import type { IeltsTest } from "@/types/ielts";

// ========================================
// کتاب کمبریج ۰۶ — تست ۱ آکادمیک (محتوای تمرینی اختصاصی Flex English)
// ========================================

export const book06: IeltsTest = {
  slug: "cambridge-06",
  bookNumber: 6,
  testNumber: 1,
  module: "ACADEMIC",
  titleFa: "کمبریج ۰۶ — تست ۱",
  titleEn: "Cambridge 06 — Test 1",
  available: true,

  reading: {
    minutes: 60,
    passages: [
      {
        part: 1,
        title: "Penguins on a Warming Planet",
        intro: "Winners, losers and surprises at the bottom of the world",
        paragraphs: [
          { label: "A", text: "Antarctica's penguins have become the poster animals of climate change, and the image the posters usually choose — a lone bird on a melting ice sheet — turns out to be misleading in an important way. There are eighteen penguin species, and they do not share a fate. Some are collapsing, some are stable, and a few are quietly expanding, all in response to the same changing ocean." },
          { label: "B", text: "The emperor penguin, the tallest and most film-famous, depends on sea ice for its extraordinary winter breeding cycle: it lays its egg on ice, incubates it through the polar dark, and raises the chick on the ice until it can swim. Too little ice and the chick falls into the sea too early; too much, and the long march to open water exhausts the parents. Emperors are therefore ice-specialists, and modelling studies project that most known colonies will be in serious trouble within decades under current warming." },
          { label: "C", text: "Adelie penguins, by contrast, are ice-dependent only in winter. In summer they need ice-free ground to nest and open water to feed. This makes their story geography-dependent: along the western Antarctic Peninsula, where warming has been fastest, Adelie colonies have crashed by tens of thousands of pairs. But further south, in the Ross Sea, the same species thrives in enormous numbers, because retreating ice has actually exposed more nesting ground and better feeding waters." },
          { label: "D", text: "The flexible generalists are doing best of all. Gentoo penguins, willing to eat almost anything and to nest on almost any beach, have pushed their range steadily southward as waters warm, founding colonies on coasts where no gentoo was recorded a century ago. Chinstraps and macaronis, specialists on krill that is itself shifting with the currents, fall between these poles, faring badly where industrial krill fishing overlaps their feeding grounds." },
          { label: "E", text: "Two lessons emerge for conservation. First, the fates of even closely related species diverge, so umbrella slogans like 'save the penguins' need replacing with species-by-species plans. Second, the Ross Sea — now the world's largest marine protected area — shows what protection can achieve: it shelters the largest remaining Adelie population precisely because fishing there is limited. A warming ocean cannot be cooled by a treaty, but the resilience of penguins, like that of reefs, turns out to depend heavily on what humans take out of the water." },
        ],
      },
      {
        part: 2,
        title: "The Sharing Economy Grows Up",
        intro: "What happened when renting your sofa became an industry",
        paragraphs: [
          { label: "A", text: "Fifteen years ago, the 'sharing economy' was a utopian vocabulary: strangers would share cars, homes and tools through apps, waste would vanish, and everyone would become a micro-entrepreneur. What exists today is both more mundane and more consequential — a set of industries worth hundreds of billions, and a fierce argument about what the word 'sharing' was ever supposed to mean." },
          { label: "B", text: "The original platforms did genuinely unlock idle assets. Ride-sharing filled empty seats in cars already making journeys; home-sharing rented spare rooms; tool libraries and car clubs put rarely used goods to work. Economists noted the efficiency happily: the same capital was producing more service. The model spread from homes and cars to parking spaces, storage, pets, boats and even dinner tables." },
          { label: "C", text: "Then capital arrived, and the meaning shifted. Investors reward growth, and genuinely shared idle assets do not scale — there are only so many spare rooms. The fastest-growing platforms therefore became fleets of purpose-bought vehicles and professionally managed property portfolios, marketed with the warm language of sharing while functioning as ordinary rental businesses with lower costs and fewer obligations." },
          { label: "D", text: "Regulators spent a decade catching up, city by city. The recurring flashpoints are housing and work. Where short-term lets multiply, long-term rents rise and neighbourhoods hollow out in the holiday season, leading cities from Amsterdam to New York to cap nights or licences. On the labour side, courts have repeatedly ruled that drivers and couriers on the biggest platforms are, in substance, employees — entitled to minimum pay and protection — a reclassification the industry has spent vast sums resisting." },
          { label: "E", text: "The most interesting developments are now the smallest. Disillusioned with the giants, communities are building genuine alternatives: cooperatively owned ride services, library-style tool shares, neighbourhood energy exchanges — often using the same software, minus the extraction. The technology the sharing economy built is not going away; what remains undecided is who owns it, and therefore whom its convenience serves." },
        ],
      },
      {
        part: 3,
        title: "Before the Alphabet",
        intro: "How writing was invented — more than once",
        paragraphs: [
          { text: "Writing is a young technology. Anatomically modern humans have existed for perhaps two hundred thousand years; the first writing appears a mere five and a half thousand years ago, and it was invented not once but at least three times independently — in Mesopotamia, in China, and in Mesoamerica — with Egypt and the Indus valley as possible additional cases that scholars still debate." },
          { text: "The Mesopotamian sequence is the best documented because its medium survived. It begins around 3300 BCE with clay tokens used for accounting; the tokens were then pressed into wet clay as marks, and the marks outlived the tokens. The earliest tablets are almost boring in their content — receipts for grain, lists of sheep, rations for named workers — which is precisely the point: writing did not begin as poetry. It began as memory for numbers, invented by temple administrators whose heads could no longer hold the economy." },
          { text: "From such humble seeds the systems grew by pressure of use. Pictures standing for things were joined by pictures standing for sounds — the rebus principle that lets a drawing of a bee stand for the syllable 'be' — and suddenly names, foreign words and abstractions could be written. Chinese script followed a comparable path from divination inscriptions on bone, while Maya writing, with its elaborate glyphs, achieved full phonetic spelling of a sophisticated court language." },
          { text: "The alphabet — the idea that a couple of dozen signs can record any utterance by sound alone — emerged late and, in the standard account, only once: from Semitic workers adapting Egyptian hieroglyphs around 1800 BCE, from which nearly every alphabet on Earth descends, whether directly or through later inspirations. Alphabets were not obviously superior: they were harder to read for complex classical languages, lacked the visual richness of characters, and for centuries existed as an awkward script for merchants while empires wrote in cuneiform." },
          { text: "What is common to every case is the social driver: writing appears where societies become too large and too busy for memory and personal trust to manage them — the tax, the debt, the treaty, the prayer to be repeated exactly. The invention was not a single spark of genius but a slow negotiation between the need to record, the materials available, and the many centuries over which a mark on clay learned to carry a human voice." },
        ],
      },
    ],
    groups: [
      {
        id: "r-g1", part: 1, type: "tfng",
        heading: "Questions 1-5",
        instruction: "Do the following statements agree with the information given in the reading passage? Write TRUE, FALSE or NOT GIVEN.",
        options: [ { label: "TRUE", text: "TRUE" }, { label: "FALSE", text: "FALSE" }, { label: "NOT GIVEN", text: "NOT GIVEN" } ],
        questions: [
          { id: "r1", number: 1, text: "All penguin species are declining because of warming.", answer: ["FALSE"], answerDisplay: "FALSE" },
          { id: "r2", number: 2, text: "Emperor penguins breed during the polar winter.", answer: ["TRUE"], answerDisplay: "TRUE" },
          { id: "r3", number: 3, text: "Adelie colonies have declined in the Ross Sea.", answer: ["FALSE"], answerDisplay: "FALSE" },
          { id: "r4", number: 4, text: "Gentoo penguins have founded colonies on coasts where they were previously unrecorded.", answer: ["TRUE"], answerDisplay: "TRUE" },
          { id: "r5", number: 5, text: "Krill fishing is banned everywhere in Antarctica.", answer: ["NOT GIVEN"], answerDisplay: "NOT GIVEN" },
        ],
      },
      {
        id: "r-g2", part: 1, type: "match-features",
        heading: "Questions 6-9",
        instruction: "Look at the following descriptions (Questions 6-9) and the list of penguin species below. Match each description with the correct species. You may use any letter more than once.",
        options: [
          { label: "Emperor", text: "Emperor" },
          { label: "Adelie", text: "Adelie" },
          { label: "Gentoo", text: "Gentoo" },
          { label: "Chinstrap/Macaroni", text: "Chinstrap/Macaroni" },
        ],
        questions: [
          { id: "r6", number: 6, text: "Suffers when ice disappears before chicks can swim.", answer: ["Emperor"], answerDisplay: "Emperor" },
          { id: "r7", number: 7, text: "Has expanded its range southward as waters warm.", answer: ["Gentoo"], answerDisplay: "Gentoo" },
          { id: "r8", number: 8, text: "Has both collapsed and thriving populations depending on location.", answer: ["Adelie"], answerDisplay: "Adelie" },
          { id: "r9", number: 9, text: "Affected by industrial fishing overlapping feeding grounds.", answer: ["Chinstrap/Macaroni"], answerDisplay: "Chinstrap/Macaroni" },
        ],
      },
      {
        id: "r-g3", part: 1, type: "sentence-completion",
        heading: "Questions 10-13",
        instruction: "Complete the sentences below. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
        wordLimit: "NO MORE THAN TWO WORDS",
        questions: [
          { id: "r10", number: 10, before: "Emperor penguins are", after: "of sea ice conditions.", answer: ["ice-specialists", "specialists"], answerDisplay: "ice-specialists" },
          { id: "r11", number: 11, before: "In summer, Adelies need ice-free ground and", after: "to feed.", answer: ["open water"], answerDisplay: "open water" },
          { id: "r12", number: 12, before: "The largest marine protected area is in the", after: ".", answer: ["ross sea", "the ross sea"], answerDisplay: "Ross Sea" },
          { id: "r13", number: 13, before: "Resilience of penguins depends on what humans", after: "of the water.", answer: ["take out"], answerDisplay: "take out" },
        ],
      },
      {
        id: "r-g4", part: 2, type: "match-headings",
        heading: "Questions 14-18",
        instruction: "The reading passage has five paragraphs, A-E. Choose the correct heading for each paragraph from the list of headings below.",
        options: [
          { label: "i", text: "Genuine efficiency from idle assets" },
          { label: "ii", text: "How the giants quietly changed the model" },
          { label: "iii", text: "A warmer vocabulary than the reality" },
          { label: "iv", text: "Cities and courts push back" },
          { label: "v", text: "Cooperative alternatives at the margins" },
          { label: "vi", text: "The end of the apps" },
        ],
        questions: [
          { id: "r14", number: 14, text: "Paragraph A", answer: ["iii"], answerDisplay: "iii" },
          { id: "r15", number: 15, text: "Paragraph B", answer: ["i"], answerDisplay: "i" },
          { id: "r16", number: 16, text: "Paragraph C", answer: ["ii"], answerDisplay: "ii" },
          { id: "r17", number: 17, text: "Paragraph D", answer: ["iv"], answerDisplay: "iv" },
          { id: "r18", number: 18, text: "Paragraph E", answer: ["v"], answerDisplay: "v" },
        ],
      },
      {
        id: "r-g5", part: 2, type: "mcq",
        heading: "Questions 19-22",
        instruction: "Choose the correct letter, A, B, C or D.",
        questions: [
          { id: "r19", number: 19, text: "Why did genuinely sharing platforms not scale?", options: [ { label: "A", text: "Apps were too slow." }, { label: "B", text: "Idle assets are limited in supply." }, { label: "C", text: "People refused to share." }, { label: "D", text: "Laws banned them everywhere." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r20", number: 20, text: "What replaced genuine sharing at the biggest platforms?", options: [ { label: "A", text: "Charity work." }, { label: "B", text: "Purpose-bought fleets and managed portfolios." }, { label: "C", text: "Public transport." }, { label: "D", text: "Government contracts." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r21", number: 21, text: "What have cities done about short-term lets?", options: [ { label: "A", text: "Nothing at all." }, { label: "B", text: "Capped nights or licences." }, { label: "C", text: "Banned tourism." }, { label: "D", text: "Built new housing." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r22", number: 22, text: "How have courts generally ruled on platform workers?", options: [ { label: "A", text: "As independent contractors always." }, { label: "B", text: "As employees in substance." }, { label: "C", text: "As volunteers." }, { label: "D", text: "As shareholders." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
      {
        id: "r-g6", part: 2, type: "summary-completion",
        heading: "Questions 23-26",
        instruction: "Complete the summary below. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
        wordLimit: "NO MORE THAN TWO WORDS",
        lines: [
          "After the idealistic phase, investment capital pushed platforms toward fleets and property portfolios marketed with the language of",
          { gap: "r23" },
          ". Regulators responded on two fronts: cities limited short-term lets to protect",
          { gap: "r24" },
          "markets, and courts reclassified drivers and couriers as",
          { gap: "r25" },
          ". Meanwhile, community-owned services using similar software represent attempts to remove the",
          { gap: "r26" },
          "from the model.",
        ],
        questions: [
          { id: "r23", number: 23, before: "the language of", after: "", answer: ["sharing"], answerDisplay: "sharing" },
          { id: "r24", number: 24, before: "to protect", after: "markets", answer: ["long-term rental", "housing", "rental"], answerDisplay: "long-term rental / housing" },
          { id: "r25", number: 25, before: "couriers as", after: "", answer: ["employees"], answerDisplay: "employees" },
          { id: "r26", number: 26, before: "remove the", after: "from the model", answer: ["extraction"], answerDisplay: "extraction" },
        ],
      },
      {
        id: "r-g7", part: 3, type: "mcq",
        heading: "Questions 27-31",
        instruction: "Choose the correct letter, A, B, C or D.",
        questions: [
          { id: "r27", number: 27, text: "How many independent inventions of writing does the passage give as established?", options: [ { label: "A", text: "One." }, { label: "B", text: "At least three." }, { label: "C", text: "Five." }, { label: "D", text: "Dozens." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r28", number: 28, text: "What were the earliest Mesopotamian tablets about?", options: [ { label: "A", text: "Poetry." }, { label: "B", text: "Religious myths." }, { label: "C", text: "Accounts and receipts." }, { label: "D", text: "Letters between kings." } ], answer: ["C"], answerDisplay: "C" },
          { id: "r29", number: 29, text: "What is the rebus principle?", options: [ { label: "A", text: "Pictures standing for sounds." }, { label: "B", text: "Writing left to right." }, { label: "C", text: "Counting with tokens." }, { label: "D", text: "Carving on bone." } ], answer: ["A"], answerDisplay: "A" },
          { id: "r30", number: 30, text: "Where did the alphabet's ancestors come from, in the standard account?", options: [ { label: "A", text: "Maya glyphs." }, { label: "B", text: "Semitic workers adapting Egyptian hieroglyphs." }, { label: "C", text: "Chinese characters." }, { label: "D", text: "Indus seals." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r31", number: 31, text: "What does the writer identify as the common social driver of writing?", options: [ { label: "A", text: "Love of art." }, { label: "B", text: "Societies too large for memory and personal trust." }, { label: "C", text: "Divine command." }, { label: "D", text: "Boredom in winter." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
      {
        id: "r-g8", part: 3, type: "note-completion",
        heading: "Questions 32-36",
        instruction: "Complete the notes below. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
        wordLimit: "NO MORE THAN TWO WORDS",
        table: {
          headers: ["THE BIRTH OF WRITING", ""],
          rows: [
            ["Mesopotamian writing evolved from clay", { gap: "r32" }, "used for accounting"],
            ["Chinese script began as divination inscriptions on", { gap: "r33" }],
            ["Maya glyphs achieved full", { gap: "r34" }, "spelling of court language"],
            ["Early alphabets were used mainly by", { gap: "r35" }, "while empires wrote in cuneiform"],
            ["Writing served the tax, the debt, the treaty and the", { gap: "r36" }],
          ],
        },
        questions: [
          { id: "r32", number: 32, answer: ["tokens"], answerDisplay: "tokens" },
          { id: "r33", number: 33, answer: ["bone"], answerDisplay: "bone" },
          { id: "r34", number: 34, answer: ["phonetic"], answerDisplay: "phonetic" },
          { id: "r35", number: 35, answer: ["merchants"], answerDisplay: "merchants" },
          { id: "r36", number: 36, answer: ["prayer"], answerDisplay: "prayer" },
        ],
      },
      {
        id: "r-g9", part: 3, type: "short-answer",
        heading: "Questions 37-40",
        instruction: "Answer the questions below. Choose NO MORE THAN THREE WORDS from the passage for each answer.",
        wordLimit: "NO MORE THAN THREE WORDS",
        questions: [
          { id: "r37", number: 37, text: "How long ago did the first writing appear?", answer: ["five and a half thousand years", "5500 years"], answerDisplay: "five and a half thousand years ago" },
          { id: "r38", number: 38, text: "Which medium preserved the Mesopotamian record?", answer: ["clay"], answerDisplay: "clay" },
          { id: "r39", number: 39, text: "Which civilisation's writing is still debated as an independent case?", answer: ["the indus valley", "indus valley", "egypt and the indus"], answerDisplay: "Egypt and the Indus valley" },
          { id: "r40", number: 40, text: "Who could no longer hold the economy in their heads, prompting writing?", answer: ["temple administrators"], answerDisplay: "temple administrators" },
        ],
      },
    ],
  },

  listening: {
    minutes: 30,
    sections: [
      {
        part: 1, title: "Booking a cooking class", context: "Phone call to a cookery school", estimatedSec: 270,
        script: [
          { speaker: "WOMAN", text: "The Spinning Bowl Cookery School, good afternoon." },
          { speaker: "MAN", text: "Hi. I'd like to book a class for my wife's birthday. She loves Italian food." },
          { speaker: "WOMAN", text: "Lovely. Our Italian classes run on Saturdays — there's Pasta from Scratch at ten, and Regional Italian at four in the afternoon." },
          { speaker: "MAN", text: "What's the difference?" },
          { speaker: "WOMAN", text: "Pasta from Scratch is hands-on — you make the dough, shape it, and eat what you make. Regional Italian is more demonstration, with dishes from four regions, plus wine tasting." },
          { speaker: "MAN", text: "She'd love the hands-on one. How long does it run?" },
          { speaker: "WOMAN", text: "Three hours, ten to one, including lunch — which is the pasta, of course." },
          { speaker: "MAN", text: "How much per person?" },
          { speaker: "WOMAN", text: "Sixty-five pounds, all ingredients included. Gift vouchers add a presentation box for three pounds if you want to give it as a present." },
          { speaker: "MAN", text: "Yes, let's add the voucher box. Do you have space this Saturday?" },
          { speaker: "WOMAN", text: "Let me check... The morning class has two places left. But if the Saturday is a surprise, we recommend booking the following week so she has time to arrange it." },
          { speaker: "MAN", text: "Good point — the 14th, then. What should she bring?" },
          { speaker: "WOMAN", text: "Just herself and flat shoes — the kitchen floor gets slippery. Aprons and everything else are provided." },
          { speaker: "MAN", text: "One more thing: she's vegetarian." },
          { speaker: "WOMAN", text: "No problem — we do a vegetarian pasta version as standard; just tell the chef on the day." },
          { speaker: "MAN", text: "Perfect. Booking for one, the 14th, with the gift box." },
          { speaker: "WOMAN", text: "Wonderful. I'll take your name and card details, and the voucher will be posted today." },
        ],
      },
      {
        part: 2, title: "A new visitor attraction: the Skyline Tower",
        context: "Radio interview about a new attraction",
        estimatedSec: 300,
        script: [
          { speaker: "NARRATOR", text: "You will hear a radio interview about a new visitor attraction." },
          { speaker: "MAN", text: "With me is Dana Whitfield, director of the new Skyline Tower, opening next month. Dana, what can visitors expect?" },
          { speaker: "WOMAN", text: "The Tower is 110 metres tall, and the viewing floor sits at 95 metres — the highest public viewpoint in the region. On clear days you can see two counties away; even in average weather, the city unfolds beautifully below." },
          { speaker: "MAN", text: "And there's more than the view?" },
          { speaker: "WOMAN", text: "Three levels, in fact. At the base, an exhibition on the city's industrial past with interactive displays for children. The viewing floor has the cafe and glass floor panels — those are already famous on social media, slightly to my alarm. And above that, for the brave, there's the outdoor skywalk, harnessed, around the tower's crown." },
          { speaker: "MAN", text: "What about access for everyone?" },
          { speaker: "WOMAN", text: "The Tower is fully step-free: lifts reach every level, including the skywalk, where we have adapted harnesses. Assistance dogs are welcome, and there are quiet hours every Tuesday morning for visitors who prefer smaller crowds and less noise." },
          { speaker: "MAN", text: "Tickets?" },
          { speaker: "WOMAN", text: "Standard admission is fourteen pounds for adults, eight for children, with under-fours free. A family ticket — two adults, two children — is thirty-eight. The skywalk costs an extra nine, booked in slots because harnesses take time. Annual passes pay for themselves in three visits and include the car park." },
          { speaker: "MAN", text: "Opening hours?" },
          { speaker: "WOMAN", text: "Ten to six, Thursday to Monday — we close Tuesdays and Wednesdays for maintenance and school visits. One request to your listeners: the glass floor panels are for photos, not for jumping. We had to say it." },
        ],
      },
      {
        part: 3, title: "Analysing survey results",
        context: "Two students discuss survey data",
        estimatedSec: 300,
        script: [
          { speaker: "NARRATOR", text: "You will hear two students discussing the results of a survey they conducted." },
          { speaker: "MAN", text: "So we got 214 responses to the survey on study habits. What do the numbers say?" },
          { speaker: "WOMAN", text: "First surprise: 60 per cent say they study best at night, but their reported grades don't back that up — the morning studiers actually have higher averages." },
          { speaker: "MAN", text: "Self-image versus reality. What about music? Didn't we ask about background music?" },
          { speaker: "WOMAN", text: "Yes — about half study with music on. But when we split by subject, music listeners dominate in maths and drop right off in reading-heavy subjects." },
          { speaker: "MAN", text: "That matches the research we read: lyrics interfere with reading comprehension but not with calculation." },
          { speaker: "WOMAN", text: "Exactly. Now the library question: 41 per cent never use the library, which the librarian will hate. But 70 per cent of those non-users live more than twenty minutes away." },
          { speaker: "MAN", text: "So it's distance, not preference. Could we map that? Postcode against library use would make a great chart for the presentation." },
          { speaker: "WOMAN", text: "I'll do the map. What about phone use — the self-reported focus time?" },
          { speaker: "MAN", text: "Median self-reported focus: 45 minutes. But 30 per cent admit checking their phone at least every ten minutes while 'focusing'." },
          { speaker: "WOMAN", text: "We should be careful there — people under-report phone checking. It's a known bias." },
          { speaker: "MAN", text: "Right — we'll present it as 'at least' those numbers, not exact ones." },
          { speaker: "WOMAN", text: "Agreed. I'll do the map and the grades chart; you write up the music and library findings. Draft by Thursday?" },
          { speaker: "MAN", text: "Thursday. And we rehearse Monday with the tutor." },
        ],
      },
      {
        part: 4, title: "Volcanoes and climate",
        context: "University lecture",
        estimatedSec: 320,
        script: [
          { speaker: "NARRATOR", text: "You will hear part of a lecture on volcanoes and climate. First, you have some time to look at questions 31 to 40." },
          { speaker: "WOMAN", text: "When Mount Pinatubo erupted in the Philippines in 1991, it cooled the entire planet by about half a degree for two years. That event transformed how climate scientists think — so today we look at volcanoes as the atmosphere's greatest natural experiment." },
          { speaker: "WOMAN", text: "The mechanism is stratospheric sulphur. An ordinary eruption, however violent, stays in the lower atmosphere and its dust rains out within weeks. But a big explosive eruption punches sulphur gases directly into the stratosphere, fifteen to thirty kilometres up, where they form a haze of droplets that reflects sunlight for years." },
          { speaker: "WOMAN", text: "The historical record is full of these experiments. The unknown eruption of 1257 — we still argue about which volcano it was — shows up in ice cores and in tree rings as the coldest northern summer of the millennium. Tambora in 1815 caused the infamous 'year without a summer' in 1816: frosts in June in New England, failed harvests across Europe, and famine." },
          { speaker: "WOMAN", text: "These events also leave fingerprints that let us calibrate other records. Sulphur layers in polar ice can be dated year by year like tree rings, and ash layers in sediments date archaeological sites. In effect, volcanoes give history a stopwatch." },
          { speaker: "WOMAN", text: "The uncomfortable modern twist is that the Pinatubo experiment is now being deliberately imitated. Several research groups are studying 'stratospheric injection' — spraying sulphur to cool the planet artificially. The 1991 eruption showed both that it works and that it does nothing about carbon dioxide: the cooling is temporary, the ocean keeps acidifying, and rainfall patterns shift unpredictably. Whether humanity chooses to run that experiment on itself is a question not for volcanologists but for everyone. Next week: how ice cores told us carbon dioxide has never been this high in 800,000 years." },
        ],
      },
    ],
    groups: [
      {
        id: "l-g1", part: 1, type: "table-completion",
        heading: "Questions 1-4",
        instruction: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["COOKERY CLASS BOOKING", ""],
          rows: [
            ["Class booked: Pasta from Scratch, on the", { gap: "l1" }, "of the month"],
            ["Class time: 10 a.m. to", { gap: "l2" }],
            ["Price per person:", { gap: "l3" }, "pounds (ingredients included)"],
            ["Extra for a gift voucher presentation box:", { gap: "l4" }, "pounds"],
          ],
        },
        questions: [
          { id: "l1", number: 1, answer: ["14th", "14", "fourteenth"], answerDisplay: "14th" },
          { id: "l2", number: 2, answer: ["one", "1", "1 p.m.", "one o'clock"], answerDisplay: "1 p.m." },
          { id: "l3", number: 3, answer: ["65", "sixty-five", "sixty five"], answerDisplay: "65" },
          { id: "l4", number: 4, answer: ["3", "three"], answerDisplay: "3" },
        ],
      },
      {
        id: "l-g2", part: 1, type: "mcq",
        heading: "Questions 5-10",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l5", number: 5, text: "What is Regional Italian?", options: [ { label: "A", text: "A hands-on pasta class." }, { label: "B", text: "A demonstration with wine tasting." }, { label: "C", text: "A market tour." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l6", number: 6, text: "What does the class price include?", options: [ { label: "A", text: "All ingredients and lunch." }, { label: "B", text: "Travel." }, { label: "C", text: "A recipe book." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l7", number: 7, text: "Why book the 14th rather than this Saturday?", options: [ { label: "A", text: "It is cheaper." }, { label: "B", text: "It is a surprise and she needs time to arrange it." }, { label: "C", text: "The class is full." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l8", number: 8, text: "What should the wife bring?", options: [ { label: "A", text: "An apron." }, { label: "B", text: "Flat shoes." }, { label: "C", text: "Her own pasta machine." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l9", number: 9, text: "How is the vegetarian request handled?", options: [ { label: "A", text: "A vegetarian version is standard — tell the chef on the day." }, { label: "B", text: "Impossible." }, { label: "C", text: "Only with two weeks' notice." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l10", number: 10, text: "How will the man pay?", options: [ { label: "A", text: "Cash on the day." }, { label: "B", text: "By card on the phone now." }, { label: "C", text: "Bank transfer later." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
      {
        id: "l-g3", part: 2, type: "mcq",
        heading: "Questions 11-15",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l11", number: 11, text: "How high is the viewing floor?", options: [ { label: "A", text: "95 metres." }, { label: "B", text: "110 metres." }, { label: "C", text: "115 metres." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l12", number: 12, text: "What is on the base level?", options: [ { label: "A", text: "The cafe." }, { label: "B", text: "An industrial-history exhibition." }, { label: "C", text: "The skywalk." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l13", number: 13, text: "What is the skywalk?", options: [ { label: "A", text: "A glass lift." }, { label: "B", text: "A harnessed outdoor walk around the crown." }, { label: "C", text: "A bridge to the car park." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l14", number: 14, text: "When are quiet hours held?", options: [ { label: "A", text: "Tuesday mornings." }, { label: "B", text: "Every evening." }, { label: "C", text: "Weekends." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l15", number: 15, text: "What does an annual pass include?", options: [ { label: "A", text: "Free skywalk." }, { label: "B", text: "The car park, and it pays back in three visits." }, { label: "C", text: "Guest tickets." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
      {
        id: "l-g4", part: 2, type: "note-completion",
        heading: "Questions 16-20",
        instruction: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["SKYLINE TOWER", ""],
          rows: [
            ["Total height: 110 metres; highest public viewpoint in the", { gap: "l16" }],
            ["Adult admission:", { gap: "l17" }, "pounds"],
            ["Family ticket (2 adults + 2 children):", { gap: "l18" }, "pounds"],
            ["Skywalk extra cost: 9 pounds, booked in", { gap: "l19" }],
            ["Open 10-6, Thursday to", { gap: "l20" }],
          ],
        },
        questions: [
          { id: "l16", number: 16, answer: ["region"], answerDisplay: "region" },
          { id: "l17", number: 17, answer: ["14", "fourteen"], answerDisplay: "14" },
          { id: "l18", number: 18, answer: ["38", "thirty-eight", "thirty eight"], answerDisplay: "38" },
          { id: "l19", number: 19, answer: ["slots"], answerDisplay: "slots" },
          { id: "l20", number: 20, answer: ["monday"], answerDisplay: "Monday" },
        ],
      },
      {
        id: "l-g5", part: 3, type: "mcq",
        heading: "Questions 21-24",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l21", number: 21, text: "What was the first surprise in the survey data?", options: [ { label: "A", text: "Night studiers believe they study best but have lower averages." }, { label: "B", text: "Nobody studies at night." }, { label: "C", text: "Grades were unmeasurable." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l22", number: 22, text: "What pattern did music show?", options: [ { label: "A", text: "Music helps all subjects." }, { label: "B", text: "Music dominates in maths but drops in reading-heavy subjects." }, { label: "C", text: "Nobody listens to music." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l23", number: 23, text: "Why do 41% never use the library?", options: [ { label: "A", text: "They dislike books." }, { label: "B", text: "Most live more than 20 minutes away." }, { label: "C", text: "It is closed at night." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l24", number: 24, text: "What chart will the woman prepare?", options: [ { label: "A", text: "A postcode map against library use." }, { label: "B", text: "A pie of favourite subjects." }, { label: "C", text: "A table of grades only." } ], answer: ["A"], answerDisplay: "A" },
        ],
      },
      {
        id: "l-g6", part: 3, type: "form-completion",
        heading: "Questions 25-30",
        instruction: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["SURVEY FINDINGS AND PLAN", ""],
          rows: [
            ["Number of responses:", { gap: "l25" }],
            ["Percentage who say they study best at night:", { gap: "l26" }, "%"],
            ["Median self-reported focus time:", { gap: "l27" }, "minutes"],
            ["Percentage checking phones at least every ten minutes:", { gap: "l28" }, "%"],
            ["Phone checking is known to be under-reported — present numbers as", { gap: "l29" }],
            ["Rehearsal with the tutor on", { gap: "l30" }],
          ],
        },
        questions: [
          { id: "l25", number: 25, answer: ["214", "two hundred and fourteen"], answerDisplay: "214" },
          { id: "l26", number: 26, answer: ["60", "sixty"], answerDisplay: "60" },
          { id: "l27", number: 27, answer: ["45", "forty-five", "forty five"], answerDisplay: "45" },
          { id: "l28", number: 28, answer: ["30", "thirty"], answerDisplay: "30" },
          { id: "l29", number: 29, answer: ["at least", "minimum"], answerDisplay: "'at least' figures" },
          { id: "l30", number: 30, answer: ["monday"], answerDisplay: "Monday" },
        ],
      },
      {
        id: "l-g7", part: 4, type: "note-completion",
        heading: "Questions 31-35",
        instruction: "Complete the notes below. Write ONE WORD ONLY for each answer.",
        wordLimit: "ONE WORD ONLY",
        table: {
          headers: ["VOLCANOES AND CLIMATE", ""],
          rows: [
            ["Pinatubo (1991) cooled the planet by about half a", { gap: "l31" }, "for two years"],
            ["Big eruptions send sulphur gases into the", { gap: "l32" }],
            ["The haze of droplets reflects", { gap: "l33" }, "for years"],
            ["The unknown eruption of 1257 left traces in ice cores and", { gap: "l34" }, "rings"],
            ["Tambora (1815) caused the 'year without a", { gap: "l35" }, "' in 1816"],
          ],
        },
        questions: [
          { id: "l31", number: 31, answer: ["degree"], answerDisplay: "degree" },
          { id: "l32", number: 32, answer: ["stratosphere"], answerDisplay: "stratosphere" },
          { id: "l33", number: 33, answer: ["sunlight"], answerDisplay: "sunlight" },
          { id: "l34", number: 34, answer: ["tree"], answerDisplay: "tree" },
          { id: "l35", number: 35, answer: ["summer"], answerDisplay: "summer" },
        ],
      },
      {
        id: "l-g8", part: 4, type: "mcq",
        heading: "Questions 36-40",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l36", number: 36, text: "What happens to dust from ordinary eruptions?", options: [ { label: "A", text: "It rains out within weeks." }, { label: "B", text: "It stays for decades." }, { label: "C", text: "It reaches the stratosphere." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l37", number: 37, text: "How do volcanoes help archaeologists?", options: [ { label: "A", text: "Ash layers date ancient sites." }, { label: "B", text: "They preserved food." }, { label: "C", text: "They built roads." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l38", number: 38, text: "What is 'stratospheric injection'?", options: [ { label: "A", text: "A natural eruption type." }, { label: "B", text: "Spraying sulphur artificially to cool the planet." }, { label: "C", text: "A rocket launch." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l39", number: 39, text: "What did Pinatubo show about cooling and CO2?", options: [ { label: "A", text: "Cooling fixes CO2 too." }, { label: "B", text: "Cooling is temporary and does nothing about CO2." }, { label: "C", text: "CO2 fell after eruptions." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l40", number: 40, text: "What is next week's lecture about?", options: [ { label: "A", text: "Earthquakes." }, { label: "B", text: "Ice cores and 800,000 years of CO2." }, { label: "C", text: "Mountain building." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
    ],
  },

  writing: {
    minutes: 60,
    tasks: [
      {
        id: "w1", taskNumber: 1, suggestedMinutes: 20, minimumWords: 150,
        prompt: "The graph below shows the percentage of the population aged 65 and over in three countries from 1980 to 2020, with projections to 2040. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
        chart: {
          type: "line", title: "Population aged 65 and over (%)", unit: "% of population",
          categories: ["1980", "2000", "2020", "2040 (proj.)"],
          series: [
            { name: "Japan", values: [9, 17, 29, 35] },
            { name: "France", values: [13, 16, 21, 25] },
            { name: "Australia", values: [10, 12, 17, 22] },
          ],
        },
        sampleAnswer: "The line graph compares the share of people aged 65 and over in Japan, France and Australia between 1980 and 2020, with a projection for 2040. Overall, all three countries are ageing, but Japan's trajectory is dramatically steeper, moving from the youngest of the three to by far the oldest. In 1980, France had the largest elderly share at 13 per cent, followed by Australia at 10 per cent and Japan at just 9 per cent. Over the next twenty years, growth was modest everywhere: France reached 16 per cent, Japan 17 per cent — overtaking France — and Australia 12 per cent. The period from 2000 to 2020 transformed the picture. Japan's figure surged to 29 per cent, the result of both long life expectancy and very low birth rates, while France rose more gently to 21 per cent and Australia to 17 per cent. The projection for 2040 extends the same pattern: Japan is expected to reach 35 per cent, France 25 per cent and Australia 22 per cent. By that point, roughly one in three Japanese residents will be 65 or older, compared with about one in five at the start of the period — a shift with obvious implications for pensions, healthcare and the workforce.",
        checklist: [
          "Overview تفاوت شیب‌ها (تند بودن ژاپن) را می‌گوید؟",
          "جابه‌جایی رتبه‌ها (اوورِتِیک شدن فرانسه) ذکر شده؟",
          "پیش‌بینی ۲۰۴۰ جدا از داده‌های واقعی گزارش شده؟",
          "اعداد کلیدی هر کشور در نقاط زمانی آمده؟",
          "حداقل ۱۵۰ کلمه؟",
        ],
      },
      {
        id: "w2", taskNumber: 2, suggestedMinutes: 40, minimumWords: 250,
        prompt: "Some people think that friendships made online are less valuable than friendships made in person. To what extent do you agree or disagree?",
        sampleAnswer: "For most of human history, friendship required proximity: the people you loved to talk to were the people you could walk to. The internet removed that condition, and a debate followed about whether the friendships it enables are worth as much as the old kind. I agree partly with the sceptics — something is genuinely different online — but I disagree that online friendships are inherently less valuable. The sceptics' strongest point concerns what bodies do for trust. Shared meals, eye contact, spontaneous laughter and the silence of two friends in the same room build a kind of knowledge that no video call fully reproduces. There is also the matter of effort: an in-person friendship cannot be maintained by tapping hearts under messages, so it selects for commitment. Critics add, fairly, that online ties are fragile — one deactivated account, one ignored message, and the connection evaporates without the social glue of a shared city or workplace. Yet the evidence cuts both ways. For shy people, for those with rare interests, for the chronically ill and for migrants far from home, online friendship is not a cheap imitation of the real thing; it is the only form available, and studies of these groups find the support they receive is measurably real — advice given, grief shared, money lent. Even the general population now routinely belongs to hybrid friendships: colleagues who became true friends, kept alive across continents by messaging apps. Calling such bonds 'online' mislabels what is simply friendship with a new tool. My own position is that the distinction that matters is not medium but depth. A friendship is valuable to the degree that both people show up — remember the appointment, notice the silence, tell the truth — and this can happen in a chat window exactly as it can fail across a dinner table. The screen changes the packaging of friendship, not its essence. In conclusion, online friendships are neither automatically shallow nor automatically equal to physical ones. They occupy, for most of us, a middle territory: more easily started, more easily lost, but capable of carrying the same loyalty and care. The task, as with all tools, is to use them to deepen rather than replace the human contact we still need.",
        checklist: [
          "موقعیت «تا حدی موافقم» روشن استدلال شده؟",
          "استدلال طرف مقابل (بدن، تعهد، شکنندگی) منصفانه ذکر شده؟",
          "گروه‌هایی که فقط دوستی آنلاین دارند ذکر شده؟",
          "تمایز «عمق نه رسانه» محور نتیجه‌گیری است؟",
          "حداقل ۲۵۰ کلمه؟",
        ],
      },
    ],
  },
};
