import type { IeltsTest } from "@/types/ielts";

// ========================================
// کتاب کمبریج ۰۴ — تست ۱ آکادمیک (محتوای تمرینی اختصاصی Flex English)
// ========================================

export const book04: IeltsTest = {
  slug: "cambridge-04",
  bookNumber: 4,
  testNumber: 1,
  module: "ACADEMIC",
  titleFa: "کمبریج ۰۴ — تست ۱",
  titleEn: "Cambridge 04 — Test 1",
  available: true,

  reading: {
    minutes: 60,
    passages: [
      {
        part: 1,
        title: "Sleep in the Animal Kingdom",
        intro: "Strange habits reveal why we need rest at all",
        paragraphs: [
          { label: "A", text: "Every animal studied so far sleeps in some form, which suggests sleep is as fundamental as eating. Yet the variety is astonishing. Elephants manage on roughly two hours a day, much of it standing; brown bats sleep around twenty. Giraffes curl their necks over their bodies for brief naps; some dolphins keep swimming by letting only half the brain sleep at a time, one eye open to watch for danger." },
          { label: "B", text: "This half-brain strategy, called unihemispheric sleep, is the clearest evidence that sleep carries costs as well as benefits. An animal that is fully unconscious cannot breathe in some species, cannot fly in others, and is easy prey in nearly all. Evolution has therefore engineered compromises everywhere, and the shape of each compromise reveals what that species can and cannot afford to lose." },
          { label: "C", text: "What is the benefit worth such risk? The leading theory is maintenance: during sleep, the brain clears metabolic waste through a recently discovered drainage system, and memories gathered while awake are sorted and filed. A second theory emphasises energy budgeting — sleep forces a period of low consumption, like a nightly fast, which matters enormously for small warm-blooded animals with fast metabolisms." },
          { label: "D", text: "Migrating birds pose the sharpest test of both theories. Some species fly for days over oceans without landing, and recordings show they spend far less time asleep than normal during the journey, without obvious ill effects. Either they sleep in very short fragments mid-flight, or migration temporarily suspends some of sleep's usual functions — a possibility that would force textbooks to add asterisks to their claims." },
          { label: "E", text: "For humans, the practical lessons are humbler but useful. Our own species' seven-to-nine-hour norm sits midway between elephant and bat, and attempts to compress it much below six hours measurably degrade attention, mood and immune function, even when people believe they have adapted. Nature's experiments suggest sleep is not a single dial but a set of separate processes, each tuned by evolution to the life an animal actually leads — and the human animal, biologically, still leads a long and busy day." },
        ],
      },
      {
        part: 2,
        title: "The Second Life of Books",
        intro: "Publishing after the digital turn",
        paragraphs: [
          { label: "A", text: "When electronic readers arrived in the late 2000s, forecasters predicted the death of the printed book within a decade. What actually happened is stranger: sales of e-books rose quickly and then plateaued, settling at somewhere between a fifth and a quarter of the market in most countries, while print recovered and has grown modestly since. The paper book, it turns out, did not need rescuing so much as a new position." },
          { label: "B", text: "The reasons for print's persistence are partly emotional. Surveys consistently report that readers associate physical books with ownership, memory and gift-giving — a book on a shelf is a small public record of who you are. Such attachments are easy to dismiss, but they translate directly into purchasing behaviour: the readers who buy the most books also buy the most paper ones, often in handsome editions that no e-commerce algorithm suggested." },
          { label: "C", text: "There are practical reasons too. E-readers excel at instant delivery and adjustable fonts, but they struggle with anything that has a complex layout: maps, footnotes, tables, children's picture books, cookbooks propped open on a kitchen counter. Publishers noticed the pattern early — genres that are read linearly migrated to screens; genres that are consulted, displayed or browsed stayed on paper almost entirely." },
          { label: "D", text: "The most consequential change has been invisible to readers: the economics of the backlist. Digital publishing makes it cheap to keep a book technically 'in print' forever, and print-on-demand machines can now produce a single paperback at a time. As a result, mid-list books that once vanished when warehouse stock ran out now generate small, steady income for authors for decades. The shelf has become endless, if less glorious." },
          { label: "E", text: "Audiobooks complicate the picture further, since they compete for the same reading hours while being consumed in entirely different situations — driving, exercising, doing housework. Their double-digit annual growth is now the industry's main engine. Nobody knows whether listening to a book 'counts' as reading it, and the question, debated endlessly online, matters commercially more than philosophically: whichever habit the young adopt will decide where the next decade's money flows." },
        ],
      },
      {
        part: 3,
        title: "Saving Disappearing Languages",
        intro: "What is lost when a language dies?",
        paragraphs: [
          { text: "Approximately seven thousand languages are spoken in the world today. Linguists estimate that one loses its last native speaker roughly every few months, and that by the end of this century fewer than half of today's languages may remain in daily use. Each death is quiet: a final conversation in a kitchen, an archive recording made too late, a dictionary nobody will speak from again." },
          { text: "Why should anyone outside the affected community care? One common answer is scientific. Each language is a natural experiment in grammar — some track the exact source of every piece of information, some have no numbers beyond three, some encode direction by compass point rather than left and right. These structures are windows into the flexibility of the human mind, and once a language is gone, the experiment cannot be rerun." },
          { text: "A second answer concerns knowledge of the natural world. Many endangered languages belong to communities with centuries of detailed observation of local ecosystems — the behaviour of fish, the properties of medicinal plants, the reading of weather signs encoded in vocabulary with no exact translation. Field researchers increasingly treat such speakers as colleagues rather than informants, precisely because the knowledge and the language that carries it are inseparable." },
          { text: "The third answer is the one speakers themselves usually give: identity. A language holds the jokes, the songs, the names of grandparents' villages and the tone in which a grandmother scolds. Communities that have revived a sleeping language — most famously Hebrew, and more recently several indigenous languages of North America and Australia — describe the change as a recovery of confidence rather than a merely linguistic achievement. Revival, however, requires resources, schools and above all community desire; well-meaning outsiders recording vocabularies cannot substitute for families speaking it at home." },
          { text: "What, then, is realistic? Total preservation is not on offer; languages have always died as communities merge and move. But documentation is cheap by the standards of what it preserves, digital archives are more durable than paper ones, and immersion schooling has a proven record where communities choose it. The likely future is a tiered world: a few hundred global languages doing commerce and science, thousands more carrying local life, and a well-organised record of whatever cannot be saved. The measure of success, linguists argue, is not stopping change — it is ensuring nothing vanishes without a trace." },
        ],
      },
    ],
    groups: [
      {
        id: "r-g1", part: 1, type: "match-headings",
        heading: "Questions 1-5",
        instruction: "The reading passage has five paragraphs, A-E. Choose the correct heading for each paragraph from the list of headings below.",
        options: [
          { label: "i", text: "A nightly fast for small bodies" },
          { label: "ii", text: "Two hours standing up" },
          { label: "iii", text: "Half a brain asleep at sea" },
          { label: "iv", text: "The bird that breaks the theory" },
          { label: "v", text: "What the risks of sleep reveal" },
          { label: "vi", text: "Lessons for the human sleeper" },
        ],
        questions: [
          { id: "r1", number: 1, text: "Paragraph A", answer: ["ii"], answerDisplay: "ii" },
          { id: "r2", number: 2, text: "Paragraph B", answer: ["v"], answerDisplay: "v" },
          { id: "r3", number: 3, text: "Paragraph C", answer: ["i"], answerDisplay: "i" },
          { id: "r4", number: 4, text: "Paragraph D", answer: ["iv"], answerDisplay: "iv" },
          { id: "r5", number: 5, text: "Paragraph E", answer: ["vi"], answerDisplay: "vi" },
        ],
      },
      {
        id: "r-g2", part: 1, type: "tfng",
        heading: "Questions 6-10",
        instruction: "Do the following statements agree with the information given in the reading passage? Write TRUE, FALSE or NOT GIVEN.",
        options: [ { label: "TRUE", text: "TRUE" }, { label: "FALSE", text: "FALSE" }, { label: "NOT GIVEN", text: "NOT GIVEN" } ],
        questions: [
          { id: "r6", number: 6, text: "Dolphins sleep with their whole brain at once.", answer: ["FALSE"], answerDisplay: "FALSE" },
          { id: "r7", number: 7, text: "Sleep helps the brain remove metabolic waste.", answer: ["TRUE"], answerDisplay: "TRUE" },
          { id: "r8", number: 8, text: "Migrating birds land on islands to sleep at night.", answer: ["NOT GIVEN"], answerDisplay: "NOT GIVEN" },
          { id: "r9", number: 9, text: "People who cut sleep below six hours always notice the decline themselves.", answer: ["FALSE"], answerDisplay: "FALSE" },
          { id: "r10", number: 10, text: "Elephants sleep longer in captivity than in the wild.", answer: ["NOT GIVEN"], answerDisplay: "NOT GIVEN" },
        ],
      },
      {
        id: "r-g3", part: 1, type: "sentence-completion",
        heading: "Questions 11-13",
        instruction: "Complete the sentences below. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
        wordLimit: "NO MORE THAN TWO WORDS",
        questions: [
          { id: "r11", number: 11, before: "Sleeping with only one brain half is called", after: "sleep.", answer: ["unihemispheric"], answerDisplay: "unihemispheric" },
          { id: "r12", number: 12, before: "The brain clears waste through a recently discovered", after: "system.", answer: ["drainage"], answerDisplay: "drainage" },
          { id: "r13", number: 13, before: "Below six hours of sleep, human attention, mood and", after: "measurably decline.", answer: ["immune function"], answerDisplay: "immune function" },
        ],
      },
      {
        id: "r-g4", part: 2, type: "mcq",
        heading: "Questions 14-18",
        instruction: "Choose the correct letter, A, B, C or D.",
        questions: [
          { id: "r14", number: 14, text: "What happened after e-book sales plateaued?", options: [ { label: "A", text: "Print recovered and grew modestly." }, { label: "B", text: "E-books disappeared." }, { label: "C", text: "Print sales collapsed." }, { label: "D", text: "Bookstores closed everywhere." } ], answer: ["A"], answerDisplay: "A" },
          { id: "r15", number: 15, text: "Why do heavy readers buy paper books, according to the passage?", options: [ { label: "A", text: "They are cheaper." }, { label: "B", text: "They carry associations of ownership, memory and gifts." }, { label: "C", text: "They are lighter." }, { label: "D", text: "Screens are unavailable." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r16", number: 16, text: "Which genres stayed mainly on paper?", options: [ { label: "A", text: "Novels read linearly." }, { label: "B", text: "Long text books." }, { label: "C", text: "Books with complex layouts like maps and cookbooks." }, { label: "D", text: "Academic journals." } ], answer: ["C"], answerDisplay: "C" },
          { id: "r17", number: 17, text: "What has print-on-demand changed for mid-list books?", options: [ { label: "A", text: "They vanish when stock runs out." }, { label: "B", text: "They can earn steady income for decades." }, { label: "C", text: "They must be re-edited." }, { label: "D", text: "They only appear as e-books." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r18", number: 18, text: "What does the writer say about audiobooks?", options: [ { label: "A", text: "They are the industry's main growth engine." }, { label: "B", text: "They are declining." }, { label: "C", text: "They replaced print entirely." }, { label: "D", text: "They are only for the young." } ], answer: ["A"], answerDisplay: "A" },
        ],
      },
      {
        id: "r-g5", part: 2, type: "summary-completion",
        heading: "Questions 19-22",
        instruction: "Complete the summary below. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
        wordLimit: "NO MORE THAN TWO WORDS",
        lines: [
          "Print books survived the digital turn partly for emotional reasons and partly for practical ones. Readers value physical books as a form of",
          { gap: "r19" },
          "and as records of identity, while screens still handle complex layouts such as maps, footnotes and",
          { gap: "r20" },
          "poorly. Behind the scenes, digital printing keeps the",
          { gap: "r21" },
          "of older titles technically in print forever, producing small but steady income. Meanwhile",
          { gap: "r22" },
          "now grow at double-digit rates because they are consumed in situations like driving and housework.",
        ],
        questions: [
          { id: "r19", number: 19, before: "a form of", after: "and as records of identity", answer: ["ownership"], answerDisplay: "ownership" },
          { id: "r20", number: 20, before: "maps, footnotes and", after: "poorly", answer: ["tables", "cookbooks"], answerDisplay: "tables / cookbooks" },
          { id: "r21", number: 21, before: "keeps the", after: "of older titles", answer: ["backlist"], answerDisplay: "backlist" },
          { id: "r22", number: 22, before: "Meanwhile", after: "now grow", answer: ["audiobooks"], answerDisplay: "audiobooks" },
        ],
      },
      {
        id: "r-g6", part: 2, type: "short-answer",
        heading: "Questions 23-26",
        instruction: "Answer the questions below. Choose NO MORE THAN THREE WORDS from the passage for each answer.",
        wordLimit: "NO MORE THAN THREE WORDS",
        questions: [
          { id: "r23", number: 23, text: "What fraction of the market have e-books settled at in most countries?", answer: ["a fifth to a quarter", "one fifth and one quarter"], answerDisplay: "a fifth to a quarter" },
          { id: "r24", number: 24, text: "Which machines can now produce a single paperback at a time?", answer: ["print-on-demand machines"], answerDisplay: "print-on-demand machines" },
          { id: "r25", number: 25, text: "Which activities compete with reading for the same hours?", answer: ["driving, exercising, housework", "driving and exercising"], answerDisplay: "driving, exercising, housework" },
          { id: "r26", number: 26, text: "What will decide where the industry's money flows next?", answer: ["the habit the young adopt", "habits of the young"], answerDisplay: "the habit the young adopt" },
        ],
      },
      {
        id: "r-g7", part: 3, type: "match-features",
        heading: "Questions 27-31",
        instruction: "Look at the following statements (Questions 27-31) and the list of reasons for preserving languages below. Match each statement with the reason it illustrates. You may use any letter more than once.",
        options: [
          { label: "Scientific value", text: "Scientific value" },
          { label: "Ecological knowledge", text: "Ecological knowledge" },
          { label: "Identity", text: "Identity" },
          { label: "None", text: "None of these" },
        ],
        questions: [
          { id: "r27", number: 27, text: "A language whose grammar requires speakers to say how they know a fact.", answer: ["Scientific value"], answerDisplay: "Scientific value" },
          { id: "r28", number: 28, text: "Vocabulary describing the behaviour of local fish and medicinal plants.", answer: ["Ecological knowledge"], answerDisplay: "Ecological knowledge" },
          { id: "r29", number: 29, text: "A revived community reporting recovered confidence.", answer: ["Identity"], answerDisplay: "Identity" },
          { id: "r30", number: 30, text: "The tone in which a grandmother scolds children.", answer: ["Identity"], answerDisplay: "Identity" },
          { id: "r31", number: 31, text: "A language with no numbers beyond three, studied by linguists.", answer: ["Scientific value"], answerDisplay: "Scientific value" },
        ],
      },
      {
        id: "r-g8", part: 3, type: "mcq",
        heading: "Questions 32-35",
        instruction: "Choose the correct letter, A, B, C or D.",
        questions: [
          { id: "r32", number: 32, text: "What does the passage say about language death today?", options: [ { label: "A", text: "It happens roughly every few months." }, { label: "B", text: "It has stopped." }, { label: "C", text: "It affects only large languages." }, { label: "D", text: "It is always sudden." } ], answer: ["A"], answerDisplay: "A" },
          { id: "r33", number: 33, text: "Why do researchers now treat speakers as colleagues?", options: [ { label: "A", text: "They need translations." }, { label: "B", text: "Knowledge is inseparable from the language carrying it." }, { label: "C", text: "Speakers pay for research." }, { label: "D", text: "Universities require it." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r34", number: 34, text: "What is essential for genuine language revival?", options: [ { label: "A", text: "Outside recording projects." }, { label: "B", text: "Government reports." }, { label: "C", text: "Community desire and families speaking it." }, { label: "D", text: "Larger dictionaries." } ], answer: ["C"], answerDisplay: "C" },
          { id: "r35", number: 35, text: "What does the writer identify as the measure of success?", options: [ { label: "A", text: "Stopping all change." }, { label: "B", text: "Saving every language." }, { label: "C", text: "Banning global languages." }, { label: "D", text: "Nothing vanishing without a trace." } ], answer: ["D"], answerDisplay: "D" },
        ],
      },
      {
        id: "r-g9", part: 3, type: "note-completion",
        heading: "Questions 36-40",
        instruction: "Complete the notes below. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
        wordLimit: "NO MORE THAN TWO WORDS",
        table: {
          headers: ["LANGUAGE LOSS AND PRESERVATION", ""],
          rows: [
            ["By 2100 fewer than half of today's languages may remain in", { gap: "r36" }, "use"],
            ["Digital archives are more durable than", { gap: "r37" }, "ones"],
            ["Hebrew is the most famous example of", { gap: "r38" }],
            ["Immersion schooling works where", { gap: "r39" }, "choose it"],
            ["Likely future: a tiered world plus an organised", { gap: "r40" }, "of what is lost"],
          ],
        },
        questions: [
          { id: "r36", number: 36, answer: ["daily"], answerDisplay: "daily" },
          { id: "r37", number: 37, answer: ["paper"], answerDisplay: "paper" },
          { id: "r38", number: 38, answer: ["revival", "language revival"], answerDisplay: "language revival" },
          { id: "r39", number: 39, answer: ["communities"], answerDisplay: "communities" },
          { id: "r40", number: 40, answer: ["record"], answerDisplay: "record" },
        ],
      },
    ],
  },

  listening: {
    minutes: 30,
    sections: [
      {
        part: 1, title: "Booking a dental appointment", context: "Phone call to a dental clinic", estimatedSec: 260,
        script: [
          { speaker: "WOMAN", text: "Bright Smile Dental, good morning. How can I help you?" },
          { speaker: "MAN", text: "Hello. I've got a chipped tooth — nothing terrible, but it's sharp. Could I see someone this week?" },
          { speaker: "WOMAN", text: "Let's look. Are you a registered patient with us?" },
          { speaker: "MAN", text: "Yes, I am. Name's Tom Bishop." },
          { speaker: "WOMAN", text: "Tom Bishop... found you. We have Dr Kaye on Tuesday morning and Dr Alvarez on Wednesday afternoon." },
          { speaker: "MAN", text: "Whoever's earlier — Tuesday works." },
          { speaker: "WOMAN", text: "Tuesday at 9:20 or 11:40. Which suits?" },
          { speaker: "MAN", text: "9:20, please. It's before work." },
          { speaker: "WOMAN", text: "Booked. If it's a chip, we'll probably do a filling or a small crown — the dentist will decide. It'll be twenty minutes for the first visit." },
          { speaker: "MAN", text: "Fine. What will it cost?" },
          { speaker: "WOMAN", text: "Consultation is 35 pounds; a filling starts from 62, a crown from 210 — but you'll only pay the consultation on Tuesday." },
          { speaker: "MAN", text: "Do you take instalments for crowns?" },
          { speaker: "WOMAN", text: "For treatments over 150 pounds, yes — three monthly payments, no interest. You'd arrange it at reception." },
          { speaker: "MAN", text: "Good to know. Anything I should do before Tuesday?" },
          { speaker: "WOMAN", text: "Avoid chewing on that side, and if it's painful, warm salt water helps. If the pain becomes severe before Tuesday, call us — we keep emergency slots at 8 each morning." },
          { speaker: "MAN", text: "Perfect, thanks very much." },
          { speaker: "WOMAN", text: "You're welcome. See you Tuesday at 9:20, Mr Bishop." },
        ],
      },
      {
        part: 2, title: "Company induction: the new building",
        context: "Welcome talk for staff",
        estimatedSec: 300,
        script: [
          { speaker: "NARRATOR", text: "You will hear a welcome talk for staff moving into a new office building." },
          { speaker: "MAN", text: "Good morning everyone, and welcome to Harbour House. Before you all disappear to your floors, five minutes of essential information." },
          { speaker: "MAN", text: "Badges first. Your new cards open the main entrance, the lift lobby and your own department's floor only. If you need other floors — the library on two, or the design studio on four — ask your manager for temporary access. Reception can replace lost badges for five pounds." },
          { speaker: "MAN", text: "Floor plan: ground floor has the canteen, open from seven in the morning till seven at night, with hot food between eleven-thirty and two. The coffee machines on every floor are free — the good ones, I'm told, not like the old building." },
          { speaker: "MAN", text: "Car parking is limited: forty spaces for two hundred staff, so it's first come, first served, and you must register your number plate with facilities. The good news is the tram stop across the road; the company covers half of a season ticket." },
          { speaker: "MAN", text: "Two rules that are new since the move. First, the sixth floor is bookable quiet space — no calls, no meetings, no noise. Second, the roof terrace closes at sunset; it has no railings on the river side yet, so please respect the sign until it's finished." },
          { speaker: "MAN", text: "Finally, IT: the wifi network name is 'HarbourHouse-staff', and your password is the same as your email until you change it. Printers are on floors one, three and five — hold your badge to the printer to release documents. Any problems, the helpdesk extension is 4-4-0-0. Welcome again, and enjoy the views." },
        ],
      },
      {
        part: 3, title: "Planning a field trip",
        context: "Discussion between two biology students",
        estimatedSec: 300,
        script: [
          { speaker: "NARRATOR", text: "You will hear two biology students planning a field trip." },
          { speaker: "WOMAN", text: "Right, the deadline for our field-trip proposal is Friday. Where shall we study?" },
          { speaker: "MAN", text: "I thought the salt marsh at Blakeney — we did a day trip there last year. Lots of invertebrates in the mud." },
          { speaker: "WOMAN", text: "The problem is tides. We'd need two low tides a fortnight apart to repeat the sampling, and the coach can't get close." },
          { speaker: "MAN", text: "What about the river site at Millbrook, then? The tutor said it has a good pollution gradient downstream of the old factory." },
          { speaker: "WOMAN", text: "It does, and it's on a bus route. We can sample upstream and downstream — classic before-and-after design." },
          { speaker: "MAN", text: "What are we measuring exactly? Invertebrate counts?" },
          { speaker: "WOMAN", text: "Species counts and water chemistry — dissolved oxygen, that's the key one. The kit is free from the lab, but we have to book it a week ahead." },
          { speaker: "MAN", text: "Then let's book it today. What about safety? Isn't the water deep by the bridge?" },
          { speaker: "WOMAN", text: "Waist-deep at most, but we all need waders and a risk form signed by the tutor. I'll draft it tonight." },
          { speaker: "MAN", text: "And dates? The report is due in six weeks, so sampling needs to happen in the next two." },
          { speaker: "WOMAN", text: "Let's do the first sampling next Wednesday if it's dry, and the repeat the week after. We can do the lab analysis in between." },
          { speaker: "MAN", text: "Agreed. I'll do the chemistry, you do the species identification — you're better with the keys." },
          { speaker: "WOMAN", text: "Deal. I'll email the tutor the whole plan tomorrow morning." },
        ],
      },
      {
        part: 4, title: "Animal camouflage",
        context: "University lecture",
        estimatedSec: 320,
        script: [
          { speaker: "NARRATOR", text: "You will hear part of a lecture on camouflage in animals. First, you have some time to look at questions 31 to 40." },
          { speaker: "WOMAN", text: "Camouflage is usually presented as a simple trick — match the background and disappear. Today I want to show you it is really a family of quite different tricks, most of which have ended up in human technology, from army uniforms to radar." },
          { speaker: "WOMAN", text: "The oldest and commonest strategy is background matching, and it goes back astonishingly far. Fossil pigment cells suggest some dinosaurs were countershaded — dark on top, light below — which is the same pattern seen on sharks and deer today. Countershading works against the sun's shading cues: it flattens the animal's three-dimensional shape into a silhouette the eye struggles to read." },
          { speaker: "WOMAN", text: "A second strategy is disruptive coloration: bold stripes and blotches that break up the outline rather than copy it. A zebra's stripes, oddly, work best when the animal is moving in a herd, producing a dazzle effect that makes it hard for a predator to track any single individual. The Royal Navy painted ships with dazzle patterns in both world wars using exactly the same logic." },
          { speaker: "WOMAN", text: "The third family is mimicry, where an animal copies something specific: a harmless hoverfly wearing the colours of a stinging wasp, an orchid mantis posing as a flower to ambush prey. Notice the direction of the benefit differs — the hoverfly deceives its predators, the mantis deceives its dinner." },
          { speaker: "WOMAN", text: "And the fourth, most remarkable of all: active camouflage. Cuttlefish and octopuses carry millions of colour cells under direct neural control and can repaint their skin in under a second, matching texture as well as colour — despite being, remarkably, colourblind themselves. How they do it remains partly open; current research suggests their skin may sense light directly. Every strategy, notice, is an arms race: as eyes evolve to see better, camouflage evolves to hide better — and neither side ever finishes." },
        ],
      },
    ],
    groups: [
      {
        id: "l-g1", part: 1, type: "table-completion",
        heading: "Questions 1-5",
        instruction: "Complete the table below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["DENTAL APPOINTMENT", ""],
          rows: [
            ["Patient's problem: a", { gap: "l1" }, "tooth"],
            ["Appointment: Tuesday at 9:20 with Dr", { gap: "l2" }],
            ["First visit lasts", { gap: "l3" }, "minutes"],
            ["Consultation fee:", { gap: "l4" }, "pounds"],
            ["Instalments available for treatments over", { gap: "l5" }, "pounds"],
          ],
        },
        questions: [
          { id: "l1", number: 1, answer: ["chipped"], answerDisplay: "chipped" },
          { id: "l2", number: 2, answer: ["kaye"], answerDisplay: "Kaye" },
          { id: "l3", number: 3, answer: ["twenty", "20"], answerDisplay: "twenty" },
          { id: "l4", number: 4, answer: ["35", "thirty-five", "thirty five"], answerDisplay: "35" },
          { id: "l5", number: 5, answer: ["150", "a hundred and fifty", "one hundred fifty"], answerDisplay: "150" },
        ],
      },
      {
        id: "l-g2", part: 1, type: "mcq",
        heading: "Questions 6-10",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l6", number: 6, text: "When is Dr Alvarez available?", options: [ { label: "A", text: "Tuesday morning." }, { label: "B", text: "Wednesday afternoon." }, { label: "C", text: "Tuesday at 11:40." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l7", number: 7, text: "How much does a crown cost from?", options: [ { label: "A", text: "£62." }, { label: "B", text: "£150." }, { label: "C", text: "£210." } ], answer: ["C"], answerDisplay: "C" },
          { id: "l8", number: 8, text: "The instalment plan is", options: [ { label: "A", text: "three monthly payments with no interest." }, { label: "B", text: "one payment upfront." }, { label: "C", text: "six payments with interest." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l9", number: 9, text: "What does the receptionist suggest for pain now?", options: [ { label: "A", text: "Ice packs." }, { label: "B", text: "Warm salt water." }, { label: "C", text: "Painkillers from the clinic." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l10", number: 10, text: "Emergency slots are kept", options: [ { label: "A", text: "at 8 each morning." }, { label: "B", text: "at 8 each evening." }, { label: "C", text: "on Fridays." } ], answer: ["A"], answerDisplay: "A" },
        ],
      },
      {
        id: "l-g3", part: 2, type: "mcq",
        heading: "Questions 11-14",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l11", number: 11, text: "Where is the design studio?", options: [ { label: "A", text: "Floor 2." }, { label: "B", text: "Floor 4." }, { label: "C", text: "Floor 6." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l12", number: 12, text: "Hot food in the canteen is available", options: [ { label: "A", text: "from 7 to 7." }, { label: "B", text: "between 11:30 and 2." }, { label: "C", text: "all day." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l13", number: 13, text: "What is said about parking?", options: [ { label: "A", text: "Everyone gets a space." }, { label: "B", text: "It is first come, first served, with 40 spaces." }, { label: "C", text: "It is free for all." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l14", number: 14, text: "Why does the roof terrace close at sunset?", options: [ { label: "A", text: "It is too cold." }, { label: "B", text: "Railings are not finished on one side." }, { label: "C", text: "It is being cleaned." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
      {
        id: "l-g4", part: 2, type: "note-completion",
        heading: "Questions 15-20",
        instruction: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["HARBOUR HOUSE — STAFF INFORMATION", ""],
          rows: [
            ["Badge replacement fee:", { gap: "l15" }, "pounds"],
            ["Quiet bookable space is on the", { gap: "l16" }, "floor"],
            ["The company covers half of a", { gap: "l17" }, "ticket"],
            ["Wifi network name: HarbourHouse-", { gap: "l18" }],
            ["Printers on floors one, three and", { gap: "l19" }],
            ["IT helpdesk extension:", { gap: "l20" }],
          ],
        },
        questions: [
          { id: "l15", number: 15, answer: ["five", "5"], answerDisplay: "five" },
          { id: "l16", number: 16, answer: ["sixth", "6th", "6"], answerDisplay: "sixth" },
          { id: "l17", number: 17, answer: ["season"], answerDisplay: "season" },
          { id: "l18", number: 18, answer: ["staff"], answerDisplay: "staff" },
          { id: "l19", number: 19, answer: ["five", "5"], answerDisplay: "five" },
          { id: "l20", number: 20, answer: ["4400", "4-4-0-0", "440"], answerDisplay: "4400" },
        ],
      },
      {
        id: "l-g5", part: 3, type: "mcq",
        heading: "Questions 21-24",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l21", number: 21, text: "Why is the salt marsh rejected?", options: [ { label: "A", text: "Too few invertebrates." }, { label: "B", text: "Tides and coach access." }, { label: "C", text: "The tutor forbids it." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l22", number: 22, text: "What makes the river site at Millbrook attractive?", options: [ { label: "A", text: "A pollution gradient." }, { label: "B", text: "Deep water." }, { label: "C", text: "Rare plants." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l23", number: 23, text: "What is the key chemical measurement?", options: [ { label: "A", text: "Salt levels." }, { label: "B", text: "Dissolved oxygen." }, { label: "C", text: "Water temperature." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l24", number: 24, text: "What must happen a week before sampling?", options: [ { label: "A", text: "Booking the lab kit." }, { label: "B", text: "Writing the report." }, { label: "C", text: "Buying waders." } ], answer: ["A"], answerDisplay: "A" },
        ],
      },
      {
        id: "l-g6", part: 3, type: "form-completion",
        heading: "Questions 25-30",
        instruction: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["FIELD TRIP PLAN", ""],
          rows: [
            ["Maximum water depth: waist-deep by the", { gap: "l25" }],
            ["Required safety item: waders plus a signed", { gap: "l26" }, "form"],
            ["First sampling: next", { gap: "l27" }, "if dry"],
            ["The man will handle the", { gap: "l28" }],
            ["The woman will handle species identification using the", { gap: "l29" }],
            ["The tutor receives the full plan by", { gap: "l30" }, "tomorrow"],
          ],
        },
        questions: [
          { id: "l25", number: 25, answer: ["bridge"], answerDisplay: "bridge" },
          { id: "l26", number: 26, answer: ["risk"], answerDisplay: "risk" },
          { id: "l27", number: 27, answer: ["wednesday"], answerDisplay: "Wednesday" },
          { id: "l28", number: 28, answer: ["chemistry"], answerDisplay: "chemistry" },
          { id: "l29", number: 29, answer: ["keys"], answerDisplay: "keys" },
          { id: "l30", number: 30, answer: ["email", "e-mail"], answerDisplay: "email" },
        ],
      },
      {
        id: "l-g7", part: 4, type: "note-completion",
        heading: "Questions 31-35",
        instruction: "Complete the notes below. Write ONE WORD ONLY for each answer.",
        wordLimit: "ONE WORD ONLY",
        table: {
          headers: ["CAMOUFLAGE STRATEGIES", ""],
          rows: [
            ["Strategy 1: background matching / countershading — makes the animal's shape look", { gap: "l31" }],
            ["Strategy 2: disruptive coloration — bold stripes and", { gap: "l32" }, "break the outline"],
            ["A zebra's stripes work best when moving in a", { gap: "l33" }],
            ["Strategy 3: mimicry — the hoverfly copies a stinging", { gap: "l34" }],
            ["The orchid mantis deceives its", { gap: "l35" }],
          ],
        },
        questions: [
          { id: "l31", number: 31, answer: ["flat", "flattened"], answerDisplay: "flat" },
          { id: "l32", number: 32, answer: ["blotches"], answerDisplay: "blotches" },
          { id: "l33", number: 33, answer: ["herd"], answerDisplay: "herd" },
          { id: "l34", number: 34, answer: ["wasp"], answerDisplay: "wasp" },
          { id: "l35", number: 35, answer: ["prey", "dinner"], answerDisplay: "prey" },
        ],
      },
      {
        id: "l-g8", part: 4, type: "mcq",
        heading: "Questions 36-40",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l36", number: 36, text: "What does countershading work against?", options: [ { label: "A", text: "The sun's shading cues." }, { label: "B", text: "Cold weather." }, { label: "C", text: "Strong smells." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l37", number: 37, text: "Who used dazzle patterns historically?", options: [ { label: "A", text: "The Royal Navy." }, { label: "B", text: "Painters." }, { label: "C", text: "Circuses." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l38", number: 38, text: "How fast can cuttlefish repaint their skin?", options: [ { label: "A", text: "In an hour." }, { label: "B", text: "In under a second." }, { label: "C", text: "Only at night." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l39", number: 39, text: "What surprising fact about octopuses is mentioned?", options: [ { label: "A", text: "They are colourblind." }, { label: "B", text: "They cannot swim." }, { label: "C", text: "They have no skin cells." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l40", number: 40, text: "How does the lecturer describe camouflage overall?", options: [ { label: "A", text: "A solved problem." }, { label: "B", text: "An arms race that never finishes." }, { label: "C", text: "A rare phenomenon." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
    ],
  },

  writing: {
    minutes: 60,
    tasks: [
      {
        id: "w1", taskNumber: 1, suggestedMinutes: 20, minimumWords: 150,
        prompt: "The table below shows the number of international visitors to three cities in 2000, 2010 and 2020, in millions. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
        chart: {
          type: "bar", title: "International visitors (millions)", unit: "million visitors",
          categories: ["2000", "2010", "2020"],
          series: [
            { name: "Paris", values: [7.6, 12.4, 15.2] },
            { name: "Istanbul", values: [2.3, 6.8, 14.5] },
            { name: "Tokyo", values: [4.4, 5.1, 9.9] },
          ],
        },
        sampleAnswer: "The bar chart compares international visitor numbers to Paris, Istanbul and Tokyo across three years: 2000, 2010 and 2020. Overall, all three cities grew substantially, but the pattern differed sharply: Paris led comfortably at the start, while Istanbul expanded fastest and had almost caught up by the end of the period. In 2000, Paris was clearly the most visited city, receiving 7.6 million international visitors — well ahead of Tokyo at 4.4 million and Istanbul at just 2.3 million. Over the next decade, Paris remained in front, nearly doubling to 12.4 million, while Istanbul nearly tripled to 6.8 million, overtaking Tokyo, whose growth was more modest at 5.1 million. The final decade confirmed the contrasting trends. Istanbul surged again, reaching 14.5 million in 2020 — only fractionally behind Paris's 15.2 million — whereas Tokyo, despite accelerating to 9.9 million, remained the least visited of the three. In summary, the gap between the leading city and the others narrowed dramatically, driven mainly by Istanbul's exceptional growth rate.",
        checklist: [
          "آیا مقایسهٔ کلی (الگوی رشد متفاوت) در Overview آمده؟",
          "آیا داده‌های هر سه سال گزارش شده؟",
          "آیا لحظهٔ جا به جایی (استانبول در ۲۰۱۰ از توکیو جلو زد) ذکر شده؟",
          "واحدها (میلیون) ذکر شده‌اند؟",
          "حداقل ۱۵۰ کلمه؟",
        ],
      },
      {
        id: "w2", taskNumber: 2, suggestedMinutes: 40, minimumWords: 250,
        prompt: "Many cities are trying to reduce car use and encourage public transport, cycling and walking. Do you think the advantages of this policy outweigh the disadvantages?",
        sampleAnswer: "From congestion charges to car-free Sundays, cities across the world are experimenting with ways to push their residents out of private cars. Such policies inconvenience some drivers and businesses in the short term, yet I believe their long-term advantages — for health, for fairness and for the cities themselves — comfortably outweigh the costs. The objections deserve a fair hearing. For people who live far from transport links, carry heavy tools, or work night shifts when buses stop running, a car is not a luxury, and restrictions can feel punitive. Small shops sometimes report losing trade when driving becomes harder, and delivery vehicles genuinely need road space. There is also a fairness question: fuel taxes and congestion charges take a bigger bite from modest incomes than from wealthy ones. Against this stand the well-documented benefits. Health heads the list: less traffic means cleaner air, quieter streets and safer roads, and every shift from driving to walking or cycling adds physical activity into ordinary days. Cities that have pedestrianised their centres, from Pontevedra in Spain to districts of London and Paris, report falling accident numbers and rising footfall — shoppers on foot, it turns out, spend more over a month than those who park once and leave. Public money also travels further: a lane of tram or bus moves several times more people than a lane of cars, making transport budgets dramatically more efficient. Finally, the climate arithmetic leaves little room for a car-centred future in growing cities. The strongest counterargument is that public transport must be good enough before restrictions bite, and here the critics are right: the policy succeeds when the alternative is attractive, not merely when the car is punished. Cities that expanded bus and cycle networks first, and applied charges afterwards, faced far less resistance and achieved faster change. In conclusion, reducing car use is less a war on drivers than a reordering of limited street space toward its most valuable uses. The transition should protect those with no realistic alternative — through exemptions, better night services and support for traders — but its direction is both necessary and, on the evidence so far, beneficial.",
        checklist: [
          "موقعیت نویسنده (مزایا بیشتر است) در مقدمه مشخص است؟",
          "معایب به‌طور منصفانه ذکر شده؟",
          "مثال‌های شهرهای واقعی استفاده شده؟",
          "شرط موفقیت سیاست (اول زیرساخت بعد محدودیت) توضیح داده شده؟",
          "حداقل ۲۵۰ کلمه؟",
        ],
      },
    ],
  },
};
