import type { IeltsTest } from "@/types/ielts";

// ========================================
// کتاب کمبریج ۰۲ — تست ۱ آکادمیک (محتوای تمرینی اختصاصی Flex English)
// ========================================

export const book02: IeltsTest = {
  slug: "cambridge-02",
  bookNumber: 2,
  testNumber: 1,
  module: "ACADEMIC",
  titleFa: "کمبریج ۰۲ — تست ۱",
  titleEn: "Cambridge 02 — Test 1",
  available: true,

  reading: {
    minutes: 60,
    passages: [
      {
        part: 1,
        title: "Fair Trade Coffee: A Complex Cup",
        intro: "The promise and problems of ethical consumerism",
        paragraphs: [
          { label: "A", text: "When the fair trade movement began in the late 1980s, its goal was simple: guarantee small coffee farmers a minimum price high enough to cover production costs, whatever the world market did. The scheme has since grown into a global certification system covering millions of producers, and the familiar logo now appears on everything from supermarket shelves to university cafes. Surveys consistently show that a majority of consumers say they are willing to pay extra for products that promise fairer conditions at the origin." },
          { label: "B", text: "Yet the economics are more tangled than the label suggests. The guaranteed minimum price acts as a safety net in years when market prices collapse, but in years when market prices rise above the fair trade floor, the premium paid to farmers shrinks to a small fixed bonus. Farmers therefore receive the most help precisely when they need it least, and comparatively little when coffee commands high prices but their own harvest fails. Critics argue that insurance schemes and access to credit would protect farmers more effectively than a price floor." },
          { label: "C", text: "Quality is a second concern. Because the certification pays a standard price regardless of taste, some cooperatives have little financial incentive to invest in better processing. Supporters reply that the social premium — the extra sum cooperatives receive for community projects — has funded washing stations, drying beds and training that have, in many regions, raised both quality and incomes together." },
          { label: "D", text: "Perhaps the sharpest criticism targets the certification itself. Obtaining and keeping the fair trade label costs money: inspection visits, paperwork and annual fees that large cooperatives absorb easily but tiny ones cannot. As a result, the poorest farmers are often excluded from the very system designed to help them, while better-organised groups — already comparatively wealthy — capture most of the benefit. Economists call this pattern 'regressive capture'." },
          { label: "E", text: "Consumers, meanwhile, overestimate how much of the premium reaches the grower. Studies of retail margins suggest that for every extra pound a shopper pays for certified coffee, only a fraction arrives at origin; the rest is absorbed along the supply chain. Campaigners respond that the figure, however small, is still more than conventional trade delivers, and that the logo also performs a valuable educational role, keeping questions of global inequality alive in the shopping aisle." },
        ],
      },
      {
        part: 2,
        title: "Do Animals Use Tools?",
        intro: "Rethinking what counts as intelligence in the wild",
        paragraphs: [
          { label: "A", text: "For most of the twentieth century, tool use was considered the defining mark of humanity: 'man the tool-maker'. Then, in 1960, Jane Goodall watched a chimpanzee strip a leafy twig and push it into a termite mound to fish out insects. Her mentor's response became famous: now we must redefine tool, redefine man, or accept chimpanzees as human. Since that day, the list of tool-using species has grown to include birds, fish, insects and even octopuses." },
          { label: "B", text: "Some cases look almost casual. Egyptian vultures pick up stones to crack ostrich eggs; sea otters float on their backs hammering shellfish against rocks balanced on their chests. Other cases show planning and learning. New Caledonian crows manufacture hooked tools from twigs, adjusting the design to the task, and pass on preferred shapes through social traditions — a crude form of cumulative culture once thought unique to humans." },
          { label: "C", text: "In the laboratory, the picture becomes stranger still. Crows presented with a novel problem — a treat floating in a narrow tube beyond reach — will select stones of the right size and drop them in to raise the water level, an ability that resembles causal understanding. Critics caution that such results can reflect learned rules rather than insight, and debate over what the experiments truly show remains lively." },
          { label: "D", text: "Definitions matter here. If a tool is any object used to change another object, then archerfish spitting jets of water at insects qualify, as do ants that use leaf fragments as carriers for building material. Many researchers prefer a stricter definition requiring modification of the object, deliberate shaping before use — a standard that excludes many charming examples but keeps the category meaningful." },
          { label: "E", text: "Why does the question fascinate us so much? Partly because tool use was long tied to human dignity, and every new species chips away at that story. But there is a practical side too: understanding how animals solve problems without language or teaching helps cognitive scientists identify which mental abilities are truly fundamental, and which are recent additions in one peculiar primate lineage." },
        ],
      },
      {
        part: 3,
        title: "Colour and the Mind",
        intro: "How colour shapes decisions we think are rational",
        paragraphs: [
          { text: "Ask people whether the colour of a room affects their thinking, and most will shrug. Yet decades of research suggest otherwise: colour reaches into decisions we experience as calm reasoning, from the marks a teacher gives to the car we buy. The challenge for scientists has been separating real effects from marketing folklore, and the results are more interesting than either extreme." },
          { text: "The best-known experiment involved combat sports. Researchers analysed Olympic taekwondo and boxing matches in which competitors were randomly assigned red or blue kits. Judged contests — but not unjudged ones — showed a measurable bias toward red, apparently because red signals dominance and aggressiveness in the human mind. When the same bouts were digitally recoloured, the bias followed the colour, not the athlete." },
          { text: "Colour also steers appetite and shopping. Warm colours such as red and orange appear to stimulate hunger, which is one reason fast-food chains favour them, while blue — rare in natural foods — is used by diet apps to make meals look less appetising. In retail, the colour of a price tag matters as much as the number on it: red tags read as deeper discounts than black tags showing identical savings, especially for men, who process price cues more swiftly when they are colour-coded." },
          { text: "Not every popular claim survives testing. The idea that surrounding students with blue improves creativity, or that pink calms prisoners, rests on thin or failed replications. One difficulty is that colour associations are partly learned and culturally specific: white signals purity in some societies and mourning in others. Even within a single culture, the same hue can carry opposite meanings — red evokes both danger and celebration — so simple one-colour-one-effect rules keep breaking down." },
          { text: "The most careful researchers now study colour not as a magic switch but as a context. A red pen may nudge a strict teacher marginally, but a friendly comment in red may read as warmer than the same words in grey. What colour reliably does is amplify the message already present. For designers, doctors marking charts, and anyone choosing how to present information, that is not a trivial power — it is a quiet background influence worth understanding, even if it never quite decides anything on its own." },
        ],
      },
    ],
    groups: [
      {
        id: "r-g1", part: 1, type: "match-info",
        heading: "Questions 1-5",
        instruction: "The reading passage has five paragraphs, A-E. Which paragraph contains the following information?",
        options: [ { label: "A", text: "A" }, { label: "B", text: "B" }, { label: "C", text: "C" }, { label: "D", text: "D" }, { label: "E", text: "E" } ],
        questions: [
          { id: "r1", number: 1, text: "an example of how the poorest producers can miss out on certification benefits", answer: ["D"], answerDisplay: "D" },
          { id: "r2", number: 2, text: "a finding about how little of the extra price paid reaches producers", answer: ["E"], answerDisplay: "E" },
          { id: "r3", number: 3, text: "the original aim of the fair trade system", answer: ["A"], answerDisplay: "A" },
          { id: "r4", number: 4, text: "a comparison with alternative forms of financial support", answer: ["B"], answerDisplay: "B" },
          { id: "r5", number: 5, text: "funding for shared facilities that also improved product standards", answer: ["C"], answerDisplay: "C" },
        ],
      },
      {
        id: "r-g2", part: 1, type: "tfng",
        heading: "Questions 6-9",
        instruction: "Do the following statements agree with the information given in the reading passage? Write TRUE, FALSE or NOT GIVEN.",
        options: [ { label: "TRUE", text: "TRUE" }, { label: "FALSE", text: "FALSE" }, { label: "NOT GIVEN", text: "NOT GIVEN" } ],
        questions: [
          { id: "r6", number: 6, text: "Most consumers say they will pay more for certified products.", answer: ["TRUE"], answerDisplay: "TRUE" },
          { id: "r7", number: 7, text: "The fair trade minimum price rises and falls with the world market price.", answer: ["FALSE"], answerDisplay: "FALSE" },
          { id: "r8", number: 8, text: "Certification fees are the same for all cooperatives regardless of size.", answer: ["FALSE"], answerDisplay: "FALSE" },
          { id: "r9", number: 9, text: "Fair trade coffee generally tastes better than conventional coffee.", answer: ["NOT GIVEN"], answerDisplay: "NOT GIVEN" },
        ],
      },
      {
        id: "r-g3", part: 1, type: "sentence-completion",
        heading: "Questions 10-13",
        instruction: "Complete the sentences below. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
        wordLimit: "NO MORE THAN TWO WORDS",
        questions: [
          { id: "r10", number: 10, before: "The guaranteed price works as a", after: "when market prices fall.", answer: ["safety net"], answerDisplay: "safety net" },
          { id: "r11", number: 11, before: "A standard price regardless of taste gives cooperatives little", after: "to improve processing.", answer: ["financial incentive", "incentive"], answerDisplay: "financial incentive" },
          { id: "r12", number: 12, before: "Economists describe the capture of benefits by wealthier groups as", after: ".", answer: ["regressive capture"], answerDisplay: "regressive capture" },
          { id: "r13", number: 13, before: "Extra money for community projects is called the", after: ".", answer: ["social premium"], answerDisplay: "social premium" },
        ],
      },
      {
        id: "r-g4", part: 2, type: "match-headings",
        heading: "Questions 14-18",
        instruction: "Choose the correct heading for paragraphs A-E from the list of headings below.",
        options: [
          { label: "i", text: "A discovery that forced a rethink" },
          { label: "ii", text: "Planning, culture and the crow" },
          { label: "iii", text: "Drawn to water: fish with aim" },
          { label: "iv", text: "Where the definition gets difficult" },
          { label: "v", text: "Why the question matters beyond curiosity" },
          { label: "vi", text: "Tools as simple habits" },
        ],
        questions: [
          { id: "r14", number: 14, text: "Paragraph A", answer: ["i"], answerDisplay: "i" },
          { id: "r15", number: 15, text: "Paragraph B", answer: ["ii"], answerDisplay: "ii" },
          { id: "r16", number: 16, text: "Paragraph C", answer: ["iii"], answerDisplay: "iii" },
          { id: "r17", number: 17, text: "Paragraph D", answer: ["iv"], answerDisplay: "iv" },
          { id: "r18", number: 18, text: "Paragraph E", answer: ["v"], answerDisplay: "v" },
        ],
      },
      {
        id: "r-g5", part: 2, type: "mcq",
        heading: "Questions 19-22",
        instruction: "Choose the correct letter, A, B, C or D.",
        questions: [
          { id: "r19", number: 19, text: "What was the reaction of Goodall's mentor to the chimpanzee observation?", options: [ { label: "A", text: "He rejected the evidence." }, { label: "B", text: "He saw it as a challenge to definitions." }, { label: "C", text: "He had predicted it years earlier." }, { label: "D", text: "He kept it secret at first." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r20", number: 20, text: "What do New Caledonian crows show, according to the passage?", options: [ { label: "A", text: "Fixed tool designs across all groups." }, { label: "B", text: "Tool shapes passed on socially." }, { label: "C", text: "An inability to learn from others." }, { label: "D", text: "Tool use limited to laboratory settings." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r21", number: 21, text: "What do critics say about the water-tube experiments?", options: [ { label: "A", text: "The crows were trained beforehand." }, { label: "B", text: "The treats were visible from above." }, { label: "C", text: "Learned rules may explain the results." }, { label: "D", text: "The sample sizes were too small." } ], answer: ["C"], answerDisplay: "C" },
          { id: "r22", number: 22, text: "Why do some researchers prefer a stricter definition of tools?", options: [ { label: "A", text: "To include ants and archerfish." }, { label: "B", text: "To keep the category meaningful." }, { label: "C", text: "To exclude all non-primates." }, { label: "D", text: "To honour older science." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
      {
        id: "r-g6", part: 2, type: "summary-completion",
        heading: "Questions 23-26",
        instruction: "Complete the summary below. Choose ONE WORD ONLY from the passage for each answer.",
        wordLimit: "ONE WORD ONLY",
        lines: [
          "Tool use was once treated as the mark of humanity, but observations since 1960 have added many species to the list. Sea otters, for example, hammer shellfish against rocks, while Egyptian vultures use stones to break open eggs. Laboratory studies with crows suggest something close to",
          { gap: "r23" },
          "understanding, though critics argue the birds may simply be applying learned rules. Definitions remain contested: some scientists require that the object be physically",
          { gap: "r24" },
          "before use. Beyond the debate, researchers value animal tool studies because they reveal which mental abilities are truly",
          { gap: "r25" },
          ", rather than recent additions found only in one",
          { gap: "r26" },
          "lineage.",
        ],
        questions: [
          { id: "r23", number: 23, before: "close to", after: "understanding", answer: ["causal"], answerDisplay: "causal" },
          { id: "r24", number: 24, before: "object be physically", after: "before use", answer: ["modified", "shaped"], answerDisplay: "modified / shaped" },
          { id: "r25", number: 25, before: "abilities are truly", after: "", answer: ["fundamental"], answerDisplay: "fundamental" },
          { id: "r26", number: 26, before: "only in one", after: "lineage", answer: ["primate"], answerDisplay: "primate" },
        ],
      },
      {
        id: "r-g7", part: 3, type: "mcq",
        heading: "Questions 27-31",
        instruction: "Choose the correct letter, A, B, C or D.",
        questions: [
          { id: "r27", number: 27, text: "What did the recolouring of combat sports footage show?", options: [ { label: "A", text: "Judges prefer blue in replay." }, { label: "B", text: "The bias follows the colour, not the athlete." }, { label: "C", text: "Red kit improves performance." }, { label: "D", text: "Random assignment failed." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r28", number: 28, text: "Why do diet apps use blue, according to the passage?", options: [ { label: "A", text: "Blue reduces appetite." }, { label: "B", text: "Blue is cheap to produce." }, { label: "C", text: "Blue improves sleep." }, { label: "D", text: "Blue reads as fresh." } ], answer: ["A"], answerDisplay: "A" },
          { id: "r29", number: 29, text: "What complicates one-colour-one-effect rules?", options: [ { label: "A", text: "Colours are hard to measure." }, { label: "B", text: "Associations are partly learned and vary." }, { label: "C", text: "Manufacturers change pigments often." }, { label: "D", text: "Most studies use animals." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r30", number: 30, text: "What does the writer conclude about colour?", options: [ { label: "A", text: "It is a magic switch." }, { label: "B", text: "Its effects are always negative." }, { label: "C", text: "It amplifies an existing message." }, { label: "D", text: "It has no measurable effect." } ], answer: ["C"], answerDisplay: "C" },
          { id: "r31", number: 31, text: "Which of these popular claims is described as weakly supported?", options: [ { label: "A", text: "Red tags reading as discounts." }, { label: "B", text: "Red signalling dominance." }, { label: "C", text: "Pink calming prisoners." }, { label: "D", text: "Warm colours stimulating hunger." } ], answer: ["C"], answerDisplay: "C" },
        ],
      },
      {
        id: "r-g8", part: 3, type: "note-completion",
        heading: "Questions 32-36",
        instruction: "Complete the notes below. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
        wordLimit: "NO MORE THAN TWO WORDS",
        table: {
          headers: ["COLOUR AND DECISIONS — KEY FINDINGS", ""],
          rows: [
            ["Judged combat sports: measurable bias toward", { gap: "r32" }],
            ["Fast-food chains favour warm colours because they stimulate", { gap: "r33" }],
            ["Red price tags read as", { gap: "r34" }, "than black tags"],
            ["White can mean purity or", { gap: "r35" }, "depending on society"],
            ["Researchers now study colour as a", { gap: "r36" }, "rather than a switch"],
          ],
        },
        questions: [
          { id: "r32", number: 32, answer: ["red"], answerDisplay: "red" },
          { id: "r33", number: 33, answer: ["hunger", "appetite"], answerDisplay: "hunger / appetite" },
          { id: "r34", number: 34, answer: ["deeper discounts"], answerDisplay: "deeper discounts" },
          { id: "r35", number: 35, answer: ["mourning"], answerDisplay: "mourning" },
          { id: "r36", number: 36, answer: ["context"], answerDisplay: "context" },
        ],
      },
      {
        id: "r-g9", part: 3, type: "short-answer",
        heading: "Questions 37-40",
        instruction: "Answer the questions below. Choose NO MORE THAN THREE WORDS from the passage for each answer.",
        wordLimit: "NO MORE THAN THREE WORDS",
        questions: [
          { id: "r37", number: 37, text: "Which sports were analysed in the best-known colour experiment?", answer: ["taekwondo and boxing", "olympic taekwondo and boxing"], answerDisplay: "taekwondo and boxing" },
          { id: "r38", number: 38, text: "Which group processes price cues more swiftly with colour-coding?", answer: ["men"], answerDisplay: "men" },
          { id: "r39", number: 39, text: "Whose behaviour might a red pen marginally influence?", answer: ["a strict teacher", "strict teacher", "teachers"], answerDisplay: "a strict teacher" },
          { id: "r40", number: 40, text: "What kind of influence does the writer call colour, worth understanding?", answer: ["a quiet background influence", "quiet background influence"], answerDisplay: "a quiet background influence" },
        ],
      },
    ],
  },

  listening: {
    minutes: 30,
    sections: [
      {
        part: 1, title: "Joining a gym", context: "Conversation at a sports centre", estimatedSec: 280,
        script: [
          { speaker: "MAN", text: "Good afternoon, Riverside Sports Centre. How can I help?" },
          { speaker: "WOMAN", text: "Hi, I'd like to ask about membership. I saw your advert — is the offer still on?" },
          { speaker: "MAN", text: "The January offer? Yes, it runs until the end of the month. It's half price for the first three months." },
          { speaker: "WOMAN", text: "Great. And what does membership include?" },
          { speaker: "MAN", text: "Everything except classes: the gym, the pool, and the sauna from six in the morning to ten at night. Classes cost two pounds each on top." },
          { speaker: "WOMAN", text: "Which classes do you run?" },
          { speaker: "MAN", text: "The popular ones are spin on Tuesdays, yoga on Wednesday mornings, and circuits — that's Thursdays at seven." },
          { speaker: "WOMAN", text: "I might try yoga. Is there a joining fee?" },
          { speaker: "MAN", text: "Normally fifteen pounds, but we waive it during the offer. You just pay your first month, which is nineteen pounds." },
          { speaker: "WOMAN", text: "That's reasonable. Do I need anything to sign up?" },
          { speaker: "MAN", text: "Photo ID and bank details for the direct debit. You can do it here at reception or online — online gives you an extra free personal training session." },
          { speaker: "WOMAN", text: "Online it is, then. One more thing — is there parking?" },
          { speaker: "MAN", text: "There's a small car park behind the building, free for two hours, and the multi-storey across the road validates tickets for members after four p.m." },
          { speaker: "WOMAN", text: "Perfect. I'll sign up tonight. Thanks for your help!" },
          { speaker: "MAN", text: "You're welcome. Enjoy your first swim!" },
        ],
      },
      {
        part: 2, title: "Harbour Museum audio guide",
        context: "Recorded guide introduction",
        estimatedSec: 300,
        script: [
          { speaker: "NARRATOR", text: "Welcome to the Harbour Museum. This short recording introduces the building and explains how your visit works." },
          { speaker: "WOMAN", text: "You are standing in the Boat Hall, the largest gallery. Straight ahead is the fishing exhibition, which tells the story of the town's fleet through objects, films and recorded interviews with fishermen. Please note that the film room seats twenty and runs every fifteen minutes; the door on the left leads to it." },
          { speaker: "WOMAN", text: "To your right, the stairs and the lift take you to the first floor, where two galleries wait: Sailors' Lives, with its famous recreation of a ship's cabin, and the temporary exhibition, which changes twice a year. This season it explores navigation instruments, from brass compasses to the first satellite trackers." },
          { speaker: "WOMAN", text: "If you have children, ask at the desk about the treasure trail — a free activity sheet that guides families through the museum looking for hidden objects. Children who complete it choose a small prize at the shop." },
          { speaker: "WOMAN", text: "A few housekeeping points. Photography is allowed everywhere except the film room. The cafe on the ground floor serves hot lunches until half past two, and the museum closes at five, with last entry at four. Lost property is kept behind the main desk for thirty days." },
          { speaker: "WOMAN", text: "Finally, a safety note: parts of the floor in the Boat Hall are original timber, uneven in places, so please watch your step and keep to the marked routes. We hope you enjoy your visit." },
        ],
      },
      {
        part: 3, title: "Choosing a statistics module",
        context: "Conversation between a student and a tutor",
        estimatedSec: 310,
        script: [
          { speaker: "NARRATOR", text: "You will hear a student discussing module choices with her tutor." },
          { speaker: "WOMAN", text: "Come in, Petra. You wanted to talk about the statistics module?" },
          { speaker: "MAN", text: "Yes — I have to pick between Statistics for Research and Advanced Methods, and I can't decide." },
          { speaker: "WOMAN", text: "The key difference is the assessment. Statistics for Research is entirely coursework — three assignments spread over the term. Advanced Methods ends with a written exam plus a small project." },
          { speaker: "MAN", text: "That matters. I panic in exams. But Advanced Methods looks better on the transcript if I apply for the research assistantship." },
          { speaker: "WOMAN", text: "It does carry more weight, yes. But so does a high mark. If coursework plays to your strengths, a first in the research module may serve you better than a bare pass in Advanced Methods." },
          { speaker: "MAN", text: "What about the teaching? I've heard Advanced Methods is all lectures." },
          { speaker: "WOMAN", text: "Two lectures a week plus a computer lab — you work with real datasets, which is genuinely useful. The research module has one lecture and a seminar where you discuss published papers." },
          { speaker: "MAN", text: "The lab sounds valuable. Do both count toward the dissertation?" },
          { speaker: "WOMAN", text: "Both are accepted, but the dissertation committee prefers to see the lab experience if your project is quantitative." },
          { speaker: "MAN", text: "My project surveys students, so it's mostly questionnaires — quantitative-ish." },
          { speaker: "WOMAN", text: "Then here's my suggestion: take Advanced Methods this term while your motivation is high, and drop to the research module only if the mid-term feedback worries you. The swap deadline is week six." },
          { speaker: "MAN", text: "That's a good safety net. I'll register for Advanced Methods today. Thank you!" },
        ],
      },
      {
        part: 4, title: "The Silk Road",
        context: "University lecture",
        estimatedSec: 320,
        script: [
          { speaker: "NARRATOR", text: "You will hear part of a lecture on the Silk Road. First, you have some time to look at questions 31 to 40." },
          { speaker: "MAN", text: "Good morning. Today we examine the Silk Road — or rather, the Silk Roads, because modern historians insist on the plural. What the name actually describes is a shifting web of caravan routes linking China to the Mediterranean across some seven thousand kilometres of mountains and deserts." },
          { speaker: "MAN", text: "The routes flourished for roughly fifteen hundred years, from around the second century BCE to the fifteenth century. Goods moved in stages: no single merchant travelled the whole distance. Chinese silk went west, yes, but so did paper, gunpowder and ceramics, while wool, glass, horses and silver travelled east." },
          { speaker: "MAN", text: "Merchants were only part of the story. The routes carried religions — Buddhism travelled from India to China along them, and later Islam spread eastwards along the same paths. Technologies mingled in the oasis towns, and so did diseases: most scholars now agree that the plague which devastated fourteenth-century Europe arrived along these corridors." },
          { speaker: "MAN", text: "Why did such an enormous network decline? Three reasons dominate. First, sea routes opened: by the 1400s, ships could carry porcelain cheaper than camels could. Second, the collapse of the Mongol Empire destroyed the security that had made long-distance trade possible. Third, political instability along the central sections choked the caravans." },
          { speaker: "MAN", text: "Interest revived in the nineteenth century when European explorers recovered manuscripts from caves near Dunhuang, and again in our own century, when new rail links and archaeology projects rebranded the routes as a heritage corridor. The lesson historians draw is simple: the Silk Road was never a single road, nor mainly about silk — it was the first great system of exchange, and its rise and fall track the rise and fall of the empires that guarded it." },
        ],
      },
    ],
    groups: [
      {
        id: "l-g1", part: 1, type: "form-completion",
        heading: "Questions 1-4",
        instruction: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["RIVERSIDE SPORTS CENTRE", ""],
          rows: [
            ["Offer: half price for the first", { gap: "l1" }, "months"],
            ["Classes cost two pounds extra, e.g. spin, yoga and", { gap: "l2" }],
            ["Normal joining fee: fifteen pounds —", { gap: "l3" }, "during the offer"],
            ["First month payment:", { gap: "l4" }, "pounds"],
          ],
        },
        questions: [
          { id: "l1", number: 1, answer: ["three", "3"], answerDisplay: "three" },
          { id: "l2", number: 2, answer: ["circuits"], answerDisplay: "circuits" },
          { id: "l3", number: 3, answer: ["waived"], answerDisplay: "waived" },
          { id: "l4", number: 4, answer: ["nineteen", "19"], answerDisplay: "nineteen" },
        ],
      },
      {
        id: "l-g2", part: 1, type: "mcq",
        heading: "Questions 5-10",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l5", number: 5, text: "When is the sauna available?", options: [ { label: "A", text: "6 a.m. to 10 p.m." }, { label: "B", text: "6 a.m. to 6 p.m." }, { label: "C", text: "10 a.m. to 10 p.m." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l6", number: 6, text: "What does the woman need to sign up?", options: [ { label: "A", text: "A passport photo." }, { label: "B", text: "Photo ID and bank details." }, { label: "C", text: "A doctor's letter." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l7", number: 7, text: "Why will the woman sign up online?", options: [ { label: "A", text: "It is cheaper." }, { label: "B", text: "The centre is closing." }, { label: "C", text: "She gets a free training session." } ], answer: ["C"], answerDisplay: "C" },
          { id: "l8", number: 8, text: "Parking behind the building is free for", options: [ { label: "A", text: "one hour." }, { label: "B", text: "two hours." }, { label: "C", text: "four hours." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l9", number: 9, text: "The multi-storey car park validates tickets for members", options: [ { label: "A", text: "before 4 p.m." }, { label: "B", text: "after 4 p.m." }, { label: "C", text: "all day." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l10", number: 10, text: "What will the woman do first at the centre?", options: [ { label: "A", text: "Swim." }, { label: "B", text: "Take a yoga class." }, { label: "C", text: "Meet a trainer." } ], answer: ["A"], answerDisplay: "A" },
        ],
      },
      {
        id: "l-g3", part: 2, type: "mcq",
        heading: "Questions 11-14",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l11", number: 11, text: "The visitor is standing in", options: [ { label: "A", text: "the film room." }, { label: "B", text: "the Boat Hall." }, { label: "C", text: "the cafe." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l12", number: 12, text: "How often does the film run?", options: [ { label: "A", text: "Every 15 minutes." }, { label: "B", text: "Every 20 minutes." }, { label: "C", text: "Every 50 minutes." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l13", number: 13, text: "The temporary exhibition currently features", options: [ { label: "A", text: "ship cabins." }, { label: "B", text: "navigation instruments." }, { label: "C", text: "treasure trails." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l14", number: 14, text: "What do children receive for completing the treasure trail?", options: [ { label: "A", text: "A free lunch." }, { label: "B", text: "A small prize at the shop." }, { label: "C", text: "A film ticket." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
      {
        id: "l-g4", part: 2, type: "note-completion",
        heading: "Questions 15-20",
        instruction: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["HARBOUR MUSEUM — VISITOR INFORMATION", ""],
          rows: [
            ["Photography allowed everywhere except the", { gap: "l15" }, "room"],
            ["Hot lunches served until", { gap: "l16" }],
            ["Museum closes at five; last entry at", { gap: "l17" }],
            ["Lost property kept behind the main desk for", { gap: "l18" }, "days"],
            ["Boat Hall floors are original", { gap: "l19" }, "— uneven"],
            ["Visitors must keep to the marked", { gap: "l20" }],
          ],
        },
        questions: [
          { id: "l15", number: 15, answer: ["film"], answerDisplay: "film" },
          { id: "l16", number: 16, answer: ["half past two", "2:30", "2.30"], answerDisplay: "half past two (2:30)" },
          { id: "l17", number: 17, answer: ["four", "4"], answerDisplay: "four" },
          { id: "l18", number: 18, answer: ["thirty", "30"], answerDisplay: "thirty" },
          { id: "l19", number: 19, answer: ["timber", "wood"], answerDisplay: "timber" },
          { id: "l20", number: 20, answer: ["routes"], answerDisplay: "routes" },
        ],
      },
      {
        id: "l-g5", part: 3, type: "mcq",
        heading: "Questions 21-25",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l21", number: 21, text: "Statistics for Research is assessed by", options: [ { label: "A", text: "a written exam." }, { label: "B", text: "three coursework assignments." }, { label: "C", text: "one project." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l22", number: 22, text: "Why does the student hesitate over Advanced Methods?", options: [ { label: "A", text: "It is more expensive." }, { label: "B", text: "It looks better for the assistantship." }, { label: "C", text: "It has no labs." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l23", number: 23, text: "What does the tutor say about a high mark?", options: [ { label: "A", text: "It may serve better than a bare pass elsewhere." }, { label: "B", text: "It is impossible in coursework." }, { label: "C", text: "It does not matter for the assistantship." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l24", number: 24, text: "Advanced Methods includes a computer lab working with", options: [ { label: "A", text: "published papers." }, { label: "B", text: "real datasets." }, { label: "C", text: "questionnaires only." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l25", number: 25, text: "The tutor's final suggestion is to", options: [ { label: "A", text: "swap modules in week six if needed." }, { label: "B", text: "avoid both modules." }, { label: "C", text: "choose the research module now." } ], answer: ["A"], answerDisplay: "A" },
        ],
      },
      {
        id: "l-g6", part: 3, type: "table-completion",
        heading: "Questions 26-30",
        instruction: "Complete the table below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["MODULE COMPARISON", ""],
          rows: [
            ["Research module: one lecture and a", { gap: "l26" }],
            ["Advanced Methods: two lectures plus a", { gap: "l27" }, "each week"],
            ["The student's dissertation project surveys", { gap: "l28" }],
            ["Committee prefers to see", { gap: "l29" }, "experience for quantitative projects"],
            ["The student will register for Advanced", { gap: "l30" }, "today"],
          ],
        },
        questions: [
          { id: "l26", number: 26, answer: ["seminar"], answerDisplay: "seminar" },
          { id: "l27", number: 27, answer: ["computer lab", "lab"], answerDisplay: "computer lab" },
          { id: "l28", number: 28, answer: ["students"], answerDisplay: "students" },
          { id: "l29", number: 29, answer: ["lab"], answerDisplay: "lab" },
          { id: "l30", number: 30, answer: ["methods"], answerDisplay: "Methods" },
        ],
      },
      {
        id: "l-g7", part: 4, type: "note-completion",
        heading: "Questions 31-35",
        instruction: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["THE SILK ROADS", ""],
          rows: [
            ["Length of routes: about seven thousand", { gap: "l31" }],
            ["Flourished from around the second century BCE to the", { gap: "l32" }, "century"],
            ["Buddhism travelled from India to", { gap: "l33" }],
            ["Manuscripts found in caves near", { gap: "l34" }],
            ["Historians describe it as the first great system of", { gap: "l35" }],
          ],
        },
        questions: [
          { id: "l31", number: 31, answer: ["kilometres", "kilometers"], answerDisplay: "kilometres" },
          { id: "l32", number: 32, answer: ["fifteenth", "15th"], answerDisplay: "fifteenth" },
          { id: "l33", number: 33, answer: ["china"], answerDisplay: "China" },
          { id: "l34", number: 34, answer: ["dunhuang"], answerDisplay: "Dunhuang" },
          { id: "l35", number: 35, answer: ["exchange"], answerDisplay: "exchange" },
        ],
      },
      {
        id: "l-g8", part: 4, type: "mcq",
        heading: "Questions 36-40",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l36", number: 36, text: "What does the lecturer stress about the name 'Silk Road'?", options: [ { label: "A", text: "It should be plural." }, { label: "B", text: "It was invented recently." }, { label: "C", text: "It describes one road." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l37", number: 37, text: "How did goods travel the routes?", options: [ { label: "A", text: "One merchant made the whole trip." }, { label: "B", text: "In stages, by different merchants." }, { label: "C", text: "Mostly by sea." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l38", number: 38, text: "What arrived in Europe along the routes in the 1300s?", options: [ { label: "A", text: "Gunpowder." }, { label: "B", text: "Porcelain." }, { label: "C", text: "The plague." } ], answer: ["C"], answerDisplay: "C" },
          { id: "l39", number: 39, text: "Which factor in the decline is NOT mentioned?", options: [ { label: "A", text: "Rising camel costs." }, { label: "B", text: "Sea routes." }, { label: "C", text: "The Mongol collapse." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l40", number: 40, text: "Why did the sea routes outcompete caravans?", options: [ { label: "A", text: "Ships carried porcelain cheaper." }, { label: "B", text: "Camels became extinct." }, { label: "C", text: "Pirates were fewer." } ], answer: ["A"], answerDisplay: "A" },
        ],
      },
    ],
  },

  writing: {
    minutes: 60,
    tasks: [
      {
        id: "w1", taskNumber: 1, suggestedMinutes: 20, minimumWords: 150,
        prompt: "The graph below shows the percentage of households with internet access in one country between 2000 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
        chart: {
          type: "line", title: "Households with internet access (%)", unit: "% of households",
          categories: ["2000", "2005", "2010", "2015", "2020"],
          series: [
            { name: "Urban", values: [18, 42, 71, 84, 92] },
            { name: "Rural", values: [5, 16, 38, 60, 79] },
          ],
        },
        sampleAnswer: "The line graph compares internet access in urban and rural households of one country over a twenty-year period. Overall, access grew dramatically in both areas, but the urban-rural gap, which peaked around 2010, narrowed steadily thereafter. In 2000, internet access was a minority experience in both places: 18 per cent of urban households and only 5 per cent of rural ones were connected. During the following decade both figures rose sharply, with urban access reaching 71 per cent by 2010, while rural access, though it more than doubled from its 2005 level, stood at just 38 per cent. This was the widest point of the gap in percentage terms. Between 2010 and 2020 growth continued but at a gentler pace, reflecting the natural slowdown as markets approach saturation. Urban households climbed to 92 per cent, while rural households reached 79 per cent, meaning the difference between the two had shrunk from 33 points to 13. The final years therefore show a clear catch-up effect in the countryside, driven in part, presumably, by improved infrastructure, although the data itself does not identify causes.",
        checklist: [
          "آیا بازهٔ زمانی و مقایسهٔ اصلی در مقدمه آمده؟",
          "آیا Overview حرکت کلی را بیان می‌کند؟",
          "آیا داده‌های عددی کلیدی هر دو گروه گزارش شده؟",
          "آیا نقطهٔ بیشینهٔ شکاف ذکر شده؟",
          "آیا حداقل ۱۵۰ کلمه دارید؟",
        ],
      },
      {
        id: "w2", taskNumber: 2, suggestedMinutes: 40, minimumWords: 250,
        prompt: "Some people believe that children today spend too much time on screens and that this harms their development. Others argue that digital skills are essential for their future. Discuss both views and give your own opinion.",
        sampleAnswer: "Few topics divide parents and educators as sharply as children's screen time. While one camp sees hours spent on devices as a direct threat to healthy development, another insists that fluency with technology is now as basic as literacy itself. Both positions contain truth, and the real challenge is distinguishing between types of screen use. Those who warn against screens point to concrete risks. Pediatric research links heavy device use with shorter sleep, reduced physical activity and weaker face-to-face social skills. Teachers frequently report pupils who struggle to concentrate through a full lesson, their attention shaped by fast-paced apps. There is also the question of content: unsupervised access can expose children to material they are not equipped to process. On these grounds, several countries have introduced guidelines urging strict limits for the youngest age groups. On the other side, advocates note that screens are the doorway through which modern life now flows. Coding, research, communication and even music lessons increasingly happen online. A child barred from devices may fall behind peers who learn to search critically, type quickly and create digital projects. The jobs today's children will apply for barely exist yet, but most forecasts agree they will demand comfortable, critical use of technology. My own view is that the debate should move from quantity to quality. An hour spent video-calling a grandparent, following a drawing tutorial or building a simple game teaches skills and maintains relationships; an identical hour of autoplaying cartoons may teach nothing. Parents and schools, therefore, should act as curators rather than gatekeepers — sitting alongside children at first, discussing what they watch, and gradually handing over responsibility. In conclusion, screens are neither poison nor panacea. The harm or benefit lies in the content and the company, and teaching children to choose well is a far more useful lesson than counting their minutes.",
        checklist: [
          "هر دو دیدگاه با دلیل بررسی شده؟",
          "نظر شخصی به‌وضوح بیان شده؟",
          "تفکیک «نوع استفاده» به‌جای «مقدار» محور استدلال است؟",
          "جمع‌بندی، استدلال را تکرار نمی‌کند بلکه آن را کامل می‌کند؟",
          "حداقل ۲۵۰ کلمه؟",
        ],
      },
    ],
  },
};
