import type { IeltsTest } from "@/types/ielts";

// ========================================
// کتاب کمبریج ۰۳ — تست ۱ آکادمیک (محتوای تمرینی اختصاصی Flex English)
// ========================================

export const book03: IeltsTest = {
  slug: "cambridge-03",
  bookNumber: 3,
  testNumber: 1,
  module: "ACADEMIC",
  titleFa: "کمبریج ۰۳ — تست ۱",
  titleEn: "Cambridge 03 — Test 1",
  available: true,

  reading: {
    minutes: 60,
    passages: [
      {
        part: 1,
        title: "Handwriting: A Skill Under Threat",
        intro: "Why schools are still arguing about pen and paper",
        paragraphs: [
          { label: "A", text: "In 2016, Finland announced that cursive handwriting would no longer be a compulsory part of its school curriculum, joining a small group of countries that have made the same move. The reasoning was pragmatic: keyboards are how most written communication now happens, and school hours are finite. Reaction elsewhere was swift and largely hostile, with commentators arguing that a civilization was abandoning one of its oldest skills." },
          { label: "B", text: "The scientific case for keeping handwriting rests heavily on how the brain processes letter formation. Studies using brain imaging show that writing letters by hand activates regions associated with reading and memory far more strongly than typing them. In classroom experiments, children who practised letters by hand recognised them faster and remembered taught words better than children who typed the same material. The effect appears even before children can read fluently." },
          { label: "C", text: "Note-taking research tells a similar story. University students who take notes by hand, forced to summarise because they cannot transcribe at speed, score higher on conceptual questions than laptop users, who tend to type everything verbatim without processing it. Interestingly, the advantage disappears when students are told to avoid verbatim typing, suggesting the benefit comes from the summarising itself, for which handwriting simply happens to be the natural tool." },
          { label: "D", text: "Defenders of keyboards reply that nostalgia is not a pedagogy. For children with dysgraphia or motor-control difficulties, handwriting is torture and typing is liberation. Digital text is searchable, editable and instantly shareable — features that matter for collaboration. Moreover, they argue, the studies compare typing done badly with handwriting done well; a keyboard used thoughtfully could, in principle, produce the same summarising behaviour." },
          { label: "E", text: "Most education systems have settled on a compromise: teach printing, keep cursive optional, and ensure every child can type. Whether this middle path retains the cognitive benefits is unclear, because almost all research contrasts pure handwriting with pure typing, not mixtures. What is clear is that the question is empirical rather than sentimental — and that the answer will shape curricula for decades." },
        ],
      },
      {
        part: 2,
        title: "Coral Reefs in Hot Water",
        intro: "The fight to save the ocean's rainforests",
        paragraphs: [
          { label: "A", text: "Coral reefs occupy less than one per cent of the ocean floor yet shelter roughly a quarter of all marine species. They also protect coastlines from storms, support fishing and tourism industries worth billions, and feed hundreds of millions of people. It is an unfortunate irony that the most valuable ecosystems in the sea are also among the most fragile." },
          { label: "B", text: "The immediate threat is bleaching. Coral animals live in partnership with tiny algae that live inside their tissues and supply them with food through photosynthesis. When water temperatures rise beyond a threshold, the corals expel the algae — perhaps as a stress response — and turn ghostly white. Bleached coral is starving but not dead; if temperatures fall within weeks, algae return and the colony recovers. If heat persists, the coral dies, and the reef begins to crumble." },
          { label: "C", text: "Mass bleaching events used to be rare. Records before the 1980s show almost none at regional scale. Since then, global bleaching has struck repeatedly, and the intervals between events have shortened beyond the decade or so that reefs need to recover. The result, on many reefs, is a silent transformation: branching corals, the fastest growers and the best fish habitat, die first, leaving slower, weedier species behind. Fish populations follow the structure downward." },
          { label: "D", text: "Local protection, however, still matters. Reefs inside well-enforced marine reserves, with clean water and intact fish populations, recover from bleaching faster than stressed reefs. Parrotfish, for example, graze the algae that otherwise smother wounded coral; where fishing has removed the grazers, recovery stalls. Marine parks cannot lower the water temperature, but they can raise a reef's capacity to bounce back from the heat it cannot avoid." },
          { label: "E", text: "The long-term answer is necessarily global, because no local measure can outpace unlimited warming. Yet scientists are also preparing assistive techniques: breeding heat-tolerant coral strains in laboratories, shading reefs during peak heat, even using underwater loudspeakers to lure fish larvae back to degraded sites. Critics worry such interventions are expensive distractions from emissions cuts. Supporters answer that a patient fighting a fever still benefits from being kept comfortable — the two treatments are not rivals but companions." },
        ],
      },
      {
        part: 3,
        title: "The Dreaming Machine",
        intro: "What happens in the sleeping brain",
        paragraphs: [
          { text: "Every night, without asking permission, each of us attends a private cinema: the brain generates images, emotions and stories that feel, at the time, entirely real. For most of the twentieth century, science treated this cinema as noise — a by-product of random neural housekeeping. That view has collapsed. Dreaming is now understood to be a structured, biologically expensive state with measurable jobs to do." },
          { text: "The physical signature of dreaming is REM sleep, a stage in which the brain runs at near-waking energy levels while the body's muscles are paralysed to prevent the acting-out of dreams. But dreams also occur outside REM, more often and with different texture — quieter, more thought-like, less bizarre. What distinguishes dreaming across both stages is the shutdown of the brain's executive regions, which handle logic and self-control, alongside continued activity in emotional and visual circuits. The dreamer is, in effect, a car with the engine running and the steering disconnected." },
          { text: "One influential theory assigns dreaming a role in emotional first aid. Studies find that REM sleep preferentially processes recent emotional memories, stripping much of their painful charge while preserving their content — a process one researcher has described as 'overnight therapy'. People deprived of REM sleep after distressing events show stronger emotional reactions the next day, and patients suffering certain sleep disorders report dreams that rehearse trauma with unusual frequency." },
          { text: "A second theory focuses on creativity and problem-solving. With the brain's rule-checking regions offline, remote associations become easier; dreams regularly combine memories into combinations that waking thought would reject. Historical anecdotes — the chemist who saw the structure of a molecule in a dream, the musician who woke with a melody — now have laboratory support: participants woken from REM solve anagram puzzles better than participants woken from other stages." },
          { text: "There is also a humbler explanation to keep in view: dreams may simply be the brain making sense of its own noise, constructing narrative order from random signals. This theory, too, predicts why dreams feel meaningful — the meaning would be manufactured after the fact. The theories are not mutually exclusive. A system that began as noise-interpretation could easily have been recruited, over evolutionary time, to do therapy and creative work as well. What all current accounts agree on is the conclusion the ancients drew by intuition: the third of life we spend asleep is not a pause in living, but a different mode of it." },
        ],
      },
    ],
    groups: [
      {
        id: "r-g1", part: 1, type: "mcq",
        heading: "Questions 1-5",
        instruction: "Choose the correct letter, A, B, C or D.",
        questions: [
          { id: "r1", number: 1, text: "Why did Finland drop compulsory cursive writing?", options: [ { label: "A", text: "Children disliked it." }, { label: "B", text: "School time is limited and keyboards dominate." }, { label: "C", text: "Teachers could not teach it." }, { label: "D", text: "It was never taught there." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r2", number: 2, text: "What do brain-imaging studies of handwriting show?", options: [ { label: "A", text: "Typing activates more regions." }, { label: "B", text: "Handwriting strongly activates reading and memory regions." }, { label: "C", text: "Letter formation blocks memory." }, { label: "D", text: "No difference was found." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r3", number: 3, text: "Why do hand-writers score better on conceptual questions?", options: [ { label: "A", text: "They write faster." }, { label: "B", text: "They must summarise rather than transcribe." }, { label: "C", text: "They avoid all technology." }, { label: "D", text: "They read more books." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r4", number: 4, text: "What point do keyboard defenders make?", options: [ { label: "A", text: "Typing is always superior." }, { label: "B", text: "Dysgraphia makes typing a liberation for some." }, { label: "C", text: "Laptops cost less." }, { label: "D", text: "Cursive is impossible to learn." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r5", number: 5, text: "What does the writer say about the compromise most schools have adopted?", options: [ { label: "A", text: "It is well researched." }, { label: "B", text: "Its cognitive effects are unknown." }, { label: "C", text: "It clearly works." }, { label: "D", text: "It was forced by parents." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
      {
        id: "r-g2", part: 1, type: "tfng",
        heading: "Questions 6-10",
        instruction: "Do the following statements agree with the information given in the reading passage? Write TRUE, FALSE or NOT GIVEN.",
        options: [ { label: "TRUE", text: "TRUE" }, { label: "FALSE", text: "FALSE" }, { label: "NOT GIVEN", text: "NOT GIVEN" } ],
        questions: [
          { id: "r6", number: 6, text: "Finland was the first country ever to make this curriculum change.", answer: ["FALSE"], answerDisplay: "FALSE" },
          { id: "r7", number: 7, text: "Handwriting benefits appear only after children learn to read fluently.", answer: ["FALSE"], answerDisplay: "FALSE" },
          { id: "r8", number: 8, text: "Told to avoid verbatim notes, laptop users lost their disadvantage.", answer: ["TRUE"], answerDisplay: "TRUE" },
          { id: "r9", number: 9, text: "Digital text is searchable and shareable.", answer: ["TRUE"], answerDisplay: "TRUE" },
          { id: "r10", number: 10, text: "Most parents support keeping cursive in schools.", answer: ["NOT GIVEN"], answerDisplay: "NOT GIVEN" },
        ],
      },
      {
        id: "r-g3", part: 1, type: "sentence-completion",
        heading: "Questions 11-13",
        instruction: "Complete the sentences below. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
        wordLimit: "NO MORE THAN TWO WORDS",
        questions: [
          { id: "r11", number: 11, before: "The public reaction to Finland's decision was mostly", after: ".", answer: ["hostile"], answerDisplay: "hostile" },
          { id: "r12", number: 12, before: "Children with dysgraphia or", after: "difficulties find handwriting painful.", answer: ["motor-control", "motor control"], answerDisplay: "motor-control" },
          { id: "r13", number: 13, before: "According to the writer, the handwriting question is empirical, not", after: ".", answer: ["sentimental"], answerDisplay: "sentimental" },
        ],
      },
      {
        id: "r-g4", part: 2, type: "match-info",
        heading: "Questions 14-18",
        instruction: "The reading passage has five paragraphs, A-E. Which paragraph contains the following information?",
        options: [ { label: "A", text: "A" }, { label: "B", text: "B" }, { label: "C", text: "C" }, { label: "D", text: "D" }, { label: "E", text: "E" } ],
        questions: [
          { id: "r14", number: 14, text: "a comparison of reef value with their fragility", answer: ["A"], answerDisplay: "A" },
          { id: "r15", number: 15, text: "the mechanism that makes corals turn white", answer: ["B"], answerDisplay: "B" },
          { id: "r16", number: 16, text: "how reefs change when recovery time is too short", answer: ["C"], answerDisplay: "C" },
          { id: "r17", number: 17, text: "the role of grazing fish in recovery", answer: ["D"], answerDisplay: "D" },
          { id: "r18", number: 18, text: "technologies being developed to help reefs directly", answer: ["E"], answerDisplay: "E" },
        ],
      },
      {
        id: "r-g5", part: 2, type: "note-completion",
        heading: "Questions 19-23",
        instruction: "Complete the notes below. Choose ONE WORD ONLY from the passage for each answer.",
        wordLimit: "ONE WORD ONLY",
        table: {
          headers: ["CORAL BLEACHING", ""],
          rows: [
            ["Corals depend on algae that provide food through", { gap: "r19" }],
            ["A bleached coral is starving but not yet", { gap: "r20" }],
            ["Branching corals provide the best fish", { gap: "r21" }],
            ["Well-enforced marine reserves raise a reef's ability to", { gap: "r22" }],
            ["Laboratories are breeding heat-", { gap: "r23" }, "coral strains"],
          ],
        },
        questions: [
          { id: "r19", number: 19, answer: ["photosynthesis"], answerDisplay: "photosynthesis" },
          { id: "r20", number: 20, answer: ["dead"], answerDisplay: "dead" },
          { id: "r21", number: 21, answer: ["habitat"], answerDisplay: "habitat" },
          { id: "r22", number: 22, answer: ["recover", "bounce"], answerDisplay: "recover / bounce (back)" },
          { id: "r23", number: 23, answer: ["tolerant"], answerDisplay: "tolerant" },
        ],
      },
      {
        id: "r-g6", part: 2, type: "short-answer",
        heading: "Questions 24-26",
        instruction: "Answer the questions below. Choose NO MORE THAN THREE WORDS from the passage for each answer.",
        wordLimit: "NO MORE THAN THREE WORDS",
        questions: [
          { id: "r24", number: 24, text: "What proportion of marine species do reefs shelter?", answer: ["a quarter", "roughly a quarter", "quarter"], answerDisplay: "roughly a quarter" },
          { id: "r25", number: 25, text: "Which fish species grazes algae that smother coral?", answer: ["parrotfish"], answerDisplay: "Parrotfish" },
          { id: "r26", number: 26, text: "What device lures fish larvae back to degraded sites?", answer: ["underwater loudspeakers", "loudspeakers"], answerDisplay: "underwater loudspeakers" },
        ],
      },
      {
        id: "r-g7", part: 3, type: "mcq",
        heading: "Questions 27-32",
        instruction: "Choose the correct letter, A, B, C or D.",
        questions: [
          { id: "r27", number: 27, text: "How did most of twentieth-century science regard dreams?", options: [ { label: "A", text: "As structured work." }, { label: "B", text: "As meaningless noise." }, { label: "C", text: "As messages to decode." }, { label: "D", text: "As rehearsals of trauma." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r28", number: 28, text: "What happens to muscles during REM sleep?", options: [ { label: "A", text: "They twitch constantly." }, { label: "B", text: "They are paralysed." }, { label: "C", text: "They cool down." }, { label: "D", text: "They grow rapidly." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r29", number: 29, text: "How are non-REM dreams described?", options: [ { label: "A", text: "Louder and more bizarre." }, { label: "B", text: "Quieter and more thought-like." }, { label: "C", text: "Always frightening." }, { label: "D", text: "Completely absent." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r30", number: 30, text: "What does the 'overnight therapy' theory claim?", options: [ { label: "A", text: "REM sleep strips painful charge from emotional memories." }, { label: "B", text: "Dreams erase all memories." }, { label: "C", text: "Therapy replaces sleep." }, { label: "D", text: "Only therapists dream." } ], answer: ["A"], answerDisplay: "A" },
          { id: "r31", number: 31, text: "Why might dreams aid creativity, according to the passage?", options: [ { label: "A", text: "Rules are checked more strictly." }, { label: "B", text: "Remote associations become easier." }, { label: "C", text: "The brain sleeps deeply." }, { label: "D", text: "Emotions are switched off." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r32", number: 32, text: "What does the humbler theory say about dream meaning?", options: [ { label: "A", text: "Meaning is manufactured after the fact." }, { label: "B", text: "Meaning comes from ancestors." }, { label: "C", text: "Dreams have fixed symbols." }, { label: "D", text: "Meaning cannot be studied." } ], answer: ["A"], answerDisplay: "A" },
        ],
      },
      {
        id: "r-g8", part: 3, type: "summary-completion",
        heading: "Questions 33-37",
        instruction: "Complete the summary below. Choose ONE WORD ONLY from the passage for each answer.",
        wordLimit: "ONE WORD ONLY",
        lines: [
          "During dreaming, the brain's executive regions — those handling logic and self-control — are offline, while emotional and",
          { gap: "r33" },
          "circuits stay active. One theory likens REM processing to overnight",
          { gap: "r34" },
          ", because it reduces the painful charge of recent memories. Laboratory evidence links REM to solving anagram",
          { gap: "r35" },
          "better than other sleep stages. An older, humbler view holds that dreams impose narrative",
          { gap: "r36" },
          "on random neural signals. The writer notes the theories may all be true, since a noise-interpretation system could later be",
          { gap: "r37" },
          "for emotional and creative work.",
        ],
        questions: [
          { id: "r33", number: 33, before: "emotional and", after: "circuits", answer: ["visual"], answerDisplay: "visual" },
          { id: "r34", number: 34, before: "likened to overnight", after: "", answer: ["therapy"], answerDisplay: "therapy" },
          { id: "r35", number: 35, before: "solving anagram", after: "better", answer: ["puzzles"], answerDisplay: "puzzles" },
          { id: "r36", number: 36, before: "impose narrative", after: "on random neural signals", answer: ["order"], answerDisplay: "order" },
          { id: "r37", number: 37, before: "could later be", after: "for emotional and creative work", answer: ["recruited"], answerDisplay: "recruited" },
        ],
      },
      {
        id: "r-g9", part: 3, type: "tfng",
        heading: "Questions 38-40",
        instruction: "Do the following statements agree with the information given in the reading passage? Write TRUE, FALSE or NOT GIVEN.",
        options: [ { label: "TRUE", text: "TRUE" }, { label: "FALSE", text: "FALSE" }, { label: "NOT GIVEN", text: "NOT GIVEN" } ],
        questions: [
          { id: "r38", number: 38, text: "Dreaming consumes little energy.", answer: ["FALSE"], answerDisplay: "FALSE" },
          { id: "r39", number: 39, text: "The three theories of dreaming contradict each other completely.", answer: ["FALSE"], answerDisplay: "FALSE" },
          { id: "r40", number: 40, text: "Dream content can be recorded and replayed with current technology.", answer: ["NOT GIVEN"], answerDisplay: "NOT GIVEN" },
        ],
      },
    ],
  },

  listening: {
    minutes: 30,
    sections: [
      {
        part: 1, title: "Reporting a lost bag", context: "Phone call to a bus company", estimatedSec: 270,
        script: [
          { speaker: "WOMAN", text: "Good morning, National Bus Lines, lost property department." },
          { speaker: "MAN", text: "Hello. I left a bag on the 10:15 coach from Oxford to Bristol yesterday." },
          { speaker: "WOMAN", text: "I'm sorry to hear that. I'll need a few details. Can you describe the bag?" },
          { speaker: "MAN", text: "It's a dark green rucksack with a small Manchester United badge on the front pocket." },
          { speaker: "WOMAN", text: "Green rucksack, badge on the front — noted. What was inside?" },
          { speaker: "MAN", text: "Mainly clothes, but also a laptop charger and a paperback novel. Oh, and my passport — that's what worries me most." },
          { speaker: "WOMAN", text: "A passport is important. Let me check the driver's report... Yes, a green rucksack was handed in at Bristol coach station at 12:40." },
          { speaker: "MAN", text: "That's a relief! Can someone post it to me?" },
          { speaker: "WOMAN", text: "We can, but not with the passport inside — our policy is not to post identity documents. You'd need to collect that in person with photo ID." },
          { speaker: "MAN", text: "I work in Bath. Is the Bristol office open Saturdays?" },
          { speaker: "WOMAN", text: "It's open Monday to Friday, nine to five, and Saturday mornings until one." },
          { speaker: "MAN", text: "I'll come Saturday morning then. Is there a fee?" },
          { speaker: "WOMAN", text: "Storage is free for the first seven days; after that it's two pounds a day. And if you want the rest posted, courier is six pounds fifty." },
          { speaker: "MAN", text: "Let's do that — post the clothes and charger, and I'll pick up the passport." },
          { speaker: "WOMAN", text: "Perfect. I'll need your full name and address for the courier label." },
          { speaker: "MAN", text: "It's Daniel Osei, 14 Kingsway, Bath, BA1 2AB." },
          { speaker: "WOMAN", text: "Thank you, Mr Osei. Reference number is L-P-4-2-9. Anything else today?" },
          { speaker: "MAN", text: "No, that's everything. You've saved my week!" },
        ],
      },
      {
        part: 2, title: "The Marshfield Food Festival",
        context: "Local radio programme",
        estimatedSec: 300,
        script: [
          { speaker: "NARRATOR", text: "You will hear a radio presenter talking about a local food festival." },
          { speaker: "MAN", text: "Good morning, and a very sunny one it is for the opening of the Marshfield Food Festival, now in its ninth year. Here's what you need to know before you set off." },
          { speaker: "MAN", text: "First, getting there. The festival takes over the whole market square and the streets around it, which means the square car park is closed to the public. Free parking is signposted from the ring road — follow the yellow signs to the college field, about ten minutes' walk away. If you're coming by train, the station is a fifteen-minute walk, and there's a shuttle bus for anyone who needs it." },
          { speaker: "MAN", text: "Admission this year is five pounds, with under-twentens free — and note, that's changed from last year, when children paid one pound. All the money goes to the town's food bank, which the festival has supported since the beginning." },
          { speaker: "MAN", text: "Now the food itself. Sixty-two stalls this year, up from fifty last year, spread over three zones. Zone A, by the church, is all about local producers: cheeses, breads, honey, and the famous Marshfield sausages. Zone B, along the river side, hosts the international stalls — anything from Nepalese dumplings to Brazilian street food. Zone C, in the college grounds, is where you'll find the cookery demonstrations, running hourly from eleven until five." },
          { speaker: "MAN", text: "A few highlights not to miss: the bread-baking contest at one o'clock, judged as always by the mayor; the chili-eating challenge at three — competitors, sign up early, it filled up in an hour last year; and the closing fireworks over the river at half past eight. Whatever you do, don't miss the sausages. See you there!" },
        ],
      },
      {
        part: 3, title: "Feedback on a marketing essay",
        context: "Conversation between a tutor and a student",
        estimatedSec: 310,
        script: [
          { speaker: "NARRATOR", text: "You will hear a tutor giving feedback on a student's marketing essay." },
          { speaker: "WOMAN", text: "Kwame, thanks for coming. I've marked your essay on brand loyalty. There's good news and there's homework." },
          { speaker: "MAN", text: "Go on — I'll take the good news first." },
          { speaker: "WOMAN", text: "The good news is your structure. Clear question, clear sections, and your conclusion actually follows from the evidence, which is rarer than it should be. Your case study of the sports shoe brands was well chosen and vividly written." },
          { speaker: "MAN", text: "That took ages to research. What's the homework part?" },
          { speaker: "WOMAN", text: "Two things. First, you rely almost entirely on one source for the survey data — the twenty-twenty-one industry report. You need at least two more sources to triangulate; the academic journals have better numbers anyway." },
          { speaker: "MAN", text: "I found the journal articles hard to follow, honestly." },
          { speaker: "WOMAN", text: "Start with the review article by Marsh and Kowalski — it summarises the whole field, then cites the studies behind each claim. Read that first and the individual papers will make sense." },
          { speaker: "WOMAN", text: "Second issue: your referencing. Several in-text citations don't appear in the bibliography, and two quotes have no page numbers." },
          { speaker: "MAN", text: "I used an app for that. Clearly not perfectly." },
          { speaker: "WOMAN", text: "The apps are ninety per cent right; the ten per cent they get wrong will cost you marks. Check every entry against the style guide yourself." },
          { speaker: "MAN", text: "Understood. If I fix the sources and the referencing, what grade could that reach?" },
          { speaker: "WOMAN", text: "It's a solid sixty-two now. With proper triangulation and clean references, a sixty-eight, maybe a seventy. Resubmit by the twelfth — I'll count it as your first draft, not a rewrite penalty." },
          { speaker: "MAN", text: "That's generous. I'll start with the review article tonight. Thank you." },
        ],
      },
      {
        part: 4, title: "Green roofs",
        context: "University lecture",
        estimatedSec: 320,
        script: [
          { speaker: "NARRATOR", text: "You will hear part of a lecture on green roofs. First, you have some time to look at questions 31 to 40." },
          { speaker: "WOMAN", text: "Today I want to persuade you that the roof of an ordinary building is wasted space — and that covering it with plants is one of the cheapest climate adaptations a city can buy." },
          { speaker: "WOMAN", text: "Green roofs are not new. The hanging gardens of ancient Babylon were essentially deep green roofs, and turf roofs have insulated Scandinavian farmhouses for centuries. What is new is the engineering. A modern green roof is a layered sandwich: a waterproof membrane, a root barrier, drainage, a lightweight growing medium, and finally the plants — usually sedums, tough succulents that survive drought." },
          { speaker: "WOMAN", text: "The benefits start with water. In a heavy storm, a green roof absorbs between fifty and eighty per cent of the rainfall that lands on it, releasing the rest slowly. For a city's drains, that means fewer flash floods. Then there's temperature: the plants cool the roof surface by up to thirty degrees on a summer day, cutting the building's cooling load, and reducing the urban heat island across whole districts if adopted widely." },
          { speaker: "WOMAN", text: "There are quieter benefits too. Green roofs roughly double the life of the waterproof membrane by shielding it from ultraviolet light. They provide habitat for insects and birds in the middle of concrete. Studies in hospitals suggest patients with a green roof view recover faster — though I should note those studies are small and need replication." },
          { speaker: "WOMAN", text: "So why doesn't every flat roof go green? Cost, mostly — installation runs roughly twice the price of a conventional roof — plus structural doubts. Not every building can carry the extra weight, especially when the growing medium is wet. But mandates are spreading; several European capitals now require green roofs or solar panels on new flat-roofed buildings, and early evidence says the flood savings alone repay the difference within a decade. Keep those numbers in mind; they'll anchor next week's problem set." },
        ],
      },
    ],
    groups: [
      {
        id: "l-g1", part: 1, type: "form-completion",
        heading: "Questions 1-6",
        instruction: "Complete the form below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["LOST PROPERTY REPORT", ""],
          rows: [
            ["Item: dark green", { gap: "l1" }, "with a badge"],
            ["Contents: clothes, laptop charger, a novel and a", { gap: "l2" }],
            ["Bag handed in at Bristol coach station at", { gap: "l3" }],
            ["Passport must be collected in person with", { gap: "l4" }],
            ["Storage free for the first", { gap: "l5" }, "days"],
            ["Courier fee:", { gap: "l6" }, "pounds fifty"],
          ],
        },
        questions: [
          { id: "l1", number: 1, answer: ["rucksack"], answerDisplay: "rucksack" },
          { id: "l2", number: 2, answer: ["passport"], answerDisplay: "passport" },
          { id: "l3", number: 3, answer: ["12:40", "12.40", "twelve forty"], answerDisplay: "12:40" },
          { id: "l4", number: 4, answer: ["photo id", "photo identity"], answerDisplay: "photo ID" },
          { id: "l5", number: 5, answer: ["seven", "7"], answerDisplay: "seven" },
          { id: "l6", number: 6, answer: ["six", "6"], answerDisplay: "six" },
        ],
      },
      {
        id: "l-g2", part: 1, type: "mcq",
        heading: "Questions 7-10",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l7", number: 7, text: "When did the man travel?", options: [ { label: "A", text: "Yesterday at 10:15." }, { label: "B", text: "This morning at 10:15." }, { label: "C", text: "Yesterday at 12:40." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l8", number: 8, text: "Why can't the passport be posted?", options: [ { label: "A", text: "It is too valuable." }, { label: "B", text: "Company policy forbids posting identity documents." }, { label: "C", text: "The man forgot the address." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l9", number: 9, text: "When will the man collect the passport?", options: [ { label: "A", text: "Friday morning." }, { label: "B", text: "Saturday morning." }, { label: "C", text: "Saturday afternoon." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l10", number: 10, text: "What is the reference number?", options: [ { label: "A", text: "LP-429." }, { label: "B", text: "LP-492." }, { label: "C", text: "LP-249." } ], answer: ["A"], answerDisplay: "A" },
        ],
      },
      {
        id: "l-g3", part: 2, type: "mcq",
        heading: "Questions 11-15",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l11", number: 11, text: "This year the festival is running for the", options: [ { label: "A", text: "ninth time." }, { label: "B", text: "fifth time." }, { label: "C", text: "nineteenth time." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l12", number: 12, text: "Free parking is available", options: [ { label: "A", text: "in the market square." }, { label: "B", text: "in the college field." }, { label: "C", text: "at the station." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l13", number: 13, text: "Admission this year is", options: [ { label: "A", text: "£1 for children." }, { label: "B", text: "free for everyone." }, { label: "C", text: "£5, with under-tens free." } ], answer: ["C"], answerDisplay: "C" },
          { id: "l14", number: 14, text: "International food stalls are found in", options: [ { label: "A", text: "Zone A by the church." }, { label: "B", text: "Zone B along the river." }, { label: "C", text: "Zone C in the college grounds." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l15", number: 15, text: "What happens at half past eight?", options: [ { label: "A", text: "The bread contest." }, { label: "B", text: "The chili challenge." }, { label: "C", text: "The fireworks." } ], answer: ["C"], answerDisplay: "C" },
        ],
      },
      {
        id: "l-g4", part: 2, type: "note-completion",
        heading: "Questions 16-20",
        instruction: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["MARSHFIELD FOOD FESTIVAL", ""],
          rows: [
            ["Number of stalls this year:", { gap: "l16" }],
            ["Cookery demonstrations run hourly from 11 until", { gap: "l17" }],
            ["Bread-baking contest judged by the", { gap: "l18" }],
            ["Chili-eating challenge starts at", { gap: "l19" }, "o'clock"],
            ["Proceeds go to the town's", { gap: "l20" }, "bank"],
          ],
        },
        questions: [
          { id: "l16", number: 16, answer: ["62", "sixty-two", "sixty two"], answerDisplay: "62" },
          { id: "l17", number: 17, answer: ["five", "5"], answerDisplay: "five" },
          { id: "l18", number: 18, answer: ["mayor"], answerDisplay: "mayor" },
          { id: "l19", number: 19, answer: ["three", "3"], answerDisplay: "three" },
          { id: "l20", number: 20, answer: ["food"], answerDisplay: "food" },
        ],
      },
      {
        id: "l-g5", part: 3, type: "mcq",
        heading: "Questions 21-24",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l21", number: 21, text: "What does the tutor praise first?", options: [ { label: "A", text: "The essay's structure." }, { label: "B", text: "The referencing." }, { label: "C", text: "The survey data." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l22", number: 22, text: "What is the main research problem?", options: [ { label: "A", text: "Too many sources." }, { label: "B", text: "Reliance on a single source." }, { label: "C", text: "No case study." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l23", number: 23, text: "What does the tutor recommend reading first?", options: [ { label: "A", text: "The style guide." }, { label: "B", text: "The review article by Marsh and Kowalski." }, { label: "C", text: "The industry report." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l24", number: 24, text: "What is said about referencing apps?", options: [ { label: "A", text: "They are always accurate." }, { label: "B", text: "They are about 90% correct." }, { label: "C", text: "They are banned." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
      {
        id: "l-g6", part: 3, type: "form-completion",
        heading: "Questions 25-30",
        instruction: "Complete the table below. Write NO MORE THAN TWO WORDS for each answer.",
        wordLimit: "NO MORE THAN TWO WORDS",
        table: {
          headers: ["ESSAY FEEDBACK", ""],
          rows: [
            ["Current grade:", { gap: "l25" }],
            ["Possible grade after revision:", { gap: "l26" }],
            ["Missing from bibliography: two quotes have no", { gap: "l27" }],
            ["Case study topic: sports", { gap: "l28" }, "brands"],
            ["Resubmission deadline: the", { gap: "l29" }, "of the month"],
            ["Resubmission counted as the first", { gap: "l30" }, "not a rewrite"],
          ],
        },
        questions: [
          { id: "l25", number: 25, answer: ["sixty-two", "62"], answerDisplay: "sixty-two" },
          { id: "l26", number: 26, answer: ["sixty-eight to seventy", "68-70", "sixty-eight or seventy"], answerDisplay: "sixty-eight to seventy" },
          { id: "l27", number: 27, answer: ["page numbers"], answerDisplay: "page numbers" },
          { id: "l28", number: 28, answer: ["shoe"], answerDisplay: "shoe" },
          { id: "l29", number: 29, answer: ["twelfth", "12th"], answerDisplay: "twelfth" },
          { id: "l30", number: 30, answer: ["draft"], answerDisplay: "draft" },
        ],
      },
      {
        id: "l-g7", part: 4, type: "note-completion",
        heading: "Questions 31-35",
        instruction: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["GREEN ROOFS — THE LAYERED SANDWICH", ""],
          rows: [
            ["Layer 1: waterproof", { gap: "l31" }],
            ["Layer 2: root", { gap: "l32" }],
            ["Layer 3:", { gap: "l33" }],
            ["Layer 4: lightweight growing", { gap: "l34" }],
            ["Plants usually sedums — tough", { gap: "l35" }],
          ],
        },
        questions: [
          { id: "l31", number: 31, answer: ["membrane"], answerDisplay: "membrane" },
          { id: "l32", number: 32, answer: ["barrier"], answerDisplay: "barrier" },
          { id: "l33", number: 33, answer: ["drainage"], answerDisplay: "drainage" },
          { id: "l34", number: 34, answer: ["medium"], answerDisplay: "medium" },
          { id: "l35", number: 35, answer: ["succulents"], answerDisplay: "succulents" },
        ],
      },
      {
        id: "l-g8", part: 4, type: "mcq",
        heading: "Questions 36-40",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l36", number: 36, text: "In a heavy storm, a green roof absorbs roughly", options: [ { label: "A", text: "15-30% of rainfall." }, { label: "B", text: "50-80% of rainfall." }, { label: "C", text: "all rainfall." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l37", number: 37, text: "On a summer day, plants can cool the roof surface by up to", options: [ { label: "A", text: "3 degrees." }, { label: "B", text: "13 degrees." }, { label: "C", text: "30 degrees." } ], answer: ["C"], answerDisplay: "C" },
          { id: "l38", number: 38, text: "Green roofs extend membrane life by protecting it from", options: [ { label: "A", text: "ultraviolet light." }, { label: "B", text: "rain." }, { label: "C", text: "birds." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l39", number: 39, text: "What does the lecturer say about the hospital studies?", options: [ { label: "A", text: "They are conclusive." }, { label: "B", text: "They are small and need replication." }, { label: "C", text: "They were retracted." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l40", number: 40, text: "Installation costs about", options: [ { label: "A", text: "half the price of a conventional roof." }, { label: "B", text: "the same as a conventional roof." }, { label: "C", text: "twice the price of a conventional roof." } ], answer: ["C"], answerDisplay: "C" },
        ],
      },
    ],
  },

  writing: {
    minutes: 60,
    tasks: [
      {
        id: "w1", taskNumber: 1, suggestedMinutes: 20, minimumWords: 150,
        prompt: "The pie charts below show how energy was produced in one country in 1990 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
        chart: {
          type: "pie", title: "Energy production by source", unit: "% of total",
          categories: ["Coal", "Gas", "Nuclear", "Renewables"],
          series: [{ name: "1990", values: [45, 30, 20, 5] }],
        },
        sampleAnswer: "The pie charts compare the relative contributions of four energy sources — coal, gas, nuclear and renewables — in a single country in 1990 and 2020. Overall, the energy mix shifted from a coal-dominated pattern toward a much more balanced one, with renewables replacing a large share of coal. In 1990, coal was the backbone of the system, supplying 45 per cent of all energy, followed by gas at 30 per cent and nuclear at 20 per cent; renewables contributed a marginal 5 per cent. Thirty years later the picture had changed considerably. Coal's share had fallen to 25 per cent, and gas had overtaken it as the leading source at 35 per cent. Nuclear remained almost unchanged at 18 per cent, while renewables expanded more than fivefold to 22 per cent, becoming the third-largest source. Taken together, fossil fuels still provided 60 per cent of production in 2020, only fifteen points below their 1990 share, so while the transition is clearly under way, the country remained majority-dependent on coal and gas.",
        checklist: [
          "مقدمه دو سال را مقایسه می‌کند؟",
          "Overview تغییر کلی (تعادل بیشتر و رشد تجدیدپذیرها) را می‌گوید؟",
          "اعداد کلیدی هر دو سال گزارش شده؟",
          "مقایسهٔ فسیلی در مجموع انجام شده؟",
          "حداقل ۱۵۰ کلمه؟",
        ],
      },
      {
        id: "w2", taskNumber: 2, suggestedMinutes: 40, minimumWords: 250,
        prompt: "More and more people are working from home rather than commuting to an office. Do the advantages of this development outweigh the disadvantages?",
        sampleAnswer: "The rise of remote work is among the most visible legacies of recent technological change, and opinions about it remain divided. While working from home brings real costs — to collaboration, to junior staff and arguably to city economies — I believe its advantages for individuals and the environment outweigh those costs. The strongest objections concern the social fabric of work. Offices do not merely host tasks; they host the informal conversations through which trust, mentoring and culture are built. New employees suffer most: learning by observation is difficult over a video call. There is also evidence that isolation harms some workers' mental health, and that home environments — a shared flat, a small apartment, caring duties — make 'home' a far from equal workplace for everyone. On the other hand, the benefits are substantial and widely shared. Commuting, for many the least pleasant hour of the day, disappears, and the time is usually reallocated to family, exercise or work itself. Productivity studies so far find no general collapse; indeed, focused individual tasks are often completed faster at home. Companies save on property, and talented people outside major cities — carers, disabled workers, residents of cheaper regions — gain access to jobs previously closed to them. The environmental case, while debated, is hard to dismiss at scale: fewer commutes means less congestion and lower transport emissions. Crucially, most of the disadvantages are solvable by design, whereas the advantages compound with time. Hybrid schedules recover the mentoring and social functions of offices without restoring the full commute; deliberate onboarding programmes and occasional in-person gatherings address the junior-staff problem. The isolation effect, too, eases as norms and neighbourhood co-working spaces develop. In conclusion, remote work trades an old set of advantages for a new one, and on balance the trade favours the worker and the climate. The sensible response is not to reverse it but to manage it — through hybrid patterns, intentional culture-building and a right to disconnect — so that its costs are engineered away while its benefits are kept.",
        checklist: [
          "آیا سوال دقیقاً پاسخ داده شده (بزرگ‌تر بودن مزایا)؟",
          "معایب واقعاً بررسی و رد نشده‌اند؟",
          "راه‌حل معایب (hybrid) ارائه شده؟",
          "پاراگراف‌بندی منطقی است؟",
          "حداقل ۲۵۰ کلمه؟",
        ],
      },
    ],
  },
};
