import type { IeltsTest } from "@/types/ielts";

// ========================================
// کتاب کمبریج ۰۷ — تست ۱ آکادمیک (محتوای تمرینی اختصاصی Flex English)
// ========================================

export const book07: IeltsTest = {
  slug: "cambridge-07",
  bookNumber: 7,
  testNumber: 1,
  module: "ACADEMIC",
  titleFa: "کمبریج ۰۷ — تست ۱",
  titleEn: "Cambridge 07 — Test 1",
  available: true,

  reading: {
    minutes: 60,
    passages: [
      {
        part: 1,
        title: "Music and the Brain",
        intro: "Why a melody can do what nothing else can",
        paragraphs: [
          { label: "A", text: "Neuroscience has a soft spot for music, because nothing else recruits so much of the brain at once. Listening to a favourite song lights up regions for hearing, movement, memory, language and emotion together — a full-brain workout triggered from outside. This sheer breadth explains both why music is so powerful and why it resists simple explanation." },
          { label: "B", text: "The emotional effect is the most striking. Music that moves a listener triggers the same reward circuitry as food and money, releasing dopamine in anticipation of a musical peak — the moment a chorus returns, a tension resolves. Intriguingly, the brain predicts music as it unfolds, and pleasure comes precisely from patterns that both meet and stretch expectation: too predictable is boring, too novel is noise. Great composers, on this view, are intuitive statisticians playing with probability." },
          { label: "C", text: "Music's hold on memory is clinically remarkable. Patients with advanced Alzheimer's, unable to recognise their own children, can sing every word of songs from their youth, and music therapy increasingly uses this island of preserved memory to reach people that conversation cannot. The effect has limits — it usually does not restore general memory — but as a channel of connection, an old song outperforms almost any drug." },
          { label: "D", text: "The famous 'Mozart effect' — the claim that listening to Mozart temporarily raises intelligence — has not survived replication, and researchers now treat it as a case study in scientific correction. What does survive is more modest but sturdier: children who learn to play an instrument show small but persistent advantages in auditory processing, attention and reading, and adults who practise show measurable brain plasticity even late in life. Learning music seems to be the beneficial part, not listening to it." },
          { label: "E", text: "Why humans evolved music at all remains contested. Darwin thought it courtship; others argue group bonding — singing and dancing synchronise bodies and feelings, forging the trust that large cooperative groups require. The two theories share an assumption worth noticing: that music is not decoration. In every known culture it accompanies the events that matter most — birth, marriage, war, worship, mourning — which suggests that whatever its origin, humanity has never treated it as optional." },
        ],
      },
      {
        part: 2,
        title: "When Land Turns to Dust",
        intro: "Desertification and the fight to reverse it",
        paragraphs: [
          { label: "A", text: "Every year, the United Nations estimates, an area of productive land roughly the size of a small country degrades into dust. Desertification — the drying and dying of land in dry regions — threatens the food supply of hundreds of millions of people, and it is usually described as spreading deserts swallowing farms. The image is vivid, but the process is stranger: most desertification is caused not by advancing sand but by the loss of the living crust of soil, and it happens under our feet long before it appears on the horizon." },
          { label: "B", text: "The drivers combine climate and misuse. Droughts arrive more often and last longer, but the damage is done by what people and livestock do during and after them: overgrazing that strips protective grass, deep ploughing that exposes soil to wind, the cutting of trees whose roots held the land together, and irrigation that salts the earth. Once the thin top layer blows away, recovery can take centuries." },
          { label: "C", text: "China's experience illustrates both failure and turnaround. By the late 1990s, dust storms from degraded northern lands were shutting schools in Beijing every spring. The response — the Great Green Wall programme — has planted millions of trees in a belt across the north, and although early plantings of water-hungry species in arid zones often died, the programme has learned. Current mixes favour native shrubs, grasses and grazing bans, and satellite imagery now shows large areas of northern China greener than twenty years ago." },
          { label: "D", text: "Africa's most celebrated case works from the ground up rather than the top down. Across the Sahel, farmers have regenerated trees on farmland simply by changing what happens to stumps: instead of clearing young shoots each season, they protect them and prune them into a canopy. The regrown trees shade crops, fix nitrogen, drop leaf litter and yield fruit and firewood. What became known as farmer-managed natural regeneration spread farmer to farmer, covering millions of hectares at almost no cost — no nurseries, no planting, no external funding loop." },
          { label: "E", text: "The lesson both cases teach is that desertification is cheaper to prevent than to cure, and that the decisive variable is who owns the outcome. Where local people control land and trees, they restore them; where trees belong to the state and grazing land to everyone, each user gains by extracting before a neighbour does. Reversing dust, it turns out, is less a technical problem — the techniques are known and simple — than an institutional one of aligning care with control." },
        ],
      },
      {
        part: 3,
        title: "Can Animals Talk?",
        intro: "What a half-century of language experiments really showed",
        paragraphs: [
          { text: "In the 1970s, researchers raised a chimpanzee named Washoe in a house, taught her signs, and reported that she had learned over a hundred words and even combined them. Newspapers asked whether the boundary between human and animal had fallen. Fifty years later, the answer the experiments produced is subtler and, in its way, more interesting: a firm no to animal language as we have it, and a yes to almost everything around it." },
          { text: "The apes did acquire vocabularies of signs and, occasionally, useful combinations. But close analysis of filmed sessions showed that most signing was either imitation of a human who had just signed, or requests for things present in the room. The signature human pattern — using symbols to discuss the absent, the possible, the past and the future — appeared rarely, if at all. Grammar, too, stayed absent: sign order never carried consistent meaning, as it does even for young children." },
          { text: "Dolphins and parrots went further in some respects. A grey parrot trained over three decades could label objects, colours, shapes and numbers, and answered novel questions correctly. But his achievements, impressive as they were, remained a learned mapping between categories and sounds — a remarkable cognitive tool, not a conversation about anything beyond the immediate." },
          { text: "The decisive twist came from a species nobody expected: not a primate or a parrot, but the honeybee. Returning foragers communicate the direction and distance of food by dancing, and experimental analysis confirmed that other bees actually use the information. Here was symbolic communication about something distant in space — exactly the displacement that the apes had lacked — performed by an animal with a brain the size of a grass seed. The finding reframed the entire field: the interesting question stopped being 'can animals learn our language?' and became 'what communication has each species evolved for its own world?'" },
          { text: "That reframed question has been productive. Prairie dogs, it turns out, encode the size, shape and colour of approaching predators in their alarm calls; elephants communicate in low frequencies below our hearing across kilometres; whales learn songs from one another. None of this is language, and the honest conclusion of the great experiments is that language, with its open-ended grammar and displacement, appears to be genuinely ours. What the same experiments proved beyond the apes and bees is that the gap, while real, is not a void: the building blocks — symbols, reference, learning, even displacement — are scattered widely across the animal kingdom, assembled fully in only one species." },
        ],
      },
    ],
    groups: [
      {
        id: "r-g1", part: 1, type: "match-info",
        heading: "Questions 1-5",
        instruction: "The reading passage has five paragraphs, A-E. Which paragraph contains the following information?",
        options: [ { label: "A", text: "A" }, { label: "B", text: "B" }, { label: "C", text: "C" }, { label: "D", text: "D" }, { label: "E", text: "E" } ],
        questions: [
          { id: "r1", number: 1, text: "why music engages almost the whole brain", answer: ["A"], answerDisplay: "A" },
          { id: "r2", number: 2, text: "the failure of a famous claim about intelligence", answer: ["D"], answerDisplay: "D" },
          { id: "r3", number: 3, text: "how expectation shapes musical pleasure", answer: ["B"], answerDisplay: "B" },
          { id: "r4", number: 4, text: "music's power over memory in dementia patients", answer: ["C"], answerDisplay: "C" },
          { id: "r5", number: 5, text: "two competing theories of music's evolutionary origin", answer: ["E"], answerDisplay: "E" },
        ],
      },
      {
        id: "r-g2", part: 1, type: "sentence-completion",
        heading: "Questions 6-9",
        instruction: "Complete the sentences below. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
        wordLimit: "NO MORE THAN TWO WORDS",
        questions: [
          { id: "r6", number: 6, before: "Musical pleasure triggers the same", after: "as food and money.", answer: ["reward circuitry"], answerDisplay: "reward circuitry" },
          { id: "r7", number: 7, before: "The brain releases dopamine in anticipation of a", after: ".", answer: ["musical peak"], answerDisplay: "musical peak" },
          { id: "r8", number: 8, before: "The lasting benefits of music come from learning to", after: "an instrument.", answer: ["play"], answerDisplay: "play" },
          { id: "r9", number: 9, before: "Darwin believed music evolved for", after: ".", answer: ["courtship"], answerDisplay: "courtship" },
        ],
      },
      {
        id: "r-g3", part: 1, type: "mcq",
        heading: "Questions 10-13",
        instruction: "Choose the correct letter, A, B, C or D.",
        questions: [
          { id: "r10", number: 10, text: "What does the passage say great composers are, in effect?", options: [ { label: "A", text: "Mathematicians." }, { label: "B", text: "Intuitive statisticians playing with probability." }, { label: "C", text: "Psychologists." }, { label: "D", text: "Storytellers." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r11", number: 11, text: "What is the limitation of music therapy in Alzheimer's?", options: [ { label: "A", text: "It works only for young patients." }, { label: "B", text: "It usually does not restore general memory." }, { label: "C", text: "It requires drugs." }, { label: "D", text: "It needs special songs." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r12", number: 12, text: "What did the 'Mozart effect' become for researchers?", options: [ { label: "A", text: "A confirmed law." }, { label: "B", text: "A case study in scientific correction." }, { label: "C", text: "A banned topic." }, { label: "D", text: "A marketing tool only." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r13", number: 13, text: "What do the two theories of music's origin share?", options: [ { label: "A", text: "Music is decoration." }, { label: "B", text: "Music is optional." }, { label: "C", text: "Music is not decoration." }, { label: "D", text: "Music evolved last year." } ], answer: ["C"], answerDisplay: "C" },
        ],
      },
      {
        id: "r-g4", part: 2, type: "match-headings",
        heading: "Questions 14-18",
        instruction: "The reading passage has five paragraphs, A-E. Choose the correct heading for each paragraph from the list of headings below.",
        options: [
          { label: "i", text: "Not sand, but dying soil" },
          { label: "ii", text: "A top-down wall of trees that learned" },
          { label: "iii", text: "Restoration from the stump up" },
          { label: "iv", text: "Drought plus misuse: the human hand" },
          { label: "v", text: "Ownership decides whether land heals" },
          { label: "vi", text: "A problem the size of a country" },
        ],
        questions: [
          { id: "r14", number: 14, text: "Paragraph A", answer: ["i"], answerDisplay: "i" },
          { id: "r15", number: 15, text: "Paragraph B", answer: ["iv"], answerDisplay: "iv" },
          { id: "r16", number: 16, text: "Paragraph C", answer: ["ii"], answerDisplay: "ii" },
          { id: "r17", number: 17, text: "Paragraph D", answer: ["iii"], answerDisplay: "iii" },
          { id: "r18", number: 18, text: "Paragraph E", answer: ["v"], answerDisplay: "v" },
        ],
      },
      {
        id: "r-g5", part: 2, type: "tfng",
        heading: "Questions 19-23",
        instruction: "Do the following statements agree with the information given in the reading passage? Write TRUE, FALSE or NOT GIVEN.",
        options: [ { label: "TRUE", text: "TRUE" }, { label: "FALSE", text: "FALSE" }, { label: "NOT GIVEN", text: "NOT GIVEN" } ],
        questions: [
          { id: "r19", number: 19, text: "Most desertification is caused by sand dunes moving over farmland.", answer: ["FALSE"], answerDisplay: "FALSE" },
          { id: "r20", number: 20, text: "The first tree species planted in China's green belt all thrived.", answer: ["FALSE"], answerDisplay: "FALSE" },
          { id: "r21", number: 21, text: "Satellite images show large parts of northern China are greener than before.", answer: ["TRUE"], answerDisplay: "TRUE" },
          { id: "r22", number: 22, text: "Farmer-managed natural regeneration requires external funding.", answer: ["FALSE"], answerDisplay: "FALSE" },
          { id: "r23", number: 23, text: "The Sahel technique has now spread to Australia.", answer: ["NOT GIVEN"], answerDisplay: "NOT GIVEN" },
        ],
      },
      {
        id: "r-g6", part: 2, type: "note-completion",
        heading: "Questions 24-26",
        instruction: "Complete the notes below. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
        wordLimit: "NO MORE THAN TWO WORDS",
        table: {
          headers: ["FIGHTING DESERTIFICATION", ""],
          rows: [
            ["Regrown trees on Sahel farms shade crops, fix nitrogen and yield fruit and", { gap: "r24" }],
            ["Once the thin", { gap: "r25" }, "blows away, recovery takes centuries"],
            ["The decisive variable in restoring land is who", { gap: "r26" }, "the outcome"],
          ],
        },
        questions: [
          { id: "r24", number: 24, answer: ["firewood", "wood"], answerDisplay: "firewood" },
          { id: "r25", number: 25, answer: ["top layer", "topsoil", "soil layer"], answerDisplay: "top layer / topsoil" },
          { id: "r26", number: 26, answer: ["owns", "controls"], answerDisplay: "owns / controls" },
        ],
      },
      {
        id: "r-g7", part: 3, type: "mcq",
        heading: "Questions 27-31",
        instruction: "Choose the correct letter, A, B, C or D.",
        questions: [
          { id: "r27", number: 27, text: "What did analysis of the apes' signing reveal?", options: [ { label: "A", text: "Complex grammar." }, { label: "B", text: "Mostly imitation and requests for present things." }, { label: "C", text: "Fluent conversation." }, { label: "D", text: "Nothing at all." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r28", number: 28, text: "What is 'displacement' in language?", options: [ { label: "A", text: "Discussing the absent, possible, past and future." }, { label: "B", text: "Moving house." }, { label: "C", text: "Signing slowly." }, { label: "D", text: "Loud calls." } ], answer: ["A"], answerDisplay: "A" },
          { id: "r29", number: 29, text: "What could the grey parrot do?", options: [ { label: "A", text: "Hold conversations." }, { label: "B", text: "Label objects, colours, shapes and numbers." }, { label: "C", text: "Sing songs." }, { label: "D", text: "Teach other parrots." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r30", number: 30, text: "Why was the honeybee finding a twist?", options: [ { label: "A", text: "Bees are large." }, { label: "B", text: "A tiny-brained animal communicated about distant food — the displacement apes lacked." }, { label: "C", text: "Bees cannot learn." }, { label: "D", text: "Dancing is not communication." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r31", number: 31, text: "What is the honest conclusion of the experiments?", options: [ { label: "A", text: "Animals have hidden grammar." }, { label: "B", text: "Language is genuinely unique to humans, but its building blocks are widespread." }, { label: "C", text: "All animals can talk." }, { label: "D", text: "Nothing is unique to humans." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
      {
        id: "r-g8", part: 3, type: "match-features",
        heading: "Questions 32-36",
        instruction: "Look at the following findings (Questions 32-36) and the list of species below. Match each finding with the species. You may use any letter more than once.",
        options: [
          { label: "Chimpanzees", text: "Chimpanzees" },
          { label: "Grey parrot", text: "Grey parrot" },
          { label: "Honeybee", text: "Honeybee" },
          { label: "Prairie dogs", text: "Prairie dogs" },
        ],
        questions: [
          { id: "r32", number: 32, text: "Communicates the direction and distance of distant food.", answer: ["Honeybee"], answerDisplay: "Honeybee" },
          { id: "r33", number: 33, text: "Alarm calls encode size, shape and colour of predators.", answer: ["Prairie dogs"], answerDisplay: "Prairie dogs" },
          { id: "r34", number: 34, text: "Learned over a hundred signs but rarely discussed the absent.", answer: ["Chimpanzees"], answerDisplay: "Chimpanzees" },
          { id: "r35", number: 35, text: "Answered novel questions about objects correctly after decades of training.", answer: ["Grey parrot"], answerDisplay: "Grey parrot" },
          { id: "r36", number: 36, text: "Sign order never carried consistent meaning.", answer: ["Chimpanzees"], answerDisplay: "Chimpanzees" },
        ],
      },
      {
        id: "r-g9", part: 3, type: "summary-completion",
        heading: "Questions 37-40",
        instruction: "Complete the summary below. Choose ONE WORD ONLY from the passage for each answer.",
        wordLimit: "ONE WORD ONLY",
        lines: [
          "The language experiments produced a subtler picture than headlines suggested. The apes acquired vocabularies but lacked grammar and",
          { gap: "r37" },
          ". A grey parrot mastered an impressive mapping between categories and",
          { gap: "r38" },
          ", though only about the immediate present. The honeybee's dance — communication about something distant — supplied the missing",
          { gap: "r39" },
          "and reframed the field. The final verdict: language itself appears unique to one",
          { gap: "r40" },
          ", while its building blocks are scattered widely.",
        ],
        questions: [
          { id: "r37", number: 37, before: "grammar and", after: "", answer: ["displacement"], answerDisplay: "displacement" },
          { id: "r38", number: 38, before: "categories and", after: "", answer: ["sounds"], answerDisplay: "sounds" },
          { id: "r39", number: 39, before: "supplied the missing", after: "and reframed", answer: ["displacement"], answerDisplay: "displacement" },
          { id: "r40", number: 40, before: "unique to one", after: "", answer: ["species"], answerDisplay: "species" },
        ],
      },
    ],
  },

  listening: {
    minutes: 30,
    sections: [
      {
        part: 1, title: "Reserving a restaurant table", context: "Phone call to a restaurant", estimatedSec: 260,
        script: [
          { speaker: "MAN", text: "Good evening, The Old Mill restaurant, how may I help you?" },
          { speaker: "WOMAN", text: "Hello. I'd like to book a table for Saturday night — it's my parents' anniversary, eight of us altogether." },
          { speaker: "MAN", text: "Congratulations to them! Saturday... what time were you thinking? We seat at 6, 7:30 and 9." },
          { speaker: "WOMAN", text: "7:30 suits everyone. Is there anything quiet? Dad hates noise." },
          { speaker: "MAN", text: "The conservatory at the back is our quietest area — garden view, and tables can be arranged in a long line for groups." },
          { speaker: "WOMAN", text: "The conservatory sounds perfect. Can we bring a cake?" },
          { speaker: "MAN", text: "Of course — there's no charge for cutting and serving, and we'll keep it in the fridge until dessert." },
          { speaker: "WOMAN", text: "Wonderful. Two of the group are vegetarian, one is vegan — is that workable?" },
          { speaker: "MAN", text: "Our menu always has two vegetarian mains; the chef can adapt one to vegan if we know in advance. I'll note it now." },
          { speaker: "WOMAN", text: "Also — my mother uses a wheelchair. Will the conservatory be accessible?" },
          { speaker: "MAN", text: "Fully — ramp from the car park and no steps inside. If you park in bay one, it's the shortest route." },
          { speaker: "WOMAN", text: "Great. Do you have a set menu for groups?" },
          { speaker: "MAN", text: "For eight or more: three courses at 32 pounds per person, or order from the full menu. The set menu is easier for the kitchen on busy nights." },
          { speaker: "WOMAN", text: "Let's do the set menu. Can we see the choices in advance?" },
          { speaker: "MAN", text: "I'll email tonight's set menu — it changes monthly, Saturday's will be similar. A deposit of five pounds a head secures the table." },
          { speaker: "WOMAN", text: "Fine, card deposit for eight. Name's Fiona Marsh." },
          { speaker: "MAN", text: "Booked: Marsh, party of eight, conservatory, Saturday 7:30, set menu, two vegetarian one vegan. We'll take good care of them." },
        ],
      },
      {
        part: 2, title: "University accommodation options",
        context: "Talk to new students",
        estimatedSec: 300,
        script: [
          { speaker: "NARRATOR", text: "You will hear an accommodation officer explaining options to new students." },
          { speaker: "WOMAN", text: "Welcome, and congratulations on your places. In the next ten minutes I'll walk you through where you could be living this year, because the choices matter more than students expect." },
          { speaker: "WOMAN", text: "Option one: halls of residence. All first-years are guaranteed a room if they apply by the end of August. Halls are catered — that means two meals a day, breakfast and dinner — and everything is included in the fee: internet, cleaning of shared areas, and a bus pass. The social life is legendary and the noise sometimes matches it. About 145 pounds a week." },
          { speaker: "WOMAN", text: "Option two: self-catered flats on campus — groups of five or six with a shared kitchen. Around 110 a week. You'll cook for yourself, which is cheaper if you're organised and expensive if your cooking is takeaway. Quieter than halls, still five minutes from lectures." },
          { speaker: "WOMAN", text: "Option three: private renting in town. The market here is tight, so we recommend the university-verified list only — every landlord on it is checked. Typical shared house: 85 to 95 a week plus bills, so budget realistically. Never pay a holding deposit in cash, and read the inventory before you sign anything." },
          { speaker: "WOMAN", text: "Whatever you choose, apply through the portal this week. And one warning I give every year: the cheapest room is not always the cheapest choice. A long bus ride costs money and time, and the friends you make in first-term accommodation tend to be the friends you keep. Choose where you'll be happy, not just where it's cheap." },
        ],
      },
      {
        part: 3, title: "Preparing a presentation on urban wildlife",
        context: "Two students prepare a talk",
        estimatedSec: 300,
        script: [
          { speaker: "NARRATOR", text: "You will hear two students preparing a presentation about wildlife in cities." },
          { speaker: "WOMAN", text: "So our topic is urban wildlife, ten minutes, next Friday. Where should we start?" },
          { speaker: "MAN", text: "With the fox, I think. Everyone recognises it — it's the perfect hook. Foxes now live in every British city, and city foxes live about half as long as country foxes." },
          { speaker: "WOMAN", text: "That's a memorable fact, but isn't it because of cars rather than food? City foxes actually eat well — bins, mostly." },
          { speaker: "MAN", text: "Right — road accidents are the main killer. Good contrast: plenty of food, deadly transport." },
          { speaker: "WOMAN", text: "Then peregrine falcons. They nest on tall buildings — the tower block is their cliff. Some pairs now raise more chicks in cities than on real cliffs, because pigeons are everywhere." },
          { speaker: "MAN", text: "Should we do a slide for each animal? Fox, falcon, and then?" },
          { speaker: "WOMAN", text: "Bees. Urban beekeeping is booming — but the twist is that wild bees, the solitary ones, may be suffering because honeybees out-compete them for flowers." },
          { speaker: "MAN", text: "Careful — I read that claim is contested. Some studies find no competition at all." },
          { speaker: "WOMAN", text: "Then we present both sides. Actually, that's a stronger slide: 'the honeybee debate'. What about the ending?" },
          { speaker: "MAN", text: "Green roofs and hedgehog highways — holes in fences. Small changes, real effects. Then the question for the audience: is the city a threat to wildlife or the newest habitat?" },
          { speaker: "WOMAN", text: "Perfect closer. I'll build the slides if you write the speaker notes — you write faster." },
          { speaker: "MAN", text: "Deal. Draft slides by Wednesday so I have two days with them?" },
          { speaker: "WOMAN", text: "Wednesday noon. And we'll rehearse in front of my flatmates Thursday — the falcon screech needs testing." },
        ],
      },
      {
        part: 4, title: "The history of glass",
        context: "University lecture",
        estimatedSec: 320,
        script: [
          { speaker: "NARRATOR", text: "You will hear part of a lecture on the history of glass. First, you have some time to look at questions 31 to 40." },
          { speaker: "MAN", text: "Glass is so ordinary that we forget it is one of the strangest materials we use — a solid that behaves like a frozen liquid, older than civilisation and younger than you think in its useful forms." },
          { speaker: "MAN", text: "Natural glass exists: obsidian, born in volcanoes, was chipped into sharper blades than any metal and traded across continents in the Stone Age. Human-made glass is around four and a half thousand years old, almost certainly discovered by accident — the story of sailors cooking on blocks of a soda cargo is charming but almost certainly false. Early glass was coloured by impurities, and clear glass was rare for two millennia." },
          { speaker: "MAN", text: "Two inventions unlocked everything. The blowpipe, about two thousand years ago in the Levant, let craftsmen inflate glass into vessels cheaply — glassware moved from royal treasure to household goods within a couple of centuries. Then flat glass: spinning molten glass into a disc, later replaced by pulling sheets from a tank, gave the world windows. Medieval cathedrals with their stained glass were, technologically, walls of luxury." },
          { speaker: "MAN", text: "The modern turning point was float glass, patented in 1952: molten glass poured onto a bath of liquid tin comes out perfectly flat and parallel, needing no grinding or polishing. Ninety per cent of flat glass today is made this way, and its cheapness is why glass towers, car windscreens and greenhouse food exist at all." },
          { speaker: "MAN", text: "The frontier now reverses the tradition of cheapness: optical fibre — glass thinner than hair — carries almost all human communication as pulses of light, and a single strand moves more data per second than the entire internet of 1990. From spearheads of volcanic glass to threads of it whispering under the oceans: the material keeps finding new things to be. Next lecture, we follow that thread literally — how fibre is drawn, and why the glass must be astonishingly pure." },
        ],
      },
    ],
    groups: [
      {
        id: "l-g1", part: 1, type: "form-completion",
        heading: "Questions 1-6",
        instruction: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["THE OLD MILL — BOOKING", ""],
          rows: [
            ["Occasion: parents'", { gap: "l1" }],
            ["Seating time:", { gap: "l2" }, "p.m."],
            ["Quietest area: the", { gap: "l3" }],
            ["Dietary: two vegetarians and one", { gap: "l4" }],
            ["Set menu price for groups of eight or more:", { gap: "l5" }, "pounds per person"],
            ["Deposit:", { gap: "l6" }, "pounds per head"],
          ],
        },
        questions: [
          { id: "l1", number: 1, answer: ["anniversary"], answerDisplay: "anniversary" },
          { id: "l2", number: 2, answer: ["7:30", "7.30", "seven thirty"], answerDisplay: "7:30" },
          { id: "l3", number: 3, answer: ["conservatory"], answerDisplay: "conservatory" },
          { id: "l4", number: 4, answer: ["vegan"], answerDisplay: "vegan" },
          { id: "l5", number: 5, answer: ["32", "thirty-two", "thirty two"], answerDisplay: "32" },
          { id: "l6", number: 6, answer: ["5", "five"], answerDisplay: "5" },
        ],
      },
      {
        id: "l-g2", part: 1, type: "mcq",
        heading: "Questions 7-10",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l7", number: 7, text: "What is the restaurant's cake policy?", options: [ { label: "A", text: "No outside food allowed." }, { label: "B", text: "Free cutting and serving, kept in the fridge." }, { label: "C", text: "A 10-pound fee." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l8", number: 8, text: "What parking advice is given?", options: [ { label: "A", text: "Bay one is closest for wheelchair access." }, { label: "B", text: "Street parking only." }, { label: "C", text: "Valet service." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l9", number: 9, text: "Why choose the set menu on busy nights?", options: [ { label: "A", text: "It is cheaper for the customer only." }, { label: "B", text: "It is easier for the kitchen." }, { label: "C", text: "It is compulsory." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l10", number: 10, text: "When will the woman receive the menu?", options: [ { label: "A", text: "Tonight's set menu by email." }, { label: "B", text: "Saturday at the table." }, { label: "C", text: "Never." } ], answer: ["A"], answerDisplay: "A" },
        ],
      },
      {
        id: "l-g3", part: 2, type: "mcq",
        heading: "Questions 11-14",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l11", number: 11, text: "What is guaranteed for first-years applying by the end of August?", options: [ { label: "A", text: "A room in halls." }, { label: "B", text: "A private house." }, { label: "C", text: "A bus pass only." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l12", number: 12, text: "What does the halls fee include?", options: [ { label: "A", text: "Two meals a day, internet, cleaning of shared areas, and a bus pass." }, { label: "B", text: "Nothing but rent." }, { label: "C", text: "Flights home." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l13", number: 13, text: "What is said about self-catered flats?", options: [ { label: "A", text: "They cost about 110 a week." }, { label: "B", text: "They include meals." }, { label: "C", text: "They are in the city centre." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l14", number: 14, text: "What warning is given about private renting?", options: [ { label: "A", text: "Never pay a holding deposit in cash, and check the inventory." }, { label: "B", text: "Avoid all landlords." }, { label: "C", text: "Bills are always included." } ], answer: ["A"], answerDisplay: "A" },
        ],
      },
      {
        id: "l-g4", part: 2, type: "note-completion",
        heading: "Questions 15-20",
        instruction: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["ACCOMMODATION AT A GLANCE", ""],
          rows: [
            ["Halls of residence: about", { gap: "l15" }, "pounds per week"],
            ["Self-catered campus flats: groups of five or six with a shared", { gap: "l16" }],
            ["Private shared house in town: 85-95 a week plus", { gap: "l17" }],
            ["Use only the university-", { gap: "l18" }, "landlord list"],
            ["Applications go through the", { gap: "l19" }, "this week"],
            ["Warning: a long bus ride costs money and", { gap: "l20" }],
          ],
        },
        questions: [
          { id: "l15", number: 15, answer: ["145", "one hundred and forty-five"], answerDisplay: "145" },
          { id: "l16", number: 16, answer: ["kitchen"], answerDisplay: "kitchen" },
          { id: "l17", number: 17, answer: ["bills"], answerDisplay: "bills" },
          { id: "l18", number: 18, answer: ["verified"], answerDisplay: "verified" },
          { id: "l19", number: 19, answer: ["portal"], answerDisplay: "portal" },
          { id: "l20", number: 20, answer: ["time"], answerDisplay: "time" },
        ],
      },
      {
        id: "l-g5", part: 3, type: "mcq",
        heading: "Questions 21-24",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l21", number: 21, text: "Why start the presentation with foxes?", options: [ { label: "A", text: "Everyone recognises them — a good hook." }, { label: "B", text: "They are the rarest animal." }, { label: "C", text: "The tutor requested it." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l22", number: 22, text: "Why do city foxes live shorter lives?", options: [ { label: "A", text: "Lack of food." }, { label: "B", text: "Road accidents mainly." }, { label: "C", text: "Disease only." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l23", number: 23, text: "What is said about peregrine falcons?", options: [ { label: "A", text: "Tower blocks act as cliffs, and pigeons provide food." }, { label: "B", text: "They avoid cities." }, { label: "C", text: "They nest on the ground." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l24", number: 24, text: "How do the students treat the honeybee claim?", options: [ { label: "A", text: "They drop it." }, { label: "B", text: "They present both sides as a debate slide." }, { label: "C", text: "They assert it as fact." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
      {
        id: "l-g6", part: 3, type: "form-completion",
        heading: "Questions 25-30",
        instruction: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["PRESENTATION PLAN", ""],
          rows: [
            ["Presentation length:", { gap: "l25" }, "minutes"],
            ["Final topics: fox, falcon,", { gap: "l26" }, "and hedgehog highways"],
            ["Closing question: is the city a threat or the newest", { gap: "l27" }, "?"],
            ["The woman builds the", { gap: "l28" }],
            ["The man writes the", { gap: "l29" }, "notes"],
            ["Draft slides ready by Wednesday", { gap: "l30" }],
          ],
        },
        questions: [
          { id: "l25", number: 25, answer: ["ten", "10"], answerDisplay: "ten" },
          { id: "l26", number: 26, answer: ["bees"], answerDisplay: "bees" },
          { id: "l27", number: 27, answer: ["habitat"], answerDisplay: "habitat" },
          { id: "l28", number: 28, answer: ["slides"], answerDisplay: "slides" },
          { id: "l29", number: 29, answer: ["speaker"], answerDisplay: "speaker" },
          { id: "l30", number: 30, answer: ["noon", "midday", "12"], answerDisplay: "noon" },
        ],
      },
      {
        id: "l-g7", part: 4, type: "note-completion",
        heading: "Questions 31-35",
        instruction: "Complete the notes below. Write ONE WORD ONLY for each answer.",
        wordLimit: "ONE WORD ONLY",
        table: {
          headers: ["THE HISTORY OF GLASS", ""],
          rows: [
            ["Natural glass from volcanoes is called", { gap: "l31" }],
            ["Early human-made glass was coloured by", { gap: "l32" }],
            ["Invention from the Levant, about 2000 years ago: the", { gap: "l33" }],
            ["Float glass, patented in 1952, pours molten glass onto liquid", { gap: "l34" }],
            ["Today 90% of flat glass is made by the", { gap: "l35" }, "process"],
          ],
        },
        questions: [
          { id: "l31", number: 31, answer: ["obsidian"], answerDisplay: "obsidian" },
          { id: "l32", number: 32, answer: ["impurities"], answerDisplay: "impurities" },
          { id: "l33", number: 33, answer: ["blowpipe"], answerDisplay: "blowpipe" },
          { id: "l34", number: 34, answer: ["tin"], answerDisplay: "tin" },
          { id: "l35", number: 35, answer: ["float"], answerDisplay: "float" },
        ],
      },
      {
        id: "l-g8", part: 4, type: "mcq",
        heading: "Questions 36-40",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l36", number: 36, text: "How old is human-made glass?", options: [ { label: "A", text: "About 4,500 years." }, { label: "B", text: "About 450 years." }, { label: "C", text: "About 45,000 years." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l37", number: 37, text: "What does the lecturer call the sailors' discovery story?", options: [ { label: "A", text: "Confirmed fact." }, { label: "B", text: "Charming but almost certainly false." }, { label: "C", text: "In a textbook." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l38", number: 38, text: "What did the blowpipe change?", options: [ { label: "A", text: "Glassware became cheap enough for households." }, { label: "B", text: "Windows were invented." }, { label: "C", text: "Glass turned clear." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l39", number: 39, text: "What is optical fibre made of?", options: [ { label: "A", text: "Copper wire." }, { label: "B", text: "Glass thinner than hair." }, { label: "C", text: "Liquid tin." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l40", number: 40, text: "What is next week's lecture about?", options: [ { label: "A", text: "Volcanoes." }, { label: "B", text: "How fibre is drawn and why its glass must be very pure." }, { label: "C", text: "Cathedrals." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
    ],
  },

  writing: {
    minutes: 60,
    tasks: [
      {
        id: "w1", taskNumber: 1, suggestedMinutes: 20, minimumWords: 150,
        prompt: "The charts below show a company's sales revenue by region in 2010 and 2020, in millions of pounds. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
        chart: {
          type: "bar", title: "Sales revenue by region (£m)", unit: "£ million",
          categories: ["2010", "2020"],
          series: [
            { name: "Europe", values: [42, 45] },
            { name: "Asia", values: [18, 52] },
            { name: "Americas", values: [30, 34] },
          ],
        },
        sampleAnswer: "The bar chart compares the sales revenue of one company across three regions — Europe, Asia and the Americas — in 2010 and 2020, in millions of pounds. Overall, total revenue grew strongly over the decade, and the regional ranking changed completely, with Asia replacing Europe as the largest market. In 2010, Europe was clearly the company's most important market at £42 million, followed by the Americas at £30 million and Asia at £18 million. Ten years later, the picture had inverted. Asian revenue had almost tripled, surging from £18 million to £52 million, making it the largest region by a clear margin. Europe, despite modest growth of £3 million to £45 million, slipped to second place, while the Americas grew only slightly, from £30 million to £34 million, and fell from second to third. In total, the company's revenue rose from £90 million to £131 million, an increase of roughly 45 per cent, with Asia alone contributing almost four-fifths of that growth. The company has therefore shifted from a Europe-centred business to one whose fortunes depend primarily on Asian demand.",
        checklist: [
          "Overview جابه‌جایی رتبه (آسیا جای اروپا) را می‌گوید؟",
          "اعداد شروع و پایان همه مناطق آمده؟",
          "مجموع و سهم رشد آسیا محاسبه/ذکر شده؟",
          "واحد (£m) ذکر شده؟",
          "حداقل ۱۵۰ کلمه؟",
        ],
      },
      {
        id: "w2", taskNumber: 2, suggestedMinutes: 40, minimumWords: 250,
        prompt: "Some people believe that governments should spend money on space exploration. Others think this money should be spent on problems on Earth. Discuss both views and give your own opinion.",
        sampleAnswer: "Every few months, a probe lands on a distant rock or a telescope returns an image of the early universe, and the same argument restarts: should governments fund this, or spend the money on hospitals, schools and the poor? Both sides argue from conscience, which is what makes the dispute durable — and worth examining closely rather than settling with slogans. The case for redirecting space budgets is straightforward moral arithmetic. Public money is finite; a single flagship mission can cost billions, and the same sum builds thousands of classrooms or funds vaccination campaigns for years. Critics also point out that space budgets grew from military rivalry, that their glamorous announcements distract from urgent planetary problems, and that the most serious challenges — climate change, pandemics, antibiotic resistance — will not be solved from orbit. It is a serious argument, and honest advocates of exploration should not sneer at it. The defence begins with scale, not romance. Earth-observation satellites — built, launched and maintained by the same agencies that fly probes — are now central to weather forecasting, climate monitoring, disaster response and agriculture; the early-warning systems that save thousands of lives in typhoon seasons are, quite literally, space programmes. Then there is the economics of spill-over: weather prediction alone repays space investment many times over, and technologies from water purification to medical imaging trace parts of their lineage to missions built for far harsher environments than any hospital. There is also the unpriceable: the pale image of Earth from deep space did more to launch the environmental movement than any pamphlet, and generations of scientists and engineers entered their fields because of it. My own view is that the dichotomy is mostly false. The world's problems are rarely short of money; they are short of organisation and political will, and cancelling science would not redirect a pound of a space budget to the poor — history suggests it would move to weapons or tax cuts. The genuinely important choice is proportion: exploration deserves a modest, protected fraction of public spending, not a blank cheque, and its benefits should be reported as soberly as its rockets are launched. In conclusion, space spending is neither a luxury to be abolished nor a sacred mission above scrutiny. It is a long-term investment that occasionally transforms life on Earth and, more modestly, answers questions we did not know we had. The reasoned position is to fund it — while never letting the glamour above the atmosphere excuse neglect below it.",
        checklist: [
          "استدلال طرف مقابل (هزینه‌فرصت اخلاقی) قوی و منصفانه بیان شده؟",
          "پاسخ (ماهواره‌های سنجش، اسپیل‌اور، اثر فرهنگی) مشخص است؟",
          "نظر شخصی (نسبت مناسب نه لغو کامل) روشن است؟",
          "نتیجه‌گیری تعادل برقرار می‌کند؟",
          "حداقل ۲۵۰ کلمه؟",
        ],
      },
    ],
  },
};
