import type { IeltsTest } from "@/types/ielts";

// ========================================
// کتاب کمبریج ۰۸ — تست ۱ آکادمیک (محتوای تمرینی اختصاصی Flex English)
// ========================================

export const book08: IeltsTest = {
  slug: "cambridge-08",
  bookNumber: 8,
  testNumber: 1,
  module: "ACADEMIC",
  titleFa: "کمبریج ۰۸ — تست ۱",
  titleEn: "Cambridge 08 — Test 1",
  available: true,

  reading: {
    minutes: 60,
    passages: [
      {
        part: 1,
        title: "The Bicycle Revolution",
        intro: "How two wheels changed everything, twice",
        paragraphs: [
          { label: "A", text: "The bicycle arrived in the 1880s and within twenty years had reshaped the modern world more than most inventions manage in a century. Its direct ancestor, the 'safety' bicycle of 1885 — equal-sized wheels, chain drive, pneumatic tyres — solved the comfort and danger problems of earlier designs, and production costs fell so fast that by 1900 a worker could buy one with a few weeks' wages." },
          { label: "B", text: "The first revolution was social. The bicycle gave ordinary people — and especially women — affordable, unaccompanied mobility for the first time in history. Feminist campaigners of the era treated it as a machine of liberation: it loosened dress codes, made chaperones impractical and widened the world a working woman could reach from a few streets to a whole county. Susan B. Anthony's remark that bicycling had done 'more to emancipate women than anything else in the world' was only half a joke." },
          { label: "C", text: "The second revolution was industrial and paved the way for the car. Bicycle manufacturers pioneered interchangeable parts, precision machining, mass marketing and the assembly-line techniques later associated with automobiles; the first motor cars in several countries were built in bicycle factories by bicycle engineers. Early aviation borrowed too — the Wright brothers ran a bicycle workshop, and the first aircraft frame was essentially a bicycle in wire and cloth." },
          { label: "D", text: "Then the car took over the road and the bicycle was demoted, for half a century, to a toy or a poor man's transport. The rediscovery began in the 1970s, when oil shocks and congestion prompted Amsterdam and Copenhagen to rebuild their streets around bikes. Those cities' now-famous cycling rates were not a cultural accident but a policy decision: separate lanes, priority at junctions, parking and, crucially, making driving slow and expensive in the centre." },
          { label: "E", text: "Today the third revolution is under way, powered by batteries. Electric assistance removes the hills, the sweat and the age limit: the average buyer of an e-bike in Europe is now over 45, and cargo versions are replacing a second family car in city after city. Sales of e-bikes already exceed those of electric cars by a wide margin, quietly making the oldest new technology on the road once again the fastest-growing one." },
        ],
      },
      {
        part: 2,
        title: "Reading on Screens",
        intro: "What we know — and admit we don't — about digital reading",
        paragraphs: [
          { label: "A", text: "The question 'are screens bad for reading?' sounds simple, and the research answer is: it depends on what is being read, by whom, and why. Two decades of studies, synthesised in dozens of reviews, have moved from panic to a calmer, more precise picture that rarely makes headlines — because precision does not make headlines." },
          { label: "B", text: "The most robust finding concerns long informational texts. In controlled comparisons, students reading the same long text on paper score modestly but consistently higher on comprehension than screen readers, and the gap widens with length and with time pressure. Crucially, the gap has narrowed among younger cohorts raised with screens — suggesting the difference is partly habit rather than biology, and that habit can move in either direction." },
          { label: "C", text: "For short texts the picture reverses. Screen readers are faster at locating a specific fact, skimming headlines and comparing options; search-and-check reading, the kind most jobs actually require, is superior on screens. It is the deep, single-author argument — the thing a textbook chapter or a long essay does — that suffers most when the medium offers constant, effortless interruption." },
          { label: "D", text: "The mechanism appears to be metacognitive rather than mechanical. Readers on screens report feeling they understand as well as on paper, while tests show they do not: they underestimate the difficulty of digital text and overestimate their attention to it. Paper, oddly, provides subtle anchors — weight of pages read, position of a remembered passage — that help readers monitor their own comprehension in ways a scroll bar does not." },
          { label: "E", text: "Practical conclusions follow for schools and for each of us. Curriculum documents now widely recommend matching medium to purpose: screens for research, reference and collaboration; paper for sustained study of long arguments. For individuals, the honest summary is unglamorous: if you need to understand a long text deeply, and you notice you have re-read the same paragraph three times, the cheapest intervention available is to print it, or at least close every other window first." },
        ],
      },
      {
        part: 3,
        title: "The Science of Laughter",
        intro: "Serious findings about our strangest sound",
        paragraphs: [
          { text: "Laughter is one of the most ordinary human activities and one of the least understood. We do it thousands of times a year, mostly in company, and almost never because anyone told a joke. That last fact, established by researchers who eavesdropped on ordinary conversations, is the doorway into the science: laughter is not primarily a response to humour. It is a social signal — a kind of audible punctuation that says 'we are playing, we are safe, we are together'." },
          { text: "The timing proves the point. In recorded conversations, speakers laugh markedly more than listeners, and people laugh at their own remarks far more than stand-up comedy ever allows. Laughter clusters at the ends of sentences, coordinated with breathing, and it is astonishingly contagious: brain imaging shows that hearing laughter prepares the motor system to join in, which is why a giggle in a quiet room spreads like a dropped match." },
          { text: "Its chemistry is real. Genuine laughter — the involuntary kind that doubles you over — triggers endorphin release, measurably raises pain thresholds and lowers stress hormones. This is the basis of laughter therapy, whose findings, though modest, are real enough to survive replication: laughter genuinely relaxes blood vessel walls, and social laughter genuinely bonds groups. The catch is that only the real thing works fully; polite social laughter, produced deliberately, is a different muscular event and a different neural one." },
          { text: "Laughter also has a dark twin: it marks hierarchy and exclusion as fluently as it marks affection. A workplace study found subordinates laughing at a superior's comments many times more often than the reverse; mockery is laughter's weaponised form; and the difference between 'laughing with' and 'laughing at' is among the first social distinctions children learn to detect. The same signal that builds a group can, aimed outward, define who is outside it." },
          { text: "Evolutionarily, laughter appears to predate language by millions of years — its vocal pattern matches the play sounds of young apes, and it develops in human infants months before speech. Some researchers therefore treat it as the older, simpler channel of human bonding: the thing conversation is built around, rather than a decoration on it. On this view, when we joke, we are borrowing the ancient reflex; when we simply laugh together at nothing in particular, we are using it in its original, honest form." },
        ],
      },
    ],
    groups: [
      {
        id: "r-g1", part: 1, type: "mcq",
        heading: "Questions 1-5",
        instruction: "Choose the correct letter, A, B, C or D.",
        questions: [
          { id: "r1", number: 1, text: "What did the 1885 'safety' bicycle solve?", options: [ { label: "A", text: "Comfort and danger problems of earlier designs." }, { label: "B", text: "The price of rubber." }, { label: "C", text: "Traffic rules." }, { label: "D", text: "The need for roads." } ], answer: ["A"], answerDisplay: "A" },
          { id: "r2", number: 2, text: "Why did feminists value the bicycle?", options: [ { label: "A", text: "It was fashionable." }, { label: "B", text: "It gave women affordable, unaccompanied mobility." }, { label: "C", text: "It was faster than trains." }, { label: "D", text: "It was free." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r3", number: 3, text: "What is the connection between bicycles and aviation?", options: [ { label: "A", text: "Planes replaced bikes." }, { label: "B", text: "The Wright brothers ran a bicycle workshop; the first aircraft frame resembled a bicycle." }, { label: "C", text: "Both use pedals." }, { label: "D", text: "None mentioned." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r4", number: 4, text: "What made Amsterdam and Copenhagen cycling cities, according to the passage?", options: [ { label: "A", text: "Culture alone." }, { label: "B", text: "Weather." }, { label: "C", text: "Deliberate policy: lanes, priority, and slowing cars." }, { label: "D", text: "Cheap bikes." } ], answer: ["C"], answerDisplay: "C" },
          { id: "r5", number: 5, text: "What characterises the third bicycle revolution?", options: [ { label: "A", text: "Wooden frames." }, { label: "B", text: "Battery assistance, older average buyers and cargo versions replacing second cars." }, { label: "C", text: "Bans on cars." }, { label: "D", text: "Faster races." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
      {
        id: "r-g2", part: 1, type: "match-info",
        heading: "Questions 6-10",
        instruction: "The reading passage has five paragraphs, A-E. Which paragraph contains the following information?",
        options: [ { label: "A", text: "A" }, { label: "B", text: "B" }, { label: "C", text: "C" }, { label: "D", text: "D" }, { label: "E", text: "E" } ],
        questions: [
          { id: "r6", number: 6, text: "a famous quote about women's emancipation", answer: ["B"], answerDisplay: "B" },
          { id: "r7", number: 7, text: "how quickly production costs fell", answer: ["A"], answerDisplay: "A" },
          { id: "r8", number: 8, text: "a city where the bicycle was demoted for decades", answer: ["D"], answerDisplay: "D" },
          { id: "r9", number: 9, text: "manufacturing techniques borrowed by the car industry", answer: ["C"], answerDisplay: "C" },
          { id: "r10", number: 10, text: "sales of one bicycle type now far exceeding electric cars", answer: ["E"], answerDisplay: "E" },
        ],
      },
      {
        id: "r-g3", part: 1, type: "sentence-completion",
        heading: "Questions 11-13",
        instruction: "Complete the sentences below. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
        wordLimit: "NO MORE THAN TWO WORDS",
        questions: [
          { id: "r11", number: 11, before: "The bicycle loosened", after: "for women riders.", answer: ["dress codes"], answerDisplay: "dress codes" },
          { id: "r12", number: 12, before: "Early motor cars in several countries were built in", after: ".", answer: ["bicycle factories"], answerDisplay: "bicycle factories" },
          { id: "r13", number: 13, before: "Electric assistance removes hills, sweat and the", after: ".", answer: ["age limit"], answerDisplay: "age limit" },
        ],
      },
      {
        id: "r-g4", part: 2, type: "tfng",
        heading: "Questions 14-19",
        instruction: "Do the following statements agree with the information given in the reading passage? Write TRUE, FALSE or NOT GIVEN.",
        options: [ { label: "TRUE", text: "TRUE" }, { label: "FALSE", text: "FALSE" }, { label: "NOT GIVEN", text: "NOT GIVEN" } ],
        questions: [
          { id: "r14", number: 14, text: "Research has produced a simple yes-or-no answer about screens and reading.", answer: ["FALSE"], answerDisplay: "FALSE" },
          { id: "r15", number: 15, text: "Students reading long informational texts on paper score higher on comprehension.", answer: ["TRUE"], answerDisplay: "TRUE" },
          { id: "r16", number: 16, text: "The paper-screen gap has widened among younger cohorts.", answer: ["FALSE"], answerDisplay: "FALSE" },
          { id: "r17", number: 17, text: "Screens are better for locating a specific fact quickly.", answer: ["TRUE"], answerDisplay: "TRUE" },
          { id: "r18", number: 18, text: "Screen readers accurately judge how well they understood a text.", answer: ["FALSE"], answerDisplay: "FALSE" },
          { id: "r19", number: 19, text: "Tablet sales fell after 2015.", answer: ["NOT GIVEN"], answerDisplay: "NOT GIVEN" },
        ],
      },
      {
        id: "r-g5", part: 2, type: "note-completion",
        heading: "Questions 20-23",
        instruction: "Complete the notes below. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
        wordLimit: "NO MORE THAN TWO WORDS",
        table: {
          headers: ["SCREEN READING — KEY POINTS", ""],
          rows: [
            ["Gap between paper and screens widens with text length and", { gap: "r20" }],
            ["Screen readers are superior at", { gap: "r21" }, "reading — locating facts fast"],
            ["The mechanism is metacognitive: readers on screens", { gap: "r22" }, "the difficulty of digital text"],
            ["Paper provides anchors such as the weight of pages and the", { gap: "r23" }, "of a remembered passage"],
          ],
        },
        questions: [
          { id: "r20", number: 20, answer: ["time pressure"], answerDisplay: "time pressure" },
          { id: "r21", number: 21, answer: ["search-and-check"], answerDisplay: "search-and-check" },
          { id: "r22", number: 22, answer: ["underestimate"], answerDisplay: "underestimate" },
          { id: "r23", number: 23, answer: ["position"], answerDisplay: "position" },
        ],
      },
      {
        id: "r-g6", part: 2, type: "mcq",
        heading: "Questions 24-26",
        instruction: "Choose the correct letter, A, B, C or D.",
        questions: [
          { id: "r24", number: 24, text: "Which kind of reading suffers most on screens?", options: [ { label: "A", text: "Checking a timetable." }, { label: "B", text: "Deep, single-author argument." }, { label: "C", text: "Comparing prices." }, { label: "D", text: "Reading headlines." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r25", number: 25, text: "What do curriculum documents now recommend?", options: [ { label: "A", text: "Screens only." }, { label: "B", text: "Paper only." }, { label: "C", text: "Matching medium to purpose." }, { label: "D", text: "Banning either one." } ], answer: ["C"], answerDisplay: "C" },
          { id: "r26", number: 26, text: "What does the writer suggest if you re-read a paragraph three times?", options: [ { label: "A", text: "Give up." }, { label: "B", text: "Print it or close other windows." }, { label: "C", text: "Read faster." }, { label: "D", text: "Buy a new device." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
      {
        id: "r-g7", part: 3, type: "mcq",
        heading: "Questions 27-31",
        instruction: "Choose the correct letter, A, B, C or D.",
        questions: [
          { id: "r27", number: 27, text: "What did researchers discover by eavesdropping on conversations?", options: [ { label: "A", text: "Laughter is mostly a response to jokes." }, { label: "B", text: "We rarely laugh because of jokes; it is a social signal." }, { label: "C", text: "People never laugh alone." }, { label: "D", text: "Laughter is random." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r28", number: 28, text: "What does laughter cluster around in speech?", options: [ { label: "A", text: "The beginnings of conversations." }, { label: "B", text: "The ends of sentences, coordinated with breathing." }, { label: "C", text: "Long silences." }, { label: "D", text: "Only punchlines." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r29", number: 29, text: "What is said about genuine versus polite laughter?", options: [ { label: "A", text: "Only genuine laughter works fully as a muscular and neural event." }, { label: "B", text: "Both are identical." }, { label: "C", text: "Polite laughter is healthier." }, { label: "D", text: "Neither can be studied." } ], answer: ["A"], answerDisplay: "A" },
          { id: "r30", number: 30, text: "What did the workplace study find?", options: [ { label: "A", text: "Bosses laugh at subordinates more." }, { label: "B", text: "Subordinates laugh at superiors' comments many times more often." }, { label: "C", text: "Nobody laughs at work." }, { label: "D", text: "Laughter is banned." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r31", number: 31, text: "What do some researchers consider laughter to be?", options: [ { label: "A", text: "A recent invention." }, { label: "B", text: "The older, simpler channel of human bonding that conversation is built around." }, { label: "C", text: "A form of singing." }, { label: "D", text: "Purely a language artefact." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
      {
        id: "r-g8", part: 3, type: "summary-completion",
        heading: "Questions 32-36",
        instruction: "Complete the summary below. Choose ONE WORD ONLY from the passage for each answer.",
        wordLimit: "ONE WORD ONLY",
        lines: [
          "Laughter is primarily social rather than comic. In conversations, speakers laugh more than",
          { gap: "r32" },
          ", and hearing laughter prepares the brain's motor system to join in, making it powerfully",
          { gap: "r33" },
          ". Genuine laughter releases endorphins, raises pain thresholds and lowers stress",
          { gap: "r34" },
          ". It also has a dark side: it marks hierarchy, and mockery is its weaponised form. Developmentally, laughter appears in infants months before",
          { gap: "r35" },
          ", and its vocal pattern matches the play sounds of young",
          { gap: "r36" },
          ".",
        ],
        questions: [
          { id: "r32", number: 32, before: "speakers laugh more than", after: "", answer: ["listeners"], answerDisplay: "listeners" },
          { id: "r33", number: 33, before: "making it powerfully", after: "", answer: ["contagious"], answerDisplay: "contagious" },
          { id: "r34", number: 34, before: "lowers stress", after: "", answer: ["hormones"], answerDisplay: "hormones" },
          { id: "r35", number: 35, before: "in infants months before", after: "", answer: ["speech"], answerDisplay: "speech" },
          { id: "r36", number: 36, before: "play sounds of young", after: "", answer: ["apes"], answerDisplay: "apes" },
        ],
      },
      {
        id: "r-g9", part: 3, type: "short-answer",
        heading: "Questions 37-40",
        instruction: "Answer the questions below. Choose NO MORE THAN THREE WORDS from the passage for each answer.",
        wordLimit: "NO MORE THAN THREE WORDS",
        questions: [
          { id: "r37", number: 37, text: "What does laughter say, in the writer's phrase, about a group?", answer: ["we are playing, we are safe, we are together", "we are safe"], answerDisplay: "'we are playing, we are safe, we are together'" },
          { id: "r38", number: 38, text: "What does laughter measurably raise, alongside endorphin release?", answer: ["pain thresholds"], answerDisplay: "pain thresholds" },
          { id: "r39", number: 39, text: "Which distinction do children learn to detect early?", answer: ["laughing with and laughing at", "between laughing with and laughing at"], answerDisplay: "laughing with vs laughing at" },
          { id: "r40", number: 40, text: "How long before language does laughter appear to have existed?", answer: ["millions of years"], answerDisplay: "millions of years" },
        ],
      },
    ],
  },

  listening: {
    minutes: 30,
    sections: [
      {
        part: 1, title: "Enrolling in an evening course", context: "Conversation at a college", estimatedSec: 270,
        script: [
          { speaker: "WOMAN", text: "Evening courses office, can I help?" },
          { speaker: "MAN", text: "Hi. I saw the brochure — the photography course. Can I still join?" },
          { speaker: "WOMAN", text: "Let me check. The Tuesday class is full, but Thursday still has places. Both run 6:30 to 8:30, ten weeks." },
          { speaker: "MAN", text: "Thursdays work. What's the difference between the two classes?" },
          { speaker: "WOMAN", text: "Same syllabus, same tutor actually. Tuesday just filled first because it's listed first in the brochure." },
          { speaker: "MAN", text: "Funny how that works. What do I need — a camera?" },
          { speaker: "WOMAN", text: "Any camera with manual settings, including a phone in pro mode. The tutor recommends a tripod by week four, but we lend those." },
          { speaker: "MAN", text: "And the price?" },
          { speaker: "WOMAN", text: "150 pounds for the ten weeks, or 120 if you book before the end of this week — the early rate." },
          { speaker: "MAN", text: "I'll book now then. Is there a materials cost on top?" },
          { speaker: "WOMAN", text: "Ten pounds, one-off, for printing — you get a portfolio of your best work at the end. There's a small exhibition of student photos in the last week, by the way. Friends and family welcome." },
          { speaker: "MAN", text: "That's a nice target to work toward. Do I need any experience?" },
          { speaker: "WOMAN", text: "None — it starts from zero: exposure, composition, light, then a genre each week from week five. Portraits, street, landscape, night..." },
          { speaker: "MAN", text: "Sold. Can I pay the deposit today?" },
          { speaker: "WOMAN", text: "You can pay in full, or hold a place with thirty pounds. The balance is due at the first class. Card's fine." },
          { speaker: "MAN", text: "Full payment, please — less to think about." },
          { speaker: "WOMAN", text: "Perfect. I'll need a name, email, and a contact number, and you'll get the joining instructions this week." },
        ],
      },
      {
        part: 2, title: "Welcome to the city farm",
        context: "Talk to visitors at a city farm",
        estimatedSec: 300,
        script: [
          { speaker: "NARRATOR", text: "You will hear the welcome talk at a city farm." },
          { speaker: "MAN", text: "Welcome to Mudchute City Farm — forty acres of fields and animals, five minutes from the Underground, which still surprises people. A quick word on how the place works, and then you're free." },
          { speaker: "MAN", text: "Entry is free, always — we're a charity, and the animals are here for everyone. The feeding sessions are the highlight: goats at ten, donkeys at noon, and the very popular pig feeding at three. Volunteers hand out the feed, so join the small queue by each paddock. If you have very young children, the petting corner near the barn is open all day." },
          { speaker: "MAN", text: "A few rules keep everyone safe and calm. Please don't feed the animals anything except the official feed — especially not bread, which the donkeys adore and can't digest. Gates must stay closed — yes, all of them, even the ones that look pointless; the sheep are cleverer than they look. And dogs are welcome on leads except in the animal areas, where they're not allowed at all." },
          { speaker: "MAN", text: "The cafe is by the main gate, open till four. On Saturdays there's a vegetable stall — whatever the garden grew that week, pay what you think is fair. The shop sells eggs from the farm's own hens, honey from our bees, and wool kit if the crafting bug bites." },
          { speaker: "MAN", text: "Finally, if you enjoy today, we run volunteer mornings every Wednesday — no experience needed, wellies provided, tea guaranteed. Ask at the office by the cafe. Enjoy the farm, and remember: the goat follows anyone holding a green bucket. That is a promise, not a warning." },
        ],
      },
      {
        part: 3, title: "Discussing a marketing project brief",
        context: "Two students interpret a client brief",
        estimatedSec: 300,
        script: [
          { speaker: "NARRATOR", text: "You will hear two students discussing a marketing project brief from a real client." },
          { speaker: "WOMAN", text: "Right, the brief. A local bakery wants to attract customers under thirty. Budget: basically nothing. Where do we start?" },
          { speaker: "MAN", text: "With what the bakery actually sells. Their bread is genuinely good — proper sourdough. But the shop looks like it's from 1985 and closes at two." },
          { speaker: "WOMAN", text: "So the problem isn't product, it's image and access. Students want coffee places that look good in photos and stay open late." },
          { speaker: "MAN", text: "Exactly. But we can't propose rebuilding the shop on a tiny budget. What's the cheapest lever?" },
          { speaker: "WOMAN", text: "Social media, obviously — but that's the lazy answer unless we say what exactly." },
          { speaker: "MAN", text: "Then let's be specific. The owner's daughter is at college and films everything anyway. We propose she runs a short-video account — bread being scored, ovens opening at dawn — no actors, no budget, just process." },
          { speaker: "WOMAN", text: "Bakery content does weirdly well online. And what about the hours? Could they trial one late evening?" },
          { speaker: "MAN", text: "Thursday. There's a cinema next door — a Thursday five-to-eight window catches the pre-film crowd without changing their whole routine." },
          { speaker: "WOMAN", text: "A four-week trial, measured by till receipts. That gives our report real data, which the tutor will love." },
          { speaker: "MAN", text: "So the structure: keep the product, refresh the story through short video, trial late Thursdays, measure, then recommend. Simple, cheap, testable." },
          { speaker: "WOMAN", text: "I'll draft the slides. You contact the owner for approval — she liked us, and we need her daughter's filming by next week." },
          { speaker: "MAN", text: "I'll call tomorrow morning before the bakery rush. Slides by Friday?" },
          { speaker: "WOMAN", text: "Friday. And we rehearse Sunday at mine — the tutor warned us about running over ten minutes." },
        ],
      },
      {
        part: 4, title: "Sleep and learning",
        context: "University lecture",
        estimatedSec: 320,
        script: [
          { speaker: "NARRATOR", text: "You will hear part of a lecture on sleep and learning. First, you have some time to look at questions 31 to 40." },
          { speaker: "WOMAN", text: "Here is a fact your student life makes personal: you cannot learn efficiently while you are sleep-deprived, and no amount of caffeine changes the arithmetic. Today we look at why sleep is not the absence of learning but a core part of it." },
          { speaker: "WOMAN", text: "The mechanism has two halves. Deep sleep, in the first half of the night, transfers the day's new memories from short-term storage in the hippocampus into long-term cortex — literally filing them. REM sleep, concentrated toward morning, then appears to reorganise and connect what was filed, which is why difficult problems sometimes solve themselves overnight. Students, note the ordering: the filing happens first. An all-nighter studies into a full hippocampus that never gets time to save." },
          { speaker: "WOMAN", text: "The experimental record is uncomfortably clear. In a classic design, one group practises a skill in the morning and is tested twelve hours later; a second practises in the evening, sleeps, and is tested at the same interval. The sleep group performs substantially better — improvement that came from the night, not extra practice. Similar results hold for vocabulary, for music and for motor skills." },
          { speaker: "WOMAN", text: "Sleep before learning matters too. Volunteers deprived of one night's sleep show a forty per cent drop in the ability to form new memories the next day. The brain's hippocampus, it seems, has a limited capacity and needs sleep to clear it — like an inbox that must be emptied before new mail can be received." },
          { speaker: "WOMAN", text: "So the practical guidance writes itself. Study, then sleep — spacing practice across days so each night can file the material; treat the last week before an exam as a sleep-protection project, not a cramming sprint; and if you must cut something, cut the late-night revision, not the morning lecture. There is, in the whole of learning science, no cheaper performance enhancer than the one you can get for free, tonight." },
        ],
      },
    ],
    groups: [
      {
        id: "l-g1", part: 1, type: "form-completion",
        heading: "Questions 1-5",
        instruction: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["EVENING PHOTOGRAPHY COURSE", ""],
          rows: [
            ["Available class day:", { gap: "l1" }],
            ["Class time: 6:30 to 8:30, for", { gap: "l2" }, "weeks"],
            ["Early-rate price (book before end of this week):", { gap: "l3" }, "pounds"],
            ["One-off printing/materials fee:", { gap: "l4" }, "pounds"],
            ["Deposit option to hold a place:", { gap: "l5" }, "pounds"],
          ],
        },
        questions: [
          { id: "l1", number: 1, answer: ["thursday"], answerDisplay: "Thursday" },
          { id: "l2", number: 2, answer: ["ten", "10"], answerDisplay: "ten" },
          { id: "l3", number: 3, answer: ["120", "one hundred and twenty"], answerDisplay: "120" },
          { id: "l4", number: 4, answer: ["10", "ten"], answerDisplay: "10" },
          { id: "l5", number: 5, answer: ["30", "thirty"], answerDisplay: "30" },
        ],
      },
      {
        id: "l-g2", part: 1, type: "mcq",
        heading: "Questions 6-10",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l6", number: 6, text: "Why did the Tuesday class fill first?", options: [ { label: "A", text: "Different tutor." }, { label: "B", text: "It's listed first in the brochure." }, { label: "C", text: "Better times." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l7", number: 7, text: "What camera is acceptable?", options: [ { label: "A", text: "Any camera with manual settings, including a phone in pro mode." }, { label: "B", text: "Only professional cameras." }, { label: "C", text: "The college lends cameras." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l8", number: 8, text: "What happens in the last week?", options: [ { label: "A", text: "An exam." }, { label: "B", text: "A small exhibition of student photos." }, { label: "C", text: "A trip." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l9", number: 9, text: "What does the course start from?", options: [ { label: "A", text: "Assumed experience." }, { label: "B", text: "Zero — exposure, composition, light." }, { label: "C", text: "Night photography." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l10", number: 10, text: "How does the man pay?", options: [ { label: "A", text: "Deposit only." }, { label: "B", text: "In full by card now." }, { label: "C", text: "Cash at the first class." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
      {
        id: "l-g3", part: 2, type: "mcq",
        heading: "Questions 11-14",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l11", number: 11, text: "What is the farm's size?", options: [ { label: "A", text: "Forty acres." }, { label: "B", text: "Fourteen acres." }, { label: "C", text: "Four hundred acres." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l12", number: 12, text: "When is the popular pig feeding?", options: [ { label: "A", text: "At ten." }, { label: "B", text: "At noon." }, { label: "C", text: "At three." } ], answer: ["C"], answerDisplay: "C" },
          { id: "l13", number: 13, text: "What food rule is emphasised?", options: [ { label: "A", text: "Only official feed — no bread, which donkeys can't digest." }, { label: "B", text: "Any food is fine." }, { label: "C", text: "Vegetables only." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l14", number: 14, text: "What are the rules on dogs?", options: [ { label: "A", text: "Dogs are banned everywhere." }, { label: "B", text: "Welcome on leads except in animal areas." }, { label: "C", text: "Free to run." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
      {
        id: "l-g4", part: 2, type: "note-completion",
        heading: "Questions 15-20",
        instruction: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["MUDCHUTE CITY FARM", ""],
          rows: [
            ["Entry is always", { gap: "l15" }],
            ["Donkey feeding at", { gap: "l16" }],
            ["Petting corner is near the", { gap: "l17" }],
            ["Saturday vegetable stall: pay what you think is", { gap: "l18" }],
            ["The shop sells eggs, honey and", { gap: "l19" }, "kit"],
            ["Volunteer mornings every Wednesday — wellies and", { gap: "l20" }, "provided"],
          ],
        },
        questions: [
          { id: "l15", number: 15, answer: ["free"], answerDisplay: "free" },
          { id: "l16", number: 16, answer: ["noon", "12"], answerDisplay: "noon" },
          { id: "l17", number: 17, answer: ["barn"], answerDisplay: "barn" },
          { id: "l18", number: 18, answer: ["fair"], answerDisplay: "fair" },
          { id: "l19", number: 19, answer: ["wool"], answerDisplay: "wool" },
          { id: "l20", number: 20, answer: ["tea"], answerDisplay: "tea" },
        ],
      },
      {
        id: "l-g5", part: 3, type: "mcq",
        heading: "Questions 21-24",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l21", number: 21, text: "What is the bakery's real problem, in the students' view?", options: [ { label: "A", text: "The bread is poor." }, { label: "B", text: "Image and access, not product." }, { label: "C", text: "The location." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l22", number: 22, text: "Who would run the video account?", options: [ { label: "A", text: "A hired agency." }, { label: "B", text: "The owner's daughter, who already films everything." }, { label: "C", text: "The students themselves." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l23", number: 23, text: "Why Thursday for the late opening trial?", options: [ { label: "A", text: "It's the slowest day." }, { label: "B", text: "A cinema next door brings a pre-film crowd." }, { label: "C", text: "The owner prefers it." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l24", number: 24, text: "How will the trial be measured?", options: [ { label: "A", text: "By till receipts over four weeks." }, { label: "B", text: "By a survey only." }, { label: "C", text: "By counting followers." } ], answer: ["A"], answerDisplay: "A" },
        ],
      },
      {
        id: "l-g6", part: 3, type: "form-completion",
        heading: "Questions 25-30",
        instruction: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["BAKERY PROJECT — PLAN AND DEADLINES", ""],
          rows: [
            ["Proposed late-opening window: 5 to 8 p.m. on", { gap: "l25" }, "for a four-week trial"],
            ["Video content: bread being scored and ovens opening at", { gap: "l26" }],
            ["The man calls the owner", { gap: "l27" }, "morning, before the bakery rush"],
            ["Draft slides due", { gap: "l28" }],
            ["Rehearsal on Sunday at the woman's", { gap: "l29" }],
            ["Tutor's warning: don't run over ten", { gap: "l30" }],
          ],
        },
        questions: [
          { id: "l25", number: 25, answer: ["thursday", "thursdays"], answerDisplay: "Thursdays" },
          { id: "l26", number: 26, answer: ["dawn"], answerDisplay: "dawn" },
          { id: "l27", number: 27, answer: ["tomorrow"], answerDisplay: "tomorrow" },
          { id: "l28", number: 28, answer: ["friday"], answerDisplay: "Friday" },
          { id: "l29", number: 29, answer: ["place", "home", "house"], answerDisplay: "place / home" },
          { id: "l30", number: 30, answer: ["minutes"], answerDisplay: "minutes" },
        ],
      },
      {
        id: "l-g7", part: 4, type: "note-completion",
        heading: "Questions 31-35",
        instruction: "Complete the notes below. Write ONE WORD ONLY for each answer.",
        wordLimit: "ONE WORD ONLY",
        table: {
          headers: ["SLEEP AND LEARNING — THE TWO HALVES", ""],
          rows: [
            ["Deep sleep transfers memories from the hippocampus to the", { gap: "l31" }],
            ["REM sleep, toward morning, reorganises and", { gap: "l32" }, "what was filed"],
            ["In the classic experiment, the evening-practice group improved after a", { gap: "l33" }, "of sleep"],
            ["One night of deprivation cuts new-memory formation by about forty per", { gap: "l34" }],
            ["The hippocampus needs sleep to", { gap: "l35" }, "its limited capacity"],
          ],
        },
        questions: [
          { id: "l31", number: 31, answer: ["cortex"], answerDisplay: "cortex" },
          { id: "l32", number: 32, answer: ["connect"], answerDisplay: "connect" },
          { id: "l33", number: 33, answer: ["night"], answerDisplay: "night" },
          { id: "l34", number: 34, answer: ["cent"], answerDisplay: "cent" },
          { id: "l35", number: 35, answer: ["clear"], answerDisplay: "clear" },
        ],
      },
      {
        id: "l-g8", part: 4, type: "mcq",
        heading: "Questions 36-40",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l36", number: 36, text: "What does the lecturer say an all-nighter does?", options: [ { label: "A", text: "Studies into a full hippocampus that never gets time to save." }, { label: "B", text: "Improves filing." }, { label: "C", text: "Nothing harmful." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l37", number: 37, text: "What improvement does the sleep group show in the classic design?", options: [ { label: "A", text: "Worse performance." }, { label: "B", text: "Substantially better performance." }, { label: "C", text: "Identical performance." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l38", number: 38, text: "What is the effect of sleep deprivation on forming new memories?", options: [ { label: "A", text: "A 40% drop the next day." }, { label: "B", text: "A 4% drop." }, { label: "C", text: "No effect." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l39", number: 39, text: "How should exam week be treated?", options: [ { label: "A", text: "A cramming sprint." }, { label: "B", text: "A sleep-protection project." }, { label: "C", text: "A holiday." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l40", number: 40, text: "What does the lecturer call sleep?", options: [ { label: "A", text: "The cheapest performance enhancer." }, { label: "B", text: "A waste of time." }, { label: "C", text: "An optional extra." } ], answer: ["A"], answerDisplay: "A" },
        ],
      },
    ],
  },

  writing: {
    minutes: 60,
    tasks: [
      {
        id: "w1", taskNumber: 1, suggestedMinutes: 20, minimumWords: 150,
        prompt: "The chart below shows average daily household water use in one country in 1990 and 2020, by category. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
        chart: {
          type: "bar", title: "Average daily household water use (litres per person)", unit: "litres per person per day",
          categories: ["1990", "2020"],
          series: [
            { name: "Bathing", values: [65, 55] },
            { name: "Toilet", values: [40, 32] },
            { name: "Kitchen", values: [30, 26] },
            { name: "Laundry", values: [25, 35] },
            { name: "Garden", values: [20, 12] },
          ],
        },
        sampleAnswer: "The bar chart compares average daily household water use per person across five categories in one country, in 1990 and 2020. Overall, total consumption fell over the thirty-year period, with reductions in most categories offsetting a clear rise in laundry use. In 1990, bathing was by far the largest use at 65 litres per person per day, followed by toilet flushing at 40, kitchen use at 30, laundry at 25 and the garden at 20 — a total of 180 litres. By 2020, the pattern was similar in shape but lower overall: bathing remained the largest category despite falling to 55 litres, toilet use dropped to 32, kitchen use to 26, and garden watering nearly halved to 12 litres. The exception was laundry, which rose from 25 to 35 litres, overtaking kitchen use — a change presumably explained by more frequent washing of clothes rather than more water per cycle. In total, daily use fell from 180 to 160 litres per person, a decline of about eleven per cent, achieved in every category except laundry.",
        checklist: [
          "Overview کل روند (کاهش کلی + استثنای لباسشویی) را می‌دهد؟",
          "داده‌های همه دسته‌ها در هر دو سال آمده؟",
          "جابه‌جایی رتبه (لباسشویی از آشپزخانه جلو زد) ذکر شده؟",
          "مجموع و درصد کاهش محاسبه شده؟",
          "حداقل ۱۵۰ کلمه؟",
        ],
      },
      {
        id: "w2", taskNumber: 2, suggestedMinutes: 40, minimumWords: 250,
        prompt: "Some people believe that protecting the environment is the responsibility of governments, while others believe it is the responsibility of individuals. Discuss both views and give your own opinion.",
        sampleAnswer: "When the weather turns strange and the rivers run low, the question of who should fix it returns: governments, with their power to legislate, or individuals, with their millions of daily choices. Both answers contain something important, but each is incomplete without the other, and treating them as rivals is the surest way to achieve neither. The case for government responsibility is the case for physics. Climate change and mass pollution are systemic problems: no individual choice can redesign an electricity grid, set fuel standards, tax carbon or negotiate with neighbouring states. Moreover, individual behaviour is heavily shaped by infrastructure and price — people drive where public transport is poor and buy what is cheap, and only governments change those conditions. Countries that have cut emissions fastest did so through policy: renewable mandates, efficiency standards and carbon pricing, not through appeals to conscience. The individualist case starts where such arguments end. Governments are slow, captured by lobbies and elected on short cycles; meanwhile, half of emissions flow through millions of small household decisions — heating, driving, flying, diet, waste. Personal action also builds the political weather: a public that cycles, repairs and votes with climate in mind elects governments that legislate; one that does not, does not. And there is a moral dimension that policy alone cannot reach: knowing what we now know, outsourcing all responsibility feels less like efficiency and more like an excuse. My view is that the question itself is badly framed. Responsibility is not a fixed quantity to be divided between state and citizen like a bill; it is a loop. Policy makes sustainable choices easy, individuals adopt and normalise them, and that normalisation creates the mandate for braver policy. Recycling followed exactly this path from eccentric habit to kerbside law, and electric cars are following it now. The framing that matters, therefore, is sequence: governments move first where only they can — energy, transport, industry — and individuals move first everywhere culture leads policy. In conclusion, both positions are half right, which is why the debate between them is so sterile. Governments hold the levers that change systems; individuals hold the values that pull them. Environmental protection is not the responsibility of one or the other but of the loop between them — and strengthening that loop, rather than arguing about its halves, is the actual task of this generation.",
        checklist: [
          "استدلال دو طرف به‌طور مستقل قوی بیان شده؟",
          "ایدهٔ «حلقهٔ مسئولیت» محور نظر شخصی است؟",
          "مثال بازیافت و خودروی برقی برای حلقه آورده شده؟",
          "نتیجه‌گیری چارچوب سوال را بازنویسی می‌کند نه تکرار؟",
          "حداقل ۲۵۰ کلمه؟",
        ],
      },
    ],
  },
};
