import type { IeltsTest } from "@/types/ielts";

// ========================================
// کتاب کمبریج ۰۵ — تست ۱ آکادمیک (محتوای تمرینی اختصاصی Flex English)
// ========================================

export const book05: IeltsTest = {
  slug: "cambridge-05",
  bookNumber: 5,
  testNumber: 1,
  module: "ACADEMIC",
  titleFa: "کمبریج ۰۵ — تست ۱",
  titleEn: "Cambridge 05 — Test 1",
  available: true,

  reading: {
    minutes: 60,
    passages: [
      {
        part: 1,
        title: "Chocolate: From Ritual to Bar",
        intro: "A bitter drink becomes the world's favourite sweet",
        paragraphs: [
          { label: "A", text: "The story of chocolate begins not with sweetness but with bitterness. The Maya and later the Aztecs of Central America consumed cacao as a frothy, spiced drink, often cold and unsweetened, in rituals, medicine and daily life alike. Cacao beans were valuable enough to serve as currency: records describe marketgoers paying for goods with counted beans, and tax collectors accepting them from conquered provinces." },
          { label: "B", text: "European contact transformed the drink rather than the bean. Spanish arrivals in the sixteenth century found the taste alien and added sugar and warm milk, creating something recognisably close to modern hot chocolate. For two centuries it remained an aristocratic luxury in Europe — expensive, exotic and associated with health claims that ranged from the plausible to the absurd. Coffee houses serving it appeared in the capitals, but only the wealthy drank there." },
          { label: "C", text: "Industrialisation democratised the product. The nineteenth century brought the steam-powered grinding of beans, the cocoa press that separated fat from powder, and finally the conching machine that kneaded chocolate into the smooth solid we know. Each invention lowered prices; by 1900 a bar of eating chocolate was a treat an ordinary worker could afford, and within a generation it was part of military rations, school treats and romance itself." },
          { label: "D", text: "The twentieth century then reversed the recipe. Traditional chocolate is mostly cacao; the industrial bar is mostly sugar, with milk powder and vegetable fats added and the cacao fraction shrinking to a few per cent in the cheapest products. This change made chocolate cheap, stable and universally palatable — and turned cacao itself into a commodity bought at low prices from tropical smallholders while the value accumulated elsewhere in the chain." },
          { label: "E", text: "Today the industry faces demands from two directions at once. Consumers increasingly want proof that cocoa was grown without child labour or deforestation, and they want more of the actual bean in the bar — the premium 'dark' segment grows while mass products stagnate. Both trends push value back toward the farm, though slowly and unevenly. In an odd full circle, some manufacturers now sell a spiced, bitter drinking chocolate openly modelled on the Maya original, at prices the Maya would have found astonishing." },
        ],
      },
      {
        part: 2,
        title: "Farms in the Sky",
        intro: "Vertical farming grows up",
        paragraphs: [
          { label: "A", text: "On a shelf in a warehouse near a big city, lettuce grows under pink light, stacked fifteen levels high, watered by a robot, and never touched by weather. Vertical farming — growing crops in stacked indoor layers — has moved from science-fiction sketches to a real industry with commercial farms operating from Singapore to Chicago. Its advocates promise food grown next to the people who eat it, using a fraction of the land and none of the pesticides." },
          { label: "B", text: "The numbers behind the promise are striking. A vertical farm can produce many times the yield of a field of the same footprint, because light, temperature and nutrients are tuned continuously and harvests run all year. Water use falls by as much as ninety-five per cent, since systems recycle the condensation from leaves, and there are no nutrient runoffs into rivers because there is no soil to leak." },
          { label: "C", text: "But the physics of food is unforgiving, and the obstacle is energy. Field crops take their energy free from the sun; vertical farms must buy electricity to replace it, and light is the single largest cost of production. At current prices this confines profitable crops to a narrow family: soft, fast-growing, high-value leaves such as basil, lettuce and microgreens. Wheat, rice and potatoes — the crops that actually feed the world — remain hopelessly uneconomic indoors, and most analyses conclude they will stay so." },
          { label: "D", text: "The industry's response has been to specialise rather than replace. Vertical farms increasingly sell on reliability rather than price: a hospital or a premium supermarket will pay extra for herbs that are clean, local, identical every week of the year and immune to a drought or a war on another continent. In this role the technology functions less like a farm and more like a factory making perishable components of meals — which is precisely how it is now described in the industry's own documents." },
          { label: "E", text: "Where the technology may matter most is not the wealthy city but the extreme one: the Gulf desert, the Arctic town, the research base, the disaster zone. Where fields cannot exist at any price, energy-hungry indoor growing becomes the rational choice, and military and humanitarian organisations have begun to fund it for exactly that reason. The farm in the sky will not feed the planet; what it may do is make the planet's harshest addresses a little less dependent on supply lines that fail exactly when they are needed most." },
        ],
      },
      {
        part: 3,
        title: "The Placebo Problem",
        intro: "Why fake medicine sometimes works — and what to do about it",
        paragraphs: [
          { text: "In the classic trial, a new drug must beat a placebo — an inert pill that looks identical — before it may be sold. The logic seems airtight: any improvement in the placebo group is imagination, and only effects beyond it count as medicine. Yet seventy years of research into placebos has quietly revealed something more interesting: the 'imaginary' effects are real, measurable, and follow discoverable rules of their own." },
          { text: "The mechanisms are now partly mapped. Placebo pain relief, the best-studied case, is blocked by drugs that disable the body's own painkillers, proving the relief is produced by the brain's chemistry rather than by belief alone. Expectation acts through measurable pathways: the same infusion relieves more when patients are told it is a powerful medicine. Even conditioning works — patients given real relief repeatedly respond later to a dummy that resembles it, the immune and hormonal systems having apparently learned the association." },
          { text: "This creates genuine dilemmas. If dummy pills can relieve real suffering through honest-looking rituals, is prescribing them deception, therapy, or both? Surveys find a majority of physicians admit to sometimes recommending treatments with no specific activity, usually alongsidereal care. Bioethicists are divided: deception erodes the trust on which medicine rests, yet a recent line of studies suggests even open-label placebos — pills honestly labelled as sugar — may still help in some conditions, an unresolved and slightly unsettling result." },
          { text: "The phenomenon also contaminates the trials designed to exclude it. Placebo responses have grown measurably stronger in recent decades, especially in the United States and especially in psychiatry and pain studies, possibly because trials have become longer, larger and more pleasant to attend. A drug that would have passed easily in 1970 may fail today not because it weakened but because the placebo arm improved." },
          { text: "The research frontier has accordingly shifted from asking whether placebos work to engineering their components. Attention, empathy, explanation and the sensory drama of treatment — the injection rather than the tablet, the white coat, the ritual of measurement — all raise the response, and none of them requires lying to the patient. Whether these 'context effects' should be counted as part of medicine's core or separated out as a suspicious trick remains an open question. But the era of dismissing them as noise is over; the dummy pill has earned its place as an object of serious science." },
        ],
      },
    ],
    groups: [
      {
        id: "r-g1", part: 1, type: "match-info",
        heading: "Questions 1-5",
        instruction: "The reading passage has five paragraphs, A-E. Which paragraph contains the following information?",
        options: [ { label: "A", text: "A" }, { label: "B", text: "B" }, { label: "C", text: "C" }, { label: "D", text: "D" }, { label: "E", text: "E" } ],
        questions: [
          { id: "r1", number: 1, text: "the use of cacao beans as money", answer: ["A"], answerDisplay: "A" },
          { id: "r2", number: 2, text: "machines that made chocolate affordable to workers", answer: ["C"], answerDisplay: "C" },
          { id: "r3", number: 3, text: "a change in the recipe that reduced the cacao content", answer: ["D"], answerDisplay: "D" },
          { id: "r4", number: 4, text: "a modern product modelled on an ancient drink", answer: ["E"], answerDisplay: "E" },
          { id: "r5", number: 5, text: "health claims attached to an aristocratic luxury", answer: ["B"], answerDisplay: "B" },
        ],
      },
      {
        id: "r-g2", part: 1, type: "sentence-completion",
        heading: "Questions 6-9",
        instruction: "Complete the sentences below. Choose NO MORE THAN THREE WORDS from the passage for each answer.",
        wordLimit: "NO MORE THAN THREE WORDS",
        questions: [
          { id: "r6", number: 6, before: "The Maya drank cacao cold, spiced and", after: ".", answer: ["unsweetened"], answerDisplay: "unsweetened" },
          { id: "r7", number: 7, before: "The Spanish made the drink recognisably modern by adding sugar and", after: ".", answer: ["warm milk"], answerDisplay: "warm milk" },
          { id: "r8", number: 8, before: "The cocoa press separated fat from", after: ".", answer: ["powder"], answerDisplay: "powder" },
          { id: "r9", number: 9, before: "Chocolate entered military rations, school treats and", after: "within a generation of 1900.", answer: ["romance", "romance itself"], answerDisplay: "romance" },
        ],
      },
      {
        id: "r-g3", part: 1, type: "mcq",
        heading: "Questions 10-13",
        instruction: "Choose the correct letter, A, B, C or D.",
        questions: [
          { id: "r10", number: 10, text: "What did industrialisation do to chocolate?", options: [ { label: "A", text: "Made it rarer." }, { label: "B", text: "Made it affordable to ordinary people." }, { label: "C", text: "Raised its price." }, { label: "D", text: "Banned it from rations." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r11", number: 11, text: "What happened as cacao content in bars fell?", options: [ { label: "A", text: "Value moved away from the farm." }, { label: "B", text: "Farms became richer." }, { label: "C", text: "Sugar disappeared." }, { label: "D", text: "Taxes rose." } ], answer: ["A"], answerDisplay: "A" },
          { id: "r12", number: 12, text: "What do today's premium consumers want?", options: [ { label: "A", text: "More sugar." }, { label: "B", text: "More actual bean in the bar." }, { label: "C", text: "Brighter wrappers." }, { label: "D", text: "Bigger bars." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r13", number: 13, text: "What does the final sentence suggest about Maya-style chocolate today?", options: [ { label: "A", text: "It is banned." }, { label: "B", text: "It is cheap." }, { label: "C", text: "It commands surprisingly high prices." }, { label: "D", text: "It failed to sell." } ], answer: ["C"], answerDisplay: "C" },
        ],
      },
      {
        id: "r-g4", part: 2, type: "tfng",
        heading: "Questions 14-18",
        instruction: "Do the following statements agree with the information given in the reading passage? Write TRUE, FALSE or NOT GIVEN.",
        options: [ { label: "TRUE", text: "TRUE" }, { label: "FALSE", text: "FALSE" }, { label: "NOT GIVEN", text: "NOT GIVEN" } ],
        questions: [
          { id: "r14", number: 14, text: "Vertical farms use pesticides sparingly but do use some.", answer: ["FALSE"], answerDisplay: "FALSE" },
          { id: "r15", number: 15, text: "Vertical farms can harvest all year round.", answer: ["TRUE"], answerDisplay: "TRUE" },
          { id: "r16", number: 16, text: "Wheat is already profitable in vertical farms.", answer: ["FALSE"], answerDisplay: "FALSE" },
          { id: "r17", number: 17, text: "Supermarkets pay a premium for reliability of supply.", answer: ["TRUE"], answerDisplay: "TRUE" },
          { id: "r18", number: 18, text: "Singapore operates the largest vertical farm in the world.", answer: ["NOT GIVEN"], answerDisplay: "NOT GIVEN" },
        ],
      },
      {
        id: "r-g5", part: 2, type: "note-completion",
        heading: "Questions 19-22",
        instruction: "Complete the notes below. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
        wordLimit: "NO MORE THAN TWO WORDS",
        table: {
          headers: ["VERTICAL FARMING", ""],
          rows: [
            ["Crops grow in stacked indoor", { gap: "r19" }],
            ["Water use falls by up to ninety-five per cent because systems recycle", { gap: "r20" }, "from leaves"],
            ["The single largest production cost is", { gap: "r21" }],
            ["Profitable crops are soft, fast-growing and high-value, such as", { gap: "r22" }, "and lettuce"],
          ],
        },
        questions: [
          { id: "r19", number: 19, answer: ["layers"], answerDisplay: "layers" },
          { id: "r20", number: 20, answer: ["the condensation", "condensation"], answerDisplay: "condensation" },
          { id: "r21", number: 21, answer: ["light", "energy"], answerDisplay: "light / energy" },
          { id: "r22", number: 22, answer: ["basil", "microgreens", "herbs"], answerDisplay: "basil / microgreens" },
        ],
      },
      {
        id: "r-g6", part: 2, type: "mcq",
        heading: "Questions 23-26",
        instruction: "Choose the correct letter, A, B, C or D.",
        questions: [
          { id: "r23", number: 23, text: "Why do crops like rice remain uneconomic indoors?", options: [ { label: "A", text: "They taste bad." }, { label: "B", text: "The energy cost of replacing sunlight is too high." }, { label: "C", text: "They grow too fast." }, { label: "D", text: "Robots cannot plant them." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r24", number: 24, text: "How does the industry itself describe vertical farms?", options: [ { label: "A", text: "As traditional farms." }, { label: "B", text: "As factories for perishable food." }, { label: "C", text: "As parks." }, { label: "D", text: "As laboratories only." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r25", number: 25, text: "Where may the technology matter most?", options: [ { label: "A", text: "In tropical farmland." }, { label: "B", text: "In extreme and cut-off places." }, { label: "C", text: "In suburbs." }, { label: "D", text: "In mountain ski resorts." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r26", number: 26, text: "Who funds indoor growing for harsh locations?", options: [ { label: "A", text: "Military and humanitarian organisations." }, { label: "B", text: "Football clubs." }, { label: "C", text: "Farmers' unions." }, { label: "D", text: "Airlines." } ], answer: ["A"], answerDisplay: "A" },
        ],
      },
      {
        id: "r-g7", part: 3, type: "mcq",
        heading: "Questions 27-31",
        instruction: "Choose the correct letter, A, B, C or D.",
        questions: [
          { id: "r27", number: 27, text: "What has research revealed about placebo effects?", options: [ { label: "A", text: "They are pure imagination." }, { label: "B", text: "They are real and follow rules." }, { label: "C", text: "They only occur in trials." }, { label: "D", text: "They cannot be measured." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r28", number: 28, text: "What proves placebo pain relief involves brain chemistry?", options: [ { label: "A", text: "It is blocked by drugs that disable the body's own painkillers." }, { label: "B", text: "Patients say so." }, { label: "C", text: "It lasts forever." }, { label: "D", text: "Scans look normal." } ], answer: ["A"], answerDisplay: "A" },
          { id: "r29", number: 29, text: "What is an open-label placebo?", options: [ { label: "A", text: "A hidden injection." }, { label: "B", text: "A pill honestly labelled as sugar." }, { label: "C", text: "A stronger drug." }, { label: "D", text: "A surgical ritual." } ], answer: ["B"], answerDisplay: "B" },
          { id: "r30", number: 30, text: "What has happened to placebo responses in recent decades?", options: [ { label: "A", text: "They have weakened." }, { label: "B", text: "They have stayed identical." }, { label: "C", text: "They have grown stronger in some regions and fields." }, { label: "D", text: "They have disappeared from psychiatry." } ], answer: ["C"], answerDisplay: "C" },
          { id: "r31", number: 31, text: "What raises the placebo response without lying?", options: [ { label: "A", text: "Longer waiting rooms." }, { label: "B", text: "Attention, empathy and treatment rituals." }, { label: "C", text: "Cheaper pills." }, { label: "D", text: "Bigger pharmacies." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
      {
        id: "r-g8", part: 3, type: "summary-completion",
        heading: "Questions 32-36",
        instruction: "Complete the summary below. Choose ONE WORD ONLY from the passage for each answer.",
        wordLimit: "ONE WORD ONLY",
        lines: [
          "Placebo research began as a way to filter drugs, but it has uncovered real effects. Pain relief from placebos is produced by the brain's own",
          { gap: "r32" },
          "chemistry. The effects respond both to expectation and to",
          { gap: "r33" },
          ", where the body learns from repeated real treatment. A practical problem is that stronger placebo responses can make genuinely effective drugs",
          { gap: "r34" },
          "their trials, since the comparison group improves too much. Researchers now try to engineer the",
          { gap: "r35" },
          "of treatment — its rituals, setting and attentiveness — and debate whether these should be treated as part of",
          { gap: "r36" },
          "itself.",
        ],
        questions: [
          { id: "r32", number: 32, before: "the brain's own", after: "chemistry", answer: ["painkiller", "natural"], answerDisplay: "painkiller / natural" },
          { id: "r33", number: 33, before: "expectation and to", after: "", answer: ["conditioning"], answerDisplay: "conditioning" },
          { id: "r34", number: 34, before: "effective drugs", after: "their trials", answer: ["fail"], answerDisplay: "fail" },
          { id: "r35", number: 35, before: "engineer the", after: "of treatment", answer: ["components", "context"], answerDisplay: "components / context" },
          { id: "r36", number: 36, before: "as part of", after: "itself", answer: ["medicine"], answerDisplay: "medicine" },
        ],
      },
      {
        id: "r-g9", part: 3, type: "tfng",
        heading: "Questions 37-40",
        instruction: "Do the following statements agree with the information given in the reading passage? Write TRUE, FALSE or NOT GIVEN.",
        options: [ { label: "TRUE", text: "TRUE" }, { label: "FALSE", text: "FALSE" }, { label: "NOT GIVEN", text: "NOT GIVEN" } ],
        questions: [
          { id: "r37", number: 37, text: "Most physicians deny ever using inert treatments.", answer: ["FALSE"], answerDisplay: "FALSE" },
          { id: "r38", number: 38, text: "Open-label placebos have been proven useless.", answer: ["FALSE"], answerDisplay: "FALSE" },
          { id: "r39", number: 39, text: "An injection produces a stronger response than a tablet.", answer: ["TRUE"], answerDisplay: "TRUE" },
          { id: "r40", number: 40, text: "Placebo research receives more funding than genetics.", answer: ["NOT GIVEN"], answerDisplay: "NOT GIVEN" },
        ],
      },
    ],
  },

  listening: {
    minutes: 30,
    sections: [
      {
        part: 1, title: "Opening a bank account", context: "Conversation in a bank", estimatedSec: 270,
        script: [
          { speaker: "MAN", text: "Good morning. I've just moved here for work and I need a bank account." },
          { speaker: "WOMAN", text: "Welcome. A standard current account, or a student account?" },
          { speaker: "MAN", text: "Standard, please. My salary will be paid in monthly." },
          { speaker: "WOMAN", text: "Then the Day-to-Day account suits you. There's no monthly fee as long as your salary of at least 500 pounds goes in — otherwise it's 6 pounds a month." },
          { speaker: "MAN", text: "That's fine. What do I get with it?" },
          { speaker: "WOMAN", text: "A debit card, online banking, and fee-free withdrawals at any of our machines — but using other banks' machines costs 1.50 each time." },
          { speaker: "MAN", text: "What about an overdraft?" },
          { speaker: "WOMAN", text: "You can apply after three months. The interest is 15 per cent a year, calculated daily — we always tell people to treat it as a short-term buffer, not free money." },
          { speaker: "MAN", text: "Understood. What documents do you need from me?" },
          { speaker: "WOMAN", text: "Passport or driving licence, and proof of address — a utility bill or a tenancy agreement less than three months old." },
          { speaker: "MAN", text: "My tenancy agreement is at the flat. I could bring it tomorrow." },
          { speaker: "WOMAN", text: "Perfect. I can hold the application for seven days. You'll also choose a PIN — four digits, not your birthday, we check that." },
          { speaker: "MAN", text: "Can I choose it here?" },
          { speaker: "WOMAN", text: "You'll set it at the machine by the door with your temporary card. The permanent card arrives by post in about five working days — remember to activate it from the app." },
          { speaker: "MAN", text: "Great. I'll be back tomorrow morning with the agreement." },
          { speaker: "WOMAN", text: "See you then. Welcome to the city!" },
        ],
      },
      {
        part: 2, title: "Volunteer park run briefing",
        context: "Talk to volunteers at a charity run",
        estimatedSec: 300,
        script: [
          { speaker: "NARRATOR", text: "You will hear a briefing for volunteers at a charity fun run." },
          { speaker: "WOMAN", text: "Right, volunteers — great turnout, thank you. The Riverside 10K starts at ten, and here's how the morning runs." },
          { speaker: "WOMAN", text: "First, marshals: you're the most important people on the course. Collect your yellow vests and position cards from the tent behind me by nine fifteen. Each card shows your corner and the emergency number — keep it in your pocket, not your car. If a runner collapses, stay with them, wave down the roving medic on the bicycle, and call the number if it's serious." },
          { speaker: "WOMAN", text: "Water station teams, you're at the halfway point by the rowing club. We've got three thousand bottles. Fill the cups only halfway — runners can't drink more anyway — and hold them out with the cup's bottom facing the runner. You'll get soaked. That's part of the fun." },
          { speaker: "WOMAN", text: "Finish-line helpers: your job is medals and directing finishers left toward the food tent or right toward first aid. Watch for anyone who sits down immediately and looks grey — walk them gently to the medical tent, don't let them lie on cold ground." },
          { speaker: "WOMAN", text: "Timing: the race officially closes at midday. Roads reopen at twelve-fifteen sharp — after that, anyone still running is picked up by the sweeper van. And a last thing: lost children go to the bandstand; lost property comes to this tent. Any questions? No? Then vests on, and let's have a brilliant morning." },
        ],
      },
      {
        part: 3, title: "Choosing a dissertation topic",
        context: "Two students discuss topic options",
        estimatedSec: 310,
        script: [
          { speaker: "NARRATOR", text: "You will hear two students discussing dissertation topics." },
          { speaker: "MAN", text: "Deadline for the dissertation proposal is the end of the month. Have you picked your topic yet, Lena?" },
          { speaker: "WOMAN", text: "I keep swinging between two. One is noise pollution in hospitals — I work part-time as a cleaner on a ward, so I could collect real data." },
          { speaker: "MAN", text: "That's a strong angle. Access is always the hardest part, and you already have it." },
          { speaker: "WOMAN", text: "Except my supervisor says ethics approval for hospitals takes up to three months. The dissertation is due in five. It's tight." },
          { speaker: "MAN", text: "Risky. What's the other one?" },
          { speaker: "WOMAN", text: "Sound levels in open-plan offices. I could measure three or four local companies — my aunt manages one of them." },
          { speaker: "MAN", text: "Ethics for companies is usually quicker — anonymous measurement, no patients involved. And open-plan offices are a hot topic; you'd have plenty of recent literature." },
          { speaker: "WOMAN", text: "That's what I thought, but it feels less original. Everyone studies offices." },
          { speaker: "MAN", text: "Not with your angle. You could compare hospital ward noise standards with office standards — the methods carry over, and it makes the hospital question your future master's proposal instead." },
          { speaker: "WOMAN", text: "Oh — that's clever. Do the office study now, safely inside the deadline, and keep the hospital idea for later." },
          { speaker: "MAN", text: "Exactly. And your aunt's company gives you a pilot site immediately; the other companies will be easier to approach once you have pilot results." },
          { speaker: "WOMAN", text: "You've talked me into it. I'll email my supervisor tonight: office noise, comparative methods, hospital study as future work." },
          { speaker: "MAN", text: "That's a proposal I'd approve. Fancy the library after lunch to draft it?" },
          { speaker: "WOMAN", text: "Deal — two o'clock by the entrance." },
        ],
      },
      {
        part: 4, title: "Roman concrete",
        context: "University lecture",
        estimatedSec: 320,
        script: [
          { speaker: "NARRATOR", text: "You will hear part of a lecture on Roman concrete. First, you have some time to look at questions 31 to 40." },
          { speaker: "MAN", text: "Stand in the Pantheon in Rome and you are under the largest unreinforced concrete dome ever built — two thousand years old, and still perfect. Modern concrete structures are designed for a fifty-year life. Today's lecture asks why the Roman version has lasted so long, and what we are now learning from it." },
          { speaker: "MAN", text: "The Roman recipe was simple: volcanic ash called pozzolana, lime, seawater where available, and chunks of rock as filler. The ash was the secret. It reacts with lime and water to form a cement that keeps hardening for years and, crucially, continues reacting in a self-healing way: when cracks appear, unreacted lime inside them forms new minerals that seal the gap." },
          { speaker: "MAN", text: "The most surprising discovery came from samples taken from a harbour wall near Naples. Seawater, which destroys modern concrete by rusting its steel reinforcement and eating its surface, actually made the Roman harbour walls stronger over the centuries. The minerals in the mix reacted with the seawater to grow new binding crystals throughout the structure." },
          { speaker: "MAN", text: "Why, then, did we abandon this wonder material? Partly knowledge loss, partly economics. Roman concrete cures slowly — weeks against days for the modern version — and modern concrete is cheap, fast and pours in any climate. Its weakness is the steel bars inside, which rust, expand and split the concrete from within. Most modern failures are really rust failures." },
          { speaker: "MAN", text: "The lesson is not to copy Rome but to borrow its chemistry. Several research teams have now produced self-healing concretes using industrial ash substitutes, and early results suggest seawater-resistant marine concretes could be commercially viable within a decade. If that happens, harbours, sea walls and even wind-farm foundations could be built to think in centuries rather than decades — which, as the Romans demonstrated in the Pantheon, concrete is perfectly capable of doing." },
        ],
      },
    ],
    groups: [
      {
        id: "l-g1", part: 1, type: "form-completion",
        heading: "Questions 1-4",
        instruction: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["DAY-TO-DAY CURRENT ACCOUNT", ""],
          rows: [
            ["Monthly fee: none if salary of at least", { gap: "l1" }, "pounds is paid in"],
            ["Otherwise the fee is 6 pounds; other banks' machines cost", { gap: "l2" }, "each"],
            ["Overdraft available after", { gap: "l3" }, "months"],
            ["Overdraft interest: 15% per year, calculated", { gap: "l4" }],
          ],
        },
        questions: [
          { id: "l1", number: 1, answer: ["500", "five hundred"], answerDisplay: "500" },
          { id: "l2", number: 2, answer: ["1.50", "1.5", "one fifty"], answerDisplay: "£1.50" },
          { id: "l3", number: 3, answer: ["three", "3"], answerDisplay: "three" },
          { id: "l4", number: 4, answer: ["daily"], answerDisplay: "daily" },
        ],
      },
      {
        id: "l-g2", part: 1, type: "mcq",
        heading: "Questions 5-10",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l5", number: 5, text: "What proof of address is acceptable?", options: [ { label: "A", text: "A letter from an employer." }, { label: "B", text: "A tenancy agreement under three months old." }, { label: "C", text: "A passport." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l6", number: 6, text: "How long can the bank hold the application?", options: [ { label: "A", text: "Three days." }, { label: "B", text: "Five days." }, { label: "C", text: "Seven days." } ], answer: ["C"], answerDisplay: "C" },
          { id: "l7", number: 7, text: "What PIN rule is mentioned?", options: [ { label: "A", text: "It must be six digits." }, { label: "B", text: "It cannot be your birthday." }, { label: "C", text: "It is posted to you." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l8", number: 8, text: "Where is the PIN set?", options: [ { label: "A", text: "At the counter." }, { label: "B", text: "On the phone." }, { label: "C", text: "At the machine by the door." } ], answer: ["C"], answerDisplay: "C" },
          { id: "l9", number: 9, text: "The permanent card arrives", options: [ { label: "A", text: "in about five working days." }, { label: "B", text: "immediately." }, { label: "C", text: "in seven weeks." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l10", number: 10, text: "What must the man remember to do with the card?", options: [ { label: "A", text: "Sign it." }, { label: "B", text: "Activate it from the app." }, { label: "C", text: "Photocopy it." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
      {
        id: "l-g3", part: 2, type: "mcq",
        heading: "Questions 11-14",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l11", number: 11, text: "When must marshals collect vests and cards?", options: [ { label: "A", text: "By 9:15." }, { label: "B", text: "By 10:00." }, { label: "C", text: "At midday." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l12", number: 12, text: "Where is the water station?", options: [ { label: "A", text: "At the finish line." }, { label: "B", text: "Halfway, by the rowing club." }, { label: "C", text: "At the bandstand." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l13", number: 13, text: "How full should water cups be?", options: [ { label: "A", text: "Completely full." }, { label: "B", text: "Halfway." }, { label: "C", text: "Empty." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l14", number: 14, text: "What should finish-line helpers watch for?", options: [ { label: "A", text: "Runners who sit down and look grey." }, { label: "B", text: "Fast finishers." }, { label: "C", text: "Lost medals." } ], answer: ["A"], answerDisplay: "A" },
        ],
      },
      {
        id: "l-g4", part: 2, type: "note-completion",
        heading: "Questions 15-20",
        instruction: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["RIVERSIDE 10K — VOLUNTEER BRIEFING", ""],
          rows: [
            ["Marshals collect yellow vests and", { gap: "l15" }, "cards"],
            ["Number of water bottles:", { gap: "l16" }],
            ["Finishers go left to the food tent or right to", { gap: "l17" }, "aid"],
            ["Race officially closes at", { gap: "l18" }],
            ["Roads reopen at twelve-fifteen; remaining runners join the", { gap: "l19" }, "van"],
            ["Lost children go to the", { gap: "l20" }],
          ],
        },
        questions: [
          { id: "l15", number: 15, answer: ["position"], answerDisplay: "position" },
          { id: "l16", number: 16, answer: ["3000", "three thousand", "3,000"], answerDisplay: "3000" },
          { id: "l17", number: 17, answer: ["first"], answerDisplay: "first" },
          { id: "l18", number: 18, answer: ["midday", "12"], answerDisplay: "midday" },
          { id: "l19", number: 19, answer: ["sweeper"], answerDisplay: "sweeper" },
          { id: "l20", number: 20, answer: ["bandstand"], answerDisplay: "bandstand" },
        ],
      },
      {
        id: "l-g5", part: 3, type: "mcq",
        heading: "Questions 21-25",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l21", number: 21, text: "What is the student's advantage for the hospital topic?", options: [ { label: "A", text: "She works part-time on a ward." }, { label: "B", text: "Her aunt is a doctor." }, { label: "C", text: "She did it before." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l22", number: 22, text: "What worries her supervisor about the hospital study?", options: [ { label: "A", text: "The topic is unpopular." }, { label: "B", text: "Ethics approval takes up to three months." }, { label: "C", text: "Hospitals are noisy already." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l23", number: 23, text: "Why is the office topic considered safer?", options: [ { label: "A", text: "Anonymous measurement with faster ethics." }, { label: "B", text: "Offices are quiet." }, { label: "C", text: "No methods needed." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l24", number: 24, text: "What angle does the friend suggest?", options: [ { label: "A", text: "Comparing hospital and office noise standards." }, { label: "B", text: "Studying silence in libraries." }, { label: "C", text: "Measuring classrooms." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l25", number: 25, text: "What role does the hospital idea take in the proposal?", options: [ { label: "A", text: "It is dropped forever." }, { label: "B", text: "It becomes future work, e.g. a master's proposal." }, { label: "C", text: "It replaces the office topic." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
      {
        id: "l-g6", part: 3, type: "table-completion",
        heading: "Questions 26-30",
        instruction: "Complete the table below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["DISSERTATION PLAN", ""],
          rows: [
            ["Proposal deadline: the end of the", { gap: "l26" }],
            ["The aunt manages an", { gap: "l27" }, "-plan office company"],
            ["The aunt's company serves as the", { gap: "l28" }, "site"],
            ["Supervisor receives the email", { gap: "l29" }, "evening"],
            ["Meeting at the library: two o'clock by the", { gap: "l30" }],
          ],
        },
        questions: [
          { id: "l26", number: 26, answer: ["month"], answerDisplay: "month" },
          { id: "l27", number: 27, answer: ["open"], answerDisplay: "open" },
          { id: "l28", number: 28, answer: ["pilot"], answerDisplay: "pilot" },
          { id: "l29", number: 29, answer: ["tonight", "this"], answerDisplay: "tonight" },
          { id: "l30", number: 30, answer: ["entrance"], answerDisplay: "entrance" },
        ],
      },
      {
        id: "l-g7", part: 4, type: "note-completion",
        heading: "Questions 31-35",
        instruction: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
        wordLimit: "ONE WORD AND/OR A NUMBER",
        table: {
          headers: ["ROMAN CONCRETE", ""],
          rows: [
            ["Key ingredient: volcanic ash called", { gap: "l31" }],
            ["When cracks appear, unreacted", { gap: "l32" }, "seals the gap"],
            ["Surprising samples came from a harbour wall near", { gap: "l33" }],
            ["Roman concrete cures in weeks, modern concrete in", { gap: "l34" }],
            ["Most modern failures are really", { gap: "l35" }, "failures"],
          ],
        },
        questions: [
          { id: "l31", number: 31, answer: ["pozzolana"], answerDisplay: "pozzolana" },
          { id: "l32", number: 32, answer: ["lime"], answerDisplay: "lime" },
          { id: "l33", number: 33, answer: ["naples", "napoli"], answerDisplay: "Naples" },
          { id: "l34", number: 34, answer: ["days"], answerDisplay: "days" },
          { id: "l35", number: 35, answer: ["rust"], answerDisplay: "rust" },
        ],
      },
      {
        id: "l-g8", part: 4, type: "mcq",
        heading: "Questions 36-40",
        instruction: "Choose the correct letter, A, B or C.",
        questions: [
          { id: "l36", number: 36, text: "The Pantheon's dome is", options: [ { label: "A", text: "reinforced with steel." }, { label: "B", text: "the largest unreinforced concrete dome ever built." }, { label: "C", text: "a modern copy." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l37", number: 37, text: "What did seawater do to the Roman harbour walls?", options: [ { label: "A", text: "Destroyed them slowly." }, { label: "B", text: "Made them stronger over centuries." }, { label: "C", text: "Nothing at all." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l38", number: 38, text: "Why was Roman concrete abandoned?", options: [ { label: "A", text: "It was banned." }, { label: "B", text: "Knowledge loss and economics — slow curing, fast modern needs." }, { label: "C", text: "It was too weak." } ], answer: ["B"], answerDisplay: "B" },
          { id: "l39", number: 39, text: "What weakens modern concrete from within?", options: [ { label: "A", text: "Rusting steel bars." }, { label: "B", text: "Too much ash." }, { label: "C", text: "Cold weather only." } ], answer: ["A"], answerDisplay: "A" },
          { id: "l40", number: 40, text: "What does the lecturer conclude about new self-healing concretes?", options: [ { label: "A", text: "They are already standard." }, { label: "B", text: "Marine versions could be viable within a decade." }, { label: "C", text: "They will never work." } ], answer: ["B"], answerDisplay: "B" },
        ],
      },
    ],
  },

  writing: {
    minutes: 60,
    tasks: [
      {
        id: "w1", taskNumber: 1, suggestedMinutes: 20, minimumWords: 150,
        prompt: "The table below shows the results of a survey about how people in one city travelled to work in 2000, 2010 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
        chart: {
          type: "bar", title: "Main method of travelling to work (%)", unit: "% of commuters",
          categories: ["2000", "2010", "2020"],
          series: [
            { name: "Car", values: [62, 54, 41] },
            { name: "Public transport", values: [25, 30, 38] },
            { name: "Cycling / walking", values: [13, 16, 21] },
          ],
        },
        sampleAnswer: "The bar chart shows how commuters in one city travelled to work in 2000, 2010 and 2020, across three modes: car, public transport, and cycling or walking. Overall, the car declined steadily from a dominant position, while both alternative modes rose, with public transport recording the largest gain. In 2000, the private car was the default choice, used by 62 per cent of commuters — more than double the figure for public transport, at 25 per cent, and nearly five times the share of cycling and walking, at 13 per cent. Over the following decade, car use fell by eight points to 54 per cent, while public transport rose to 30 per cent and active travel crept up to 16 per cent. The trend accelerated in the final decade. By 2020, car commuting had dropped to 41 per cent, losing a further thirteen points, while public transport climbed to 38 per cent — almost level with the car — and cycling or walking reached 21 per cent. In twenty years, the city therefore shifted from clear car dependence to a roughly three-way balance between the modes.",
        checklist: [
          "Overview جهت‌های کلی را می‌دهد؟",
          "داده‌های شروع و پایان هر حالت مقایسه شده؟",
          "شبیه شدن ماشین و حمل‌ونقل عمومی در ۲۰۲۰ ذکر شده؟",
          "واحد درصد ذکر شده؟",
          "حداقل ۱۵۰ کلمه؟",
        ],
      },
      {
        id: "w2", taskNumber: 2, suggestedMinutes: 40, minimumWords: 250,
        prompt: "Some people believe that university education should be free for everyone and funded by the government. Others believe students should pay at least part of the cost. Discuss both views and give your own opinion.",
        sampleAnswer: "Who should pay for university — the taxpayer, the student, or both in some proportion? The question divides governments around the world, and both positions rest on serious arguments about fairness and about what education is for. Those who support free higher education usually begin with fairness of access. If tuition is expensive, talented young people from poorer families either abandon the idea of university or begin adult life with heavy debt, while wealthier peers graduate unburdened. They also point to the social return: graduates pay more tax, staff hospitals and schools, and start the companies that employ others. On this view, since the whole society profits from graduates, the whole society — via general taxation — should carry the cost, as it already does for schools. The opposing case starts from a different fairness claim. University graduates earn substantially more than non-graduates over a lifetime, so asking them to contribute part of that gain — through fees repaid after graduation, or graduate taxes — redistributes money from the future rich to the taxpayer, many of whom never attended university. There is also a practical problem: free systems are expensive, and governments respond by capping places, which quietly ration access in a different way. In several countries that abolished fees, per-student funding and teaching quality fell before access improved. My own view is that the dichotomy is false: the question is not whether students pay but when and how. A well-designed system charges nothing up front, so no one is excluded at the door, and collects repayments only from graduates whose earnings have actually risen, protecting both equity and budgets. England's income-contingent loans and Australia's earlier version show this is workable, though both need reform to stop interest outpacing inflation. In conclusion, universal free tuition is a beautiful promise that often fails the poor in practice, while upfront fees fail them immediately. The defensible middle ground — free at the point of entry, repaid progressively by those who benefit — captures most of the justice of the first position and most of the sustainability of the second.",
        checklist: [
          "هر دو دیدگاه با استدلال مالی/عدالت بررسی شده؟",
          "نظر شخصی یک راه سوم (بازپرداخت درآمدی) پیشنهاد می‌دهد؟",
          "مثال کشورها ذکر شده؟",
          "جمع‌بندی دو موضع را به هم نزدیک می‌کند؟",
          "حداقل ۲۵۰ کلمه؟",
        ],
      },
    ],
  },
};
