"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import Sidebar from "./components/Sidebar";
import { NotificationProvider } from "@/app/context/NotificationContext";
import { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  const toggleSidebar = () => {
    setIsSidebarOpen(!isSidebarOpen);
  };

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-full flex flex-col bg-gray-50">
        <NotificationProvider>
          <Navbar toggleSidebar={toggleSidebar} isOpen={isSidebarOpen} />

          <div className="flex-1 flex flex-row-reverse overflow-hidden h-full">
            {/* عرض سایدبار 56 (برای جا دادن متن و آیکون) */}
            <div
              className={`
                w-56 md:w-70 h-full shrink-0 bg-transparent transition-all duration-300
                ${isSidebarOpen ? "block" : "hidden"} 
                md:block
              `}
            >
              <Sidebar />
            </div>

            <main className="flex-1 overflow-y-auto h-full">{children}</main>
          </div>
        </NotificationProvider>
      </body>
    </html>
  );
}
