import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import Sidebar from "./components/Sidebar";
import { NotificationProvider } from "@/app/context/NotificationContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-full flex flex-col bg-gray-50">
        <NotificationProvider>
          <Navbar />
          {/* کانتینر اصلی زیر نوبار، با ارتفاع کامل */}
          <div className="flex-1 flex flex-row-reverse overflow-hidden h-full">
            {/* اسلایدر (ضخامت 280px و ارتفاع پر) */}
            <div className="w-[280px] h-full shrink-0 bg-transparent">
              <Sidebar />
            </div>
            {/* محتوای اصلی - پدینگ حذف شد تا کاملا چسبیده باشه */}
            <main className="flex-1 overflow-y-auto h-full">{children}</main>
          </div>
        </NotificationProvider>
      </body>
    </html>
  );
}
